Repository deepchecks/deepchecks, pull requests merged in 2021-11, with the labels that each got.

#190 Oss
  .github/workflows/build.yml
  .github/workflows/lint.yml
  .github/workflows/pr.yaml
  .github/workflows/release.yml
  README.md
Labels: chore/ci

#197 imporove more info on new label check
  deepchecks/base/dataset.py
  deepchecks/checks/integrity/new_label.py
  notebooks/examples/CheckSuite_Iris_Dataset.ipynb
  tests/base/dataset_test.py
  tests/checks/integrity/new_label_test.py
Labels: kind/fix

#184 add label_ambiiguity to suite
  deepchecks/suites/integrity_suite.py
  notebooks/examples/CheckSuite_Iris_Dataset.ipynb
  notebooks/examples/basic/simple integrity demo.ipynb
  tests/suites/test_suites.py
Labels: kind/feature

#201 Documentation Website
  .github/workflows/build.yml
  .github/workflows/release.yml
  .gitignore
  docs/_templates/module.rst_t
  docs/_templates/package.rst_t
  docs/_templates/toc.rst_t
  docs/_website/.gitignore
  docs/_website/README.md
  docs/_website/babel.config.js
  docs/_website/docs/intro.md
  docs/_website/docusaurus.config.js
  docs/_website/package-lock.json
  docs/_website/package.json
  docs/_website/sidebars.js
  docs/_website/src/components/HomepageFeatures.js
  docs/_website/src/components/HomepageFeatures.module.css
  docs/_website/src/css/custom.css
  docs/_website/src/pages/index.js
  docs/_website/src/pages/index.module.css
  docs/_website/src/pages/markdown-page.md
  docs/_website/static/.nojekyll
  docs/_website/static/img/favicon.ico
  docs/_website/static/img/logo-dark.svg
  docs/_website/static/img/logo-light.svg
  docs/_website/yarn.lock
  docs/conf.py
  makefile
Labels: chore/ci

#162 Static drift tv
  deepchecks/base/dataset.py
  deepchecks/checks/distribution/__init__.py
  deepchecks/checks/distribution/plot.py
  deepchecks/checks/distribution/train_test_drift.py
  deepchecks/checks/distribution/trust_score_comparison.py
  deepchecks/checks/integrity/dominant_frequency_change.py
  deepchecks/checks/methodology/performance_overfit.py
  deepchecks/feature_importance_utils.py
  deepchecks/plot_utils.py
  deepchecks/suites/README.md
  deepchecks/suites/distribution_suite.py
  deepchecks/suites/methodology_suite.py
  deepchecks/suites/overall_suite.py
  deepchecks/version.py
  notebooks/checks/distribution/train_test_drift.ipynb
  notebooks/checks/methodology/boosting_overfit.ipynb
  notebooks/examples/CheckSuite_Iris_Dataset.ipynb
  notebooks/examples/basic/simple integrity demo.ipynb
  tests/checks/distribution/train_test_drift_test.py
  tests/conftest.py
  tests/suites/test_suites.py
Labels: kind/feature

#203 fixed_name of condition in data duplicates
  deepchecks/checks/integrity/data_duplicates.py
  deepchecks/suites/integrity_suite.py
  notebooks/examples/CheckSuite_Iris_Dataset.ipynb
  notebooks/examples/basic/simple integrity demo.ipynb
  tests/checks/integrity/data_duplicate_test.py
Labels: kind/feature

#205 fixing notebook detection
  deepchecks/utils/ipython.py
  docs/index.rst
Labels: kind/fix

#206 Renaming checksuite to suite
  deepchecks/base/suite.py
  deepchecks/suites/README.md
  deepchecks/suites/distribution_suite.py
  deepchecks/suites/integrity_suite.py
  deepchecks/suites/methodology_suite.py
  deepchecks/suites/overall_suite.py
  deepchecks/suites/performance_suite.py
  examples/drafts/condition_demo.ipynb
  examples/drafts/date_leakage.ipynb
  examples/drafts/suite_demonstration.ipynb
  extensive_testing/run_extensive_tests.py
  notebooks/checks/integrity/data_duplicates.ipynb
  notebooks/checks/methodology/date_train_validation_leakage_duplicates.ipynb
  notebooks/checks/methodology/date_train_validation_leakage_overlap.ipynb
  notebooks/examples/CheckSuite_Iris_Dataset.ipynb
  notebooks/examples/basic/simple integrity demo.ipynb
  tests/base/check_suite_test.py
  tests/suites/test_suites.py
Labels: kind/feature

#209 add rules to pylint ignore
  .pylintrc
Labels: kind/fix

#210 removing shap dep
  requirements.txt
Labels: kind/fix

#208 updated readme
  README.md
Labels: kind/feature

#207 [MLC-236] added 'from_numpy' and 'from_dict' constructors to the Dataset class
  deepchecks/base/dataset.py
  tests/base/dataset_test.py
Labels: kind/feature
