Repository deepchecks/deepchecks, pull requests merged in 2021-12, with the labels that each got.

#189 [MLC-199] added 'ModelInferenceTimeCheck';
  deepchecks/base/dataset.py
  deepchecks/checks/methodology/__init__.py
  deepchecks/checks/methodology/model_inference_time.py
  deepchecks/checks/methodology/performance_overfit.py
  deepchecks/checks/methodology/single_feature_contribution.py
  deepchecks/checks/methodology/single_feature_contribution_train_validation.py
  deepchecks/checks/performance/__init__.py
  deepchecks/suites/methodology_suite.py
  notebooks/checks/methodology/model_inference_time.ipynb
  notebooks/examples/CheckSuite_Iris_Dataset.ipynb
  notebooks/examples/basic/simple integrity demo.ipynb
  tests/checks/methodology/model_inference_time_test.py
  tests/checks/utils.py
Labels: kind/feature

#214 [MLC-153] new dataset column type
  deepchecks/base/dataset.py
  deepchecks/checks/distribution/plot.py
  deepchecks/checks/distribution/preprocessing.py
  deepchecks/checks/distribution/rare_category_encoder.py
  deepchecks/checks/distribution/train_test_drift.py
  deepchecks/checks/integrity/data_duplicates.py
  deepchecks/checks/integrity/is_single_value.py
  deepchecks/checks/integrity/label_ambiguity.py
  deepchecks/checks/integrity/mixed_nulls.py
  deepchecks/checks/integrity/mixed_types.py
  deepchecks/checks/integrity/new_category.py
  deepchecks/checks/integrity/new_label.py
  deepchecks/checks/integrity/rare_format_detection.py
  deepchecks/checks/integrity/special_chars.py
  deepchecks/checks/integrity/string_length_out_of_bounds.py
  deepchecks/checks/integrity/string_mismatch.py
  deepchecks/checks/integrity/string_mismatch_comparison.py
  deepchecks/checks/methodology/identifier_leakage.py
  deepchecks/checks/methodology/single_feature_contribution.py
  deepchecks/checks/methodology/single_feature_contribution_train_validation.py
  deepchecks/checks/methodology/train_test_samples_mix.py
  deepchecks/checks/performance/confusion_matrix_report.py
  deepchecks/checks/performance/partition.py
  deepchecks/checks/performance/segment_performance.py
  deepchecks/utils/dataframes.py
  deepchecks/utils/features.py
  deepchecks/utils/strings.py
  deepchecks/utils/typing.py
  deepchecks/utils/validation.py
  notebooks/checks/distribution/train_test_drift.ipynb
  notebooks/checks/methodology/boosting_overfit.ipynb
  notebooks/examples/CheckSuite_Iris_Dataset.ipynb
  notebooks/examples/basic/simple integrity demo.ipynb
  requirements.txt
  tests/base/dataset_test.py
  tests/suites/test_suites.py
Labels: kind/feature

#219 Mlc 274 pps
  deepchecks/checks/methodology/single_feature_contribution.py
  deepchecks/checks/methodology/single_feature_contribution_train_validation.py
  notebooks/examples/CheckSuite_Iris_Dataset.ipynb
  tests/checks/methodology/single_feature_contribution_test.py
Labels: kind/feature

#221 Removing examples notebook validations in CI
  makefile
Labels: chore/ci

#218 [MLC-271] transformed Dataset methods without args to properties;
  deepchecks/base/dataset.py
  deepchecks/checks/distribution/trust_score_comparison.py
  deepchecks/checks/integrity/dominant_frequency_change.py
  deepchecks/checks/integrity/label_ambiguity.py
  deepchecks/checks/integrity/new_category.py
  deepchecks/checks/integrity/new_label.py
  deepchecks/checks/methodology/boosting_overfit.py
  deepchecks/checks/methodology/date_train_test_leakage_duplicates.py
  deepchecks/checks/methodology/date_train_test_leakage_overlap.py
  deepchecks/checks/methodology/identifier_leakage.py
  deepchecks/checks/methodology/index_leakage.py
  deepchecks/checks/methodology/model_inference_time.py
  deepchecks/checks/methodology/performance_overfit.py
  deepchecks/checks/methodology/single_feature_contribution.py
  deepchecks/checks/methodology/single_feature_contribution_train_validation.py
  deepchecks/checks/methodology/train_test_samples_mix.py
  deepchecks/checks/methodology/unused_features.py
  deepchecks/checks/overview/columns_info.py
  deepchecks/checks/performance/calibration_metric.py
  deepchecks/checks/performance/confusion_matrix_report.py
  deepchecks/checks/performance/performance_report.py
  deepchecks/checks/performance/roc_report.py
  deepchecks/checks/performance/segment_performance.py
  deepchecks/checks/performance/simple_model_comparison.py
  deepchecks/utils/features.py
  deepchecks/utils/metrics.py
  notebooks/checks/distribution/train_test_drift.ipynb
  notebooks/checks/methodology/boosting_overfit.ipynb
  notebooks/checks/methodology/model_inference_time.ipynb
  notebooks/checks/methodology/unused_features.ipynb
  notebooks/checks/performance/performance_report.ipynb
  notebooks/checks/performance/segment_performance.ipynb
  notebooks/examples/CheckSuite_Iris_Dataset.ipynb
  notebooks/examples/basic/simple integrity demo.ipynb
  tests/base/dataset_test.py
  tests/base/feature_importance_utils_test.py
  tests/checks/integrity/dominant_frequency_change_test.py
  tests/checks/methodology/boosting_overfit_test.py
  tests/checks/methodology/performance_overfit_test.py
  tests/checks/methodology/unused_features_test.py
  tests/conftest.py
  tests/suites/test_suites.py
Labels: kind/feature

#225 [MLC-231] added TestDatasetSize check
  deepchecks/checks/methodology/__init__.py
  deepchecks/checks/methodology/datasets_size_comparison.py
  deepchecks/suites/methodology_suite.py
  notebooks/checks/methodology/datasets_size_comparison.ipynb
  tests/checks/methodology/datasets_size_comparison.py
  tests/conftest.py
Labels: kind/feature

#211 change output of performance overfit condition
  deepchecks/checks/methodology/performance_overfit.py
  deepchecks/suites/methodology_suite.py
  tests/checks/methodology/performance_overfit_test.py
Labels: kind/fix

#195 [MLC-200] added ClassPerformanceImbalanceCheck;
  deepchecks/base/dataset.py
  deepchecks/checks/performance/__init__.py
  deepchecks/checks/performance/class_performance_imbalance.py
  deepchecks/suites/performance_suite.py
  deepchecks/utils/metrics.py
  notebooks/checks/performance/class_performance_imbalance.ipynb
  notebooks/examples/CheckSuite_Iris_Dataset.ipynb
  notebooks/examples/basic/simple integrity demo.ipynb
  tests/checks/performance/class_performance_imbalance_test.py
Labels: kind/feature

#228 Remove check from check result init
  deepchecks/base/check.py
  deepchecks/base/display_suite.py
  deepchecks/base/suite.py
  deepchecks/checks/distribution/train_test_drift.py
  deepchecks/checks/distribution/trust_score_comparison.py
  deepchecks/checks/integrity/data_duplicates.py
  deepchecks/checks/integrity/dominant_frequency_change.py
  deepchecks/checks/integrity/is_single_value.py
  deepchecks/checks/integrity/label_ambiguity.py
  deepchecks/checks/integrity/mixed_nulls.py
  deepchecks/checks/integrity/mixed_types.py
  deepchecks/checks/integrity/new_category.py
  deepchecks/checks/integrity/new_label.py
  deepchecks/checks/integrity/rare_format_detection.py
  deepchecks/checks/integrity/special_chars.py
  deepchecks/checks/integrity/string_length_out_of_bounds.py
  deepchecks/checks/integrity/string_mismatch.py
  deepchecks/checks/integrity/string_mismatch_comparison.py
  deepchecks/checks/methodology/boosting_overfit.py
  deepchecks/checks/methodology/datasets_size_comparison.py
  deepchecks/checks/methodology/date_train_test_leakage_duplicates.py
  deepchecks/checks/methodology/date_train_test_leakage_overlap.py
  deepchecks/checks/methodology/identifier_leakage.py
  deepchecks/checks/methodology/index_leakage.py
  deepchecks/checks/methodology/model_inference_time.py
  deepchecks/checks/methodology/performance_overfit.py
  deepchecks/checks/methodology/single_feature_contribution.py
  deepchecks/checks/methodology/single_feature_contribution_train_validation.py
  deepchecks/checks/methodology/train_test_samples_mix.py
  deepchecks/checks/methodology/unused_features.py
  deepchecks/checks/overview/columns_info.py
  deepchecks/checks/overview/dataset_info.py
  deepchecks/checks/overview/model_info.py
  deepchecks/checks/performance/calibration_metric.py
  deepchecks/checks/performance/class_performance_imbalance.py
  deepchecks/checks/performance/confusion_matrix_report.py
  deepchecks/checks/performance/performance_report.py
  deepchecks/checks/performance/roc_report.py
  deepchecks/checks/performance/segment_performance.py
  deepchecks/checks/performance/simple_model_comparison.py
  notebooks/checks/methodology/datasets_size_comparison.ipynb
  notebooks/examples/CheckSuite_Iris_Dataset.ipynb
  tests/base/check_test.py
Labels: kind/feature

#217 [MLC-237] refactored model validation function
  deepchecks/base/dataset.py
  deepchecks/checks/distribution/trust_score_comparison.py
  deepchecks/checks/methodology/boosting_overfit.py
  deepchecks/checks/methodology/model_inference_time.py
  deepchecks/checks/methodology/performance_overfit.py
  deepchecks/checks/methodology/unused_features.py
  deepchecks/checks/performance/performance_report.py
  deepchecks/checks/performance/segment_performance.py
  deepchecks/checks/performance/simple_model_comparison.py
  deepchecks/utils/features.py
  deepchecks/utils/validation.py
  notebooks/checks/distribution/trust_score_comparison.ipynb
  tests/base/feature_importance_utils_test.py
Labels: kind/feature

#227 License add
  .github/workflows/build.yml
Labels: chore/ci

#231 Removing the dataset_info check
  .github/workflows/build.yml
  deepchecks/checks/overview/__init__.py
  deepchecks/checks/overview/dataset_info.py
  notebooks/checks/overview/dataset_info.ipynb
  requirements.txt
  tests/checks/overview/dataset_info_test.py
Labels: kind/fix

#232 Create codeql-analysis.yml
  .github/workflows/codeql-analysis.yml
Labels: chore/ci

#234 Adding snyk and removing docusaurus
  .github/workflows/build.yml
  .github/workflows/release.yml
  docs/_website/.gitignore
  docs/_website/README.md
  docs/_website/babel.config.js
  docs/_website/docs/intro.md
  docs/_website/docusaurus.config.js
  docs/_website/package-lock.json
  docs/_website/package.json
  docs/_website/sidebars.js
  docs/_website/src/components/HomepageFeatures.js
  docs/_website/src/components/HomepageFeatures.module.css
  docs/_website/src/css/custom.css
  docs/_website/src/pages/index.js
  docs/_website/src/pages/index.module.css
  docs/_website/src/pages/markdown-page.md
  docs/_website/static/.nojekyll
  docs/_website/static/img/favicon.ico
  docs/_website/static/img/logo-dark.svg
  docs/_website/static/img/logo-light.svg
  docs/_website/yarn.lock
Labels: chore/ci

#237 Updating Demo Notebooks for How-to-Guides
  README.md
  docs/images/diagram.svg
  examples/drafts/checks_demonstration.ipynb
  examples/drafts/condition_demo.ipynb
  examples/drafts/date_leakage.ipynb
  examples/drafts/suite_demonstration.ipynb
  makefile
  notebooks/examples/CheckSuite_Iris_Dataset.ipynb
  notebooks/examples/basic/simple integrity demo.ipynb
  notebooks/examples/create_a_custom_suite.ipynb
  notebooks/examples/quickstart_in_5_minutes.ipynb
Labels: chore/documentation

#233 add docs
  deepchecks/base/check.py
  deepchecks/checks/methodology/datasets_size_comparison.py
  notebooks/examples/add_a_custom_check.ipynb
  notebooks/examples/configure_check_conditions.ipynb
Labels: kind/feature

#220 regression error distribution check
  deepchecks/checks/performance/__init__.py
  deepchecks/checks/performance/regression_error_distribution.py
  deepchecks/suites/performance_suite.py
  notebooks/checks/performance/regression_error_distribution.ipynb
  tests/checks/performance/regression_error_distribution_test.py
Labels: kind/feature

#239 Removed name of check from exceptions
  deepchecks/base/dataset.py
  deepchecks/checks/distribution/train_test_drift.py
  deepchecks/checks/distribution/trust_score_comparison.py
  deepchecks/checks/integrity/dominant_frequency_change.py
  deepchecks/checks/integrity/label_ambiguity.py
  deepchecks/checks/integrity/new_category.py
  deepchecks/checks/integrity/new_label.py
  deepchecks/checks/methodology/boosting_overfit.py
  deepchecks/checks/methodology/datasets_size_comparison.py
  deepchecks/checks/methodology/date_train_test_leakage_duplicates.py
  deepchecks/checks/methodology/date_train_test_leakage_overlap.py
  deepchecks/checks/methodology/identifier_leakage.py
  deepchecks/checks/methodology/index_leakage.py
  deepchecks/checks/methodology/model_inference_time.py
  deepchecks/checks/methodology/performance_overfit.py
  deepchecks/checks/methodology/single_feature_contribution.py
  deepchecks/checks/methodology/single_feature_contribution_train_validation.py
  deepchecks/checks/methodology/train_test_samples_mix.py
  deepchecks/checks/methodology/unused_features.py
  deepchecks/checks/performance/calibration_metric.py
  deepchecks/checks/performance/class_performance_imbalance.py
  deepchecks/checks/performance/confusion_matrix_report.py
  deepchecks/checks/performance/performance_report.py
  deepchecks/checks/performance/regression_error_distribution.py
  deepchecks/checks/performance/roc_report.py
  deepchecks/checks/performance/segment_performance.py
  deepchecks/checks/performance/simple_model_comparison.py
  deepchecks/utils/features.py
  deepchecks/utils/metrics.py
  tests/base/dataset_test.py
  tests/checks/methodology/date_leakage_test.py
  tests/checks/methodology/identifier_leakage_test.py
  tests/checks/methodology/index_train_val_leakage_test.py
  tests/checks/methodology/performance_overfit_test.py
  tests/checks/methodology/single_feature_contribution_test.py
  tests/checks/performance/calibration_metric_test.py
  tests/checks/performance/confusion_matrix_report_test.py
  tests/checks/performance/performance_report_test.py
  tests/checks/performance/regression_error_distribution_test.py
  tests/checks/performance/roc_report_test.py
  tests/checks/performance/segment_performance_test.py
  tests/checks/performance/simple_model_comparison_test.py
Labels: kind/fix

#222 Regression bias
  deepchecks/checks/performance/__init__.py
  deepchecks/checks/performance/regression_systematic_error.py
  deepchecks/checks/performance/simple_model_comparison.py
  deepchecks/suites/performance_suite.py
  notebooks/checks/performance/regression_systematic_error.ipynb
  tests/checks/performance/regression_systematic_error_test.py
  tests/checks/performance/simple_model_comparison_test.py
Labels: kind/feature

#241 moving new label check to the classification suite
  deepchecks/checks/performance/segment_performance.py
  deepchecks/suites/distribution_suite.py
  deepchecks/suites/integrity_suite.py
  deepchecks/suites/performance_suite.py
Labels: kind/fix

#246 add try/except to check result
  deepchecks/base/check.py
Labels: kind/fix

#238 [Documentation][PR into 'doc-test'] suites section fix
  docs/source/api/suites/index.rst
Labels: chore/documentation

#251 adding citations
  notebooks/checks/methodology/boosting_overfit.ipynb
  notebooks/checks/methodology/unused_features.ipynb
  notebooks/checks/performance/segment_performance.ipynb
Labels: chore/documentation

#252 added to datetime formatting
  deepchecks/base/dataset.py
  tests/base/dataset_test.py
Labels: kind/feature

#254 fixed pipeline FI calculations if contains encoder
  deepchecks/utils/features.py
Labels: kind/fix

#253 patch_for_anonymous_series
  deepchecks/checks/integrity/data_duplicates.py
Labels: kind/fix

#244 [MLC-326] removed CompareDatasetsBaseCheck from codebase
  deepchecks/base/check.py
  deepchecks/base/suite.py
  deepchecks/checks/integrity/dominant_frequency_change.py
  deepchecks/checks/integrity/string_mismatch_comparison.py
  deepchecks/utils/typing.py
  notebooks/checks/integrity/dominant_frequency_change.ipynb
  notebooks/checks/integrity/string_mismatch_comparison.ipynb
  tests/base/check_suite_test.py
  tests/checks/integrity/dominant_frequency_change_test.py
  tests/checks/integrity/string_mismatch_comparison_test.py
Labels: kind/fix

#255 calibration plot will plot 1 line in case of binary
  deepchecks/checks/performance/calibration_metric.py
  notebooks/checks/performance/calibration_metric.ipynb
Labels: kind/fix

#257 Updating version on release
  .github/scripts/update_version.sh
  .github/workflows/build.yml
  .github/workflows/release.yml
  .licenserc_fix.yaml
  VERSION
  setup.py
Labels: chore/ci

#258 show conditions in single check
  deepchecks/base/check.py
  deepchecks/base/display_pandas.py
  deepchecks/base/display_suite.py
  deepchecks/base/suite.py
  notebooks/checks/methodology/datasets_size_comparison.ipynb
Labels: kind/feature

#259 added test to the fix
  tests/checks/integrity/data_duplicate_test.py
Labels: kind/tests

#262 Fixing release
  .github/workflows/release.yml
Labels: chore/ci

#261 removed_check_is_fitted
  deepchecks/utils/features.py
  deepchecks/utils/validation.py
  tests/base/feature_importance_utils_test.py
Labels: kind/feature

#263 Fixing release
  .github/workflows/release.yml
Labels: chore/ci

#264 Fixing release
  makefile
Labels: chore/ci

#256 param dict should be empty
  deepchecks/base/check.py
  tests/base/check_test.py
Labels: kind/feature

#260 same colors for train test
  deepchecks/checks/distribution/train_test_drift.py
  deepchecks/checks/distribution/trust_score_comparison.py
  deepchecks/checks/methodology/boosting_overfit.py
  deepchecks/checks/methodology/performance_overfit.py
  deepchecks/utils/plot.py
  notebooks/checks/distribution/train_test_drift.ipynb
  notebooks/checks/distribution/trust_score_comparison.ipynb
  notebooks/checks/methodology/boosting_overfit.ipynb
  notebooks/checks/methodology/performance_overfit.ipynb
  notebooks/checks/performance/calibration_metric.ipynb
  notebooks/checks/performance/class_performance_imbalance.ipynb
Labels: kind/fix

#265 Relax label constraints
  deepchecks/checks/distribution/trust_score_comparison.py
  deepchecks/utils/metrics.py
  tests/checks/distribution/trust_score_comparison_test.py
Labels: kind/fix

#266 fix tqdm problems with kaggle
  deepchecks/base/display_suite.py
  deepchecks/utils/ipython.py
Labels: kind/fix

#249 Update dataset properties
  deepchecks/base/dataset.py
  extensive_testing/run_extensive_tests.py
  makefile
  notebooks/checks/distribution/train_test_drift.ipynb
  notebooks/checks/distribution/trust_score_comparison.ipynb
  notebooks/checks/integrity/dominant_frequency_change.ipynb
  notebooks/checks/integrity/label_ambiguity.ipynb
  notebooks/checks/integrity/new_label.ipynb
  notebooks/checks/methodology/boosting_overfit.ipynb
  notebooks/checks/methodology/datasets_size_comparison.ipynb
  notebooks/checks/methodology/date_train_validation_leakage_duplicates.ipynb
  notebooks/checks/methodology/date_train_validation_leakage_overlap.ipynb
  notebooks/checks/methodology/identifier_leakage.ipynb
  notebooks/checks/methodology/index_leakage.ipynb
  notebooks/checks/methodology/model_inference_time.ipynb
  notebooks/checks/methodology/performance_overfit.ipynb
  notebooks/checks/methodology/single_feature_contribution.ipynb
  notebooks/checks/methodology/single_feature_contribution_train_test.ipynb
  notebooks/checks/methodology/train_test_samples_mix.ipynb
  notebooks/checks/methodology/unused_features.ipynb
  notebooks/checks/overview/columns_info.ipynb
  notebooks/checks/performance/calibration_metric.ipynb
  notebooks/checks/performance/class_performance_imbalance.ipynb
  notebooks/checks/performance/confusion_matrix_report.ipynb
  notebooks/checks/performance/performance_report.ipynb
  notebooks/checks/performance/regression_error_distribution.ipynb
  notebooks/checks/performance/regression_systematic_error.ipynb
  notebooks/checks/performance/roc_report.ipynb
  notebooks/checks/performance/segment_performance.ipynb
  notebooks/checks/performance/simple_model_comparison.ipynb
  notebooks/examples/create_a_custom_suite.ipynb
  notebooks/examples/quickstart_in_5_minutes.ipynb
  tests/base/dataset_test.py
  tests/checks/distribution/trust_score_comparison_test.py
  tests/checks/integrity/dominant_frequency_change_test.py
  tests/checks/integrity/label_ambiguity_test.py
  tests/checks/integrity/mixed_nulls_test.py
  tests/checks/integrity/mixed_types_test.py
  tests/checks/integrity/new_label_test.py
  tests/checks/integrity/special_chars_test.py
  tests/checks/integrity/string_length_out_of_bounds_test.py
  tests/checks/integrity/string_mismatch_comparison_test.py
  tests/checks/integrity/string_mismatch_test.py
  tests/checks/methodology/boosting_overfit_test.py
  tests/checks/methodology/date_leakage_test.py
  tests/checks/methodology/identifier_leakage_test.py
  tests/checks/methodology/index_train_val_leakage_test.py
  tests/checks/methodology/performance_overfit_test.py
  tests/checks/methodology/single_feature_contribution_test.py
  tests/checks/methodology/train_test_samples_mix_test.py
  tests/checks/overview/columns_info_test.py
  tests/checks/performance/regression_error_distribution_test.py
  tests/checks/performance/regression_systematic_error_test.py
  tests/checks/performance/roc_report_test.py
  tests/conftest.py
  tests/suites/test_suites.py
Labels: kind/feature

#269 Added pipeline support for boosting overfit
  deepchecks/checks/methodology/boosting_overfit.py
  deepchecks/utils/features.py
  deepchecks/utils/model.py
  tests/checks/methodology/boosting_overfit_test.py
Labels: kind/feature

#268 Add plotly support to check display
  deepchecks/base/check.py
  deepchecks/base/dataset.py
  requirements.txt
Labels: kind/feature

#271 Update label docs and add validation
  deepchecks/base/dataset.py
Labels: kind/fix

#229 made tests to run on windows too
  .github/workflows/build.yml
  makefile
Labels: kind/tests

#272 added_lru_for_FI
  deepchecks/checks/distribution/whole_dataset_drift.py
  deepchecks/utils/features.py
  notebooks/checks/distribution/whole_dataset_drift.ipynb
  tests/checks/distribution/whole_dataset_drift_test.py
Labels: kind/feature

#275 Removing Rare Format check
  deepchecks/checks/integrity/__init__.py
  deepchecks/checks/integrity/rare_format_detection.py
  deepchecks/suites/integrity_suite.py
  notebooks/checks/integrity/rare_format_detection.ipynb
  notebooks/examples/quickstart_in_5_minutes.ipynb
  tests/checks/integrity/rare_format_detection_test.py
Labels: kind/feature

#277 Fixing version
  docs/source/conf.py
Labels: kind/fix

#278 Update README.md
  README.md
Labels: chore/documentation

#273 Add model comparison
  deepchecks/base/check.py
  deepchecks/base/display_pandas.py
  deepchecks/base/display_suite.py
  deepchecks/base/suite.py
  deepchecks/errors.py
  deepchecks/utils/ipython.py
  notebooks/checks/distribution/whole_dataset_drift.ipynb
  notebooks/checks/methodology/datasets_size_comparison.ipynb
  notebooks/examples/configure_check_conditions.ipynb
  notebooks/examples/create_a_custom_suite.ipynb
  notebooks/examples/quickstart_in_5_minutes.ipynb
  tests/base/check_suite_test.py
  tests/suites/test_suites.py
Labels: kind/feature

#283 add name to index
  deepchecks/checks/integrity/dominant_frequency_change.py
  notebooks/checks/integrity/dominant_frequency_change.ipynb
Labels: kind/fix

#243 [MLC-364] replaced occurrence of 'metric' noun with 'score(r)' within 'deepchecks.checks.performance' package
  deepchecks/checks/methodology/boosting_overfit.py
  deepchecks/checks/methodology/performance_overfit.py
  deepchecks/checks/performance/__init__.py
  deepchecks/checks/performance/calibration_score.py
  deepchecks/checks/performance/class_performance_imbalance.py
  deepchecks/checks/performance/performance_report.py
  deepchecks/checks/performance/regression_error_distribution.py
  deepchecks/checks/performance/regression_systematic_error.py
  deepchecks/checks/performance/segment_performance.py
  deepchecks/checks/performance/simple_model_comparison.py
  deepchecks/suites/performance_suite.py
  deepchecks/utils/metrics.py
  notebooks/checks/methodology/boosting_overfit.ipynb
  notebooks/checks/methodology/performance_overfit.ipynb
  notebooks/checks/performance/calibration_score.ipynb
  notebooks/checks/performance/performance_report.ipynb
  notebooks/checks/performance/segment_performance.ipynb
  notebooks/checks/performance/simple_model_comparison.ipynb
  tests/checks/methodology/boosting_overfit_test.py
  tests/checks/methodology/performance_overfit_test.py
  tests/checks/performance/calibration_score_test.py
  tests/checks/performance/performance_report_test.py
  tests/checks/performance/simple_model_comparison_test.py
Labels: kind/fix

#280 GH pages job removal
  .github/workflows/release.yml
Labels: chore/ci

#287 Fix trust score err
  deepchecks/base/dataset.py
  deepchecks/checks/distribution/trust_score.py
  deepchecks/checks/distribution/trust_score_comparison.py
  deepchecks/checks/methodology/boosting_overfit.py
  deepchecks/checks/methodology/performance_overfit.py
  deepchecks/checks/performance/performance_report.py
  deepchecks/checks/performance/segment_performance.py
  deepchecks/checks/performance/simple_model_comparison.py
  deepchecks/utils/metrics.py
  notebooks/checks/performance/segment_performance.ipynb
  tests/base/dataset_test.py
  tests/checks/distribution/trust_score_comparison_test.py
  tests/checks/performance/performance_report_test.py
Labels: kind/fix

#240 [MLC-241] output order
  deepchecks/base/check.py
  deepchecks/base/display_pandas.py
  deepchecks/base/display_suite.py
Labels: kind/feature

#288 limit output size
  deepchecks/checks/integrity/new_category.py
  deepchecks/checks/integrity/string_mismatch.py
  notebooks/checks/integrity/new_category.ipynb
  notebooks/checks/integrity/string_mismatch.ipynb
Labels: kind/fix

#284 improve wording
  deepchecks/checks/performance/__init__.py
  deepchecks/checks/performance/class_performance.py
  deepchecks/suites/performance_suite.py
  notebooks/checks/performance/class_performance.ipynb
  notebooks/checks/performance/class_performance_imbalance.ipynb
  tests/checks/performance/class_performance_test.py
Labels: kind/fix

#290 Update utils.metric to delete duplicated code
  deepchecks/checks/methodology/boosting_overfit.py
  deepchecks/checks/methodology/performance_overfit.py
  deepchecks/checks/performance/class_performance.py
  deepchecks/checks/performance/performance_report.py
  deepchecks/checks/performance/segment_performance.py
  deepchecks/checks/performance/simple_model_comparison.py
  deepchecks/utils/metrics.py
  notebooks/checks/performance/class_performance.ipynb
  tests/checks/performance/class_performance_test.py
Labels: kind/fix, refactoring

#291 fix TypeError: unhashable type: 'numpy.ndarray'
  deepchecks/checks/distribution/trust_score_comparison.py
Labels: kind/fix

#293 disable nbval
  makefile
Labels: chore/ci

#286 [MCL-370] refactored __init__.py files
  deepchecks/__init__.py
  deepchecks/base/__init__.py
  deepchecks/base/check.py
  deepchecks/base/dataset.py
  deepchecks/base/display_pandas.py
  deepchecks/base/suite.py
  deepchecks/checks/__init__.py
  deepchecks/checks/distribution/__init__.py
  deepchecks/checks/distribution/whole_dataset_drift.py
  deepchecks/checks/integrity/__init__.py
  deepchecks/checks/integrity/data_duplicates.py
  deepchecks/checks/integrity/is_single_value.py
  deepchecks/checks/integrity/mixed_nulls.py
  deepchecks/checks/integrity/mixed_types.py
  deepchecks/checks/integrity/special_chars.py
  deepchecks/checks/integrity/string_length_out_of_bounds.py
  deepchecks/checks/integrity/string_mismatch.py
  deepchecks/checks/integrity/string_mismatch_comparison.py
  deepchecks/checks/methodology/__init__.py
  deepchecks/checks/overview/__init__.py
  deepchecks/checks/performance/__init__.py
  deepchecks/suites/__init__.py
  deepchecks/utils/validation.py
  tests/base/dataset_test.py
Labels: kind/feature

#295 Adding a cronjob to generate the examples
  .github/workflows/nb-generation.yml
  makefile
Labels: kind/feature

#298 Update nb-generation.yml
  .github/workflows/nb-generation.yml
Labels: chore/ci

#281 boosting overfit + unused features to plotly
  deepchecks/checks/methodology/boosting_overfit.py
  deepchecks/checks/methodology/unused_features.py
  notebooks/checks/methodology/boosting_overfit.ipynb
  notebooks/checks/methodology/unused_features.ipynb
Labels: kind/feature

#297 bug in dataset class?
  deepchecks/base/dataset.py
Labels: kind/fix

#302 Adding flake8 validations
  deepchecks/__init__.py
  deepchecks/base/check.py
  deepchecks/base/dataset.py
  deepchecks/base/display_pandas.py
  deepchecks/base/suite.py
  deepchecks/checks/__init__.py
  deepchecks/checks/distribution/trust_score.py
  deepchecks/checks/distribution/trust_score_comparison.py
  deepchecks/checks/integrity/__init__.py
  deepchecks/checks/integrity/data_duplicates.py
  deepchecks/checks/integrity/is_single_value.py
  deepchecks/checks/integrity/mixed_nulls.py
  deepchecks/checks/integrity/mixed_types.py
  deepchecks/checks/integrity/special_chars.py
  deepchecks/checks/integrity/string_mismatch.py
  deepchecks/checks/integrity/string_mismatch_comparison.py
  deepchecks/checks/methodology/boosting_overfit.py
  deepchecks/checks/methodology/date_train_test_leakage_duplicates.py
  deepchecks/checks/methodology/model_inference_time.py
  deepchecks/checks/methodology/single_feature_contribution_train_validation.py
  deepchecks/checks/methodology/train_test_samples_mix.py
  deepchecks/checks/methodology/unused_features.py
  deepchecks/checks/overview/columns_info.py
  deepchecks/checks/performance/__init__.py
  deepchecks/checks/performance/class_performance.py
  deepchecks/checks/performance/confusion_matrix_report.py
  deepchecks/checks/performance/regression_error_distribution.py
  deepchecks/checks/performance/regression_systematic_error.py
  deepchecks/checks/performance/roc_report.py
  deepchecks/checks/performance/segment_performance.py
  deepchecks/checks/performance/simple_model_comparison.py
  deepchecks/suites/__init__.py
  deepchecks/suites/methodology_suite.py
  deepchecks/utils/features.py
  deepchecks/utils/ipython.py
  deepchecks/utils/metrics.py
  deepchecks/utils/plot.py
  deepchecks/utils/typing.py
  deepchecks/utils/validation.py
  makefile
  tox.ini
  whitelist.txt
Labels: kind/tests

#301 Added plotly plots for performance
  deepchecks/checks/performance/calibration_score.py
  deepchecks/checks/performance/confusion_matrix_report.py
  deepchecks/checks/performance/segment_performance.py
  deepchecks/checks/performance/simple_model_comparison.py
  notebooks/checks/performance/calibration_score.ipynb
  notebooks/checks/performance/confusion_matrix_report.ipynb
  notebooks/checks/performance/segment_performance.ipynb
  notebooks/checks/performance/simple_model_comparison.ipynb
Labels: kind/feature

#305 Fixing plotly rendering in docs
  docs/source/conf.py
  notebooks/checks/performance/calibration_score.ipynb
  notebooks/checks/performance/simple_model_comparison.ipynb
Labels: chore/documentation

#294 Improve mixed types
  deepchecks/checks/__init__.py
  deepchecks/checks/integrity/__init__.py
  deepchecks/checks/integrity/mixed_data_types.py
  deepchecks/checks/integrity/mixed_nulls.py
  deepchecks/checks/integrity/special_chars.py
  deepchecks/checks/integrity/string_length_out_of_bounds.py
  deepchecks/checks/integrity/string_mismatch.py
  deepchecks/checks/overview/columns_info.py
  deepchecks/suites/integrity_suite.py
  deepchecks/utils/features.py
  docs/source/api/checks/integrity.rst
  notebooks/checks/README.md
  notebooks/checks/integrity/mixed_data_types.ipynb
  notebooks/checks/integrity/mixed_types.ipynb
  notebooks/examples/quickstart_in_5_minutes.ipynb
  tests/base/check_suite_test.py
  tests/checks/integrity/mixed_data_types_test.py
Labels: kind/feature

#306 Changing the google tags
  docs/source/_templates/layout.html
Labels: chore/documentation

#308 Improve mixed data types
  deepchecks/checks/integrity/mixed_data_types.py
  docs/source/examples/checks/integrity/mixed_data_types.nblink
  docs/source/examples/checks/integrity/mixed_types.nblink
  notebooks/checks/integrity/mixed_data_types.ipynb
Labels: kind/fix

#307 [MLC-310] refactoring; verify that private routines start with an underscore
  deepchecks/base/dataset.py
  deepchecks/base/display_pandas.py
  deepchecks/checks/distribution/plot.py
  deepchecks/checks/distribution/trust_score_comparison.py
  deepchecks/checks/integrity/special_chars.py
  deepchecks/checks/integrity/string_length_out_of_bounds.py
  deepchecks/checks/integrity/string_mismatch.py
  deepchecks/checks/integrity/string_mismatch_comparison.py
  deepchecks/checks/methodology/boosting_overfit.py
  deepchecks/checks/methodology/train_test_samples_mix.py
  deepchecks/checks/methodology/unused_features.py
  deepchecks/checks/performance/simple_model_comparison.py
Labels: kind/fix, refactoring

#310 nbgen fix
  .github/workflows/nb-generation.yml
Labels: chore/ci

#296 [MLC-379] fixed suite result display
  deepchecks/base/check.py
  deepchecks/base/display_suite.py
Labels: kind/fix

#312 [MLC-413] replaced mathplot with plotly
  deepchecks/checks/__init__.py
  deepchecks/checks/performance/regression_error_distribution.py
  deepchecks/checks/performance/regression_systematic_error.py
  examples/checks/performance/regression_error_distribution.ipynb
  examples/checks/performance/regression_systematic_error.ipynb
Labels: kind/feature

#316 hotfix - checking for datetime and index
  deepchecks/base/dataset.py
  tests/checks/methodology/date_leakage_test.py
Labels: kind/fix

#300 Add multimodel performance report
  deepchecks/base/check.py
  deepchecks/base/suite.py
  deepchecks/checks/__init__.py
  deepchecks/checks/methodology/boosting_overfit.py
  deepchecks/checks/methodology/performance_overfit.py
  deepchecks/checks/performance/__init__.py
  deepchecks/checks/performance/class_performance.py
  deepchecks/checks/performance/performance_report.py
  deepchecks/checks/performance/segment_performance.py
  deepchecks/checks/performance/simple_model_comparison.py
  deepchecks/utils/metrics.py
  docs/source/examples/checks/performance/multi_model_performance_report.nblink
  examples/checks/performance/multi_model_performance_report.ipynb
  tests/checks/performance/class_performance_test.py
  tests/checks/performance/multi_model_performance_report_test.py
  tests/checks/performance/performance_report_test.py
  whitelist.txt
Labels: kind/feature

#319 change some conditions to ConditionCategory.WARN
  deepchecks/checks/distribution/trust_score_comparison.py
  deepchecks/checks/integrity/data_duplicates.py
  deepchecks/checks/integrity/special_chars.py
  deepchecks/checks/integrity/string_length_out_of_bounds.py
  deepchecks/checks/methodology/unused_features.py
  deepchecks/checks/performance/regression_error_distribution.py
  tests/checks/distribution/trust_score_comparison_test.py
  tests/checks/integrity/data_duplicate_test.py
  tests/checks/integrity/special_chars_test.py
  tests/checks/integrity/string_length_out_of_bounds_test.py
  tests/checks/performance/regression_error_distribution_test.py
Labels: kind/fix

#313 Mlc 410 drift to plotly
  deepchecks/checks/distribution/dist_utils.py
  deepchecks/checks/distribution/plot.py
  deepchecks/checks/distribution/train_test_feature_drift.py
  deepchecks/checks/distribution/whole_dataset_drift.py
  examples/checks/distribution/train_test_feature_drift.ipynb
  examples/checks/distribution/whole_dataset_drift.ipynb
Labels: kind/feature

#320 refactor trust score to plotly
  deepchecks/checks/distribution/trust_score_comparison.py
  examples/checks/distribution/trust_score_comparison.ipynb
Labels: kind/feature

#318 Modifying plotly default backends
  deepchecks/__init__.py
  whitelist.txt
Labels: kind/fix

#326 flatten coef_ in FI calculation for linear regression
  deepchecks/utils/features.py
  tests/base/feature_importance_utils_test.py
Labels: kind/fix

#324 Fixing docs search
  docs/source/_static/css/custom.css
  docs/source/conf.py
Labels: chore/documentation

#327 Conda tries
  .github/workflows/conda_publish.yml
  .licenserc_fix.yaml
  conda-recipe/build.sh
  conda-recipe/meta.yaml
  deepchecks/.projectignore
Labels: chore/ci

#328 add explicit exception for classifiers with no predict_proba
  deepchecks/utils/metrics.py
  tests/conftest.py
  tests/utils/__init__.py
  tests/utils/metrics_test.py
Labels: kind/fix

#330 prevent Dataset object from re-inferring categorical features
  deepchecks/checks/performance/segment_performance.py
  deepchecks/checks/performance/simple_model_comparison.py
Labels: kind/fix

#325 fix calibration score check
  deepchecks/checks/performance/calibration_score.py
  tests/checks/performance/calibration_score_test.py
Labels: kind/fix

#329 fix requirement for google colab
  requirements.txt
Labels: kind/fix

#331 add train test split
  deepchecks/base/dataset.py
  tests/base/dataset_test.py
Labels: kind/feature

#334 Change "Baseline" and "Dataset" to "Train" and "Test"
  deepchecks/checks/integrity/dominant_frequency_change.py
  deepchecks/checks/integrity/string_mismatch_comparison.py
  examples/checks/integrity/dominant_frequency_change.ipynb
  examples/checks/integrity/string_mismatch_comparison.ipynb
  tests/checks/integrity/dominant_frequency_change_test.py
Labels: kind/fix

#315 [MLC-388] added limit on dataset features number for features importance calculation
  deepchecks/checks/distribution/train_test_feature_drift.py
  deepchecks/checks/distribution/whole_dataset_drift.py
  deepchecks/checks/integrity/dominant_frequency_change.py
  deepchecks/checks/integrity/mixed_data_types.py
  deepchecks/checks/integrity/mixed_nulls.py
  deepchecks/checks/integrity/special_chars.py
  deepchecks/checks/integrity/string_length_out_of_bounds.py
  deepchecks/checks/integrity/string_mismatch.py
  deepchecks/checks/integrity/string_mismatch_comparison.py
  deepchecks/checks/methodology/unused_features.py
  deepchecks/checks/overview/columns_info.py
  deepchecks/checks/performance/segment_performance.py
  deepchecks/errors.py
  deepchecks/utils/features.py
  deepchecks/utils/validation.py
  tests/base/feature_importance_utils_test.py
Labels: kind/feature

#335 * Adding the datasets module
  .gitignore
  deepchecks/datasets/__init__.py
  deepchecks/datasets/regression/__init__.py
  deepchecks/datasets/regression/avocado.py
  docs/source/api/datasets/index.rst
  docs/source/api/datasets/regression.rst
  docs/source/api/index.rst
  docs/source/api/suites/index.rst
Labels: kind/feature

#336 Mlc 457 check displays
  deepchecks/checks/integrity/data_duplicates.py
  deepchecks/checks/integrity/label_ambiguity.py
  deepchecks/utils/strings.py
  examples/checks/integrity/data_duplicates.ipynb
  examples/checks/integrity/label_ambiguity.ipynb
  tests/checks/integrity/label_ambiguity_test.py
Labels: kind/fix

#346 Adding coverage
  .github/workflows/build.yml
  makefile
Labels: chore/ci

#337 infer task type
  deepchecks/base/dataset.py
  deepchecks/checks/integrity/label_ambiguity.py
  examples/checks/integrity/label_ambiguity.ipynb
  tests/base/dataset_test.py
  tests/checks/integrity/label_ambiguity_test.py
Labels: kind/feature

#347 add r2 score
  deepchecks/checks/performance/performance_report.py
  deepchecks/utils/metrics.py
  examples/checks/performance/multi_model_performance_report.ipynb
  tests/checks/performance/multi_model_performance_report_test.py
Labels: kind/feature

#344 add minimum outlier difference
  deepchecks/checks/integrity/string_length_out_of_bounds.py
  examples/checks/integrity/string_length_out_of_bounds.ipynb
  tests/checks/integrity/string_length_out_of_bounds_test.py
Labels: kind/fix

#341 Simple model multi metric
  deepchecks/base/dataset.py
  deepchecks/checks/distribution/preprocessing.py
  deepchecks/checks/distribution/trust_score_comparison.py
  deepchecks/checks/performance/calibration_score.py
  deepchecks/checks/performance/class_performance.py
  deepchecks/checks/performance/performance_report.py
  deepchecks/checks/performance/simple_model_comparison.py
  deepchecks/utils/metrics.py
  examples/checks/performance/simple_model_comparison.ipynb
  tests/checks/methodology/performance_overfit_test.py
  tests/checks/performance/class_performance_test.py
  tests/checks/performance/performance_report_test.py
  tests/checks/performance/simple_model_comparison_test.py
  whitelist.txt
Labels: kind/feature

#365 update boosting overfit condition name
  deepchecks/checks/methodology/boosting_overfit.py
  tests/checks/methodology/boosting_overfit_test.py
Labels: kind/fix

#367 Fix model info default params
  deepchecks/checks/overview/model_info.py
  examples/checks/overview/model_info.ipynb
Labels: kind/fix

#369 moved dataset legened to the right #357
  deepchecks/checks/distribution/train_test_feature_drift.py
  examples/checks/distribution/train_test_feature_drift.ipynb
Labels: kind/fix, bug

#368 drop na_action from column.map, we already dropna
  deepchecks/checks/integrity/string_length_out_of_bounds.py
Labels: kind/fix

#370 add prediction column to RegressionErrorDistribution
  deepchecks/checks/performance/regression_error_distribution.py
  deepchecks/utils/metrics.py
  examples/checks/performance/regression_error_distribution.ipynb
Labels: kind/fix

#375 catch exception
  deepchecks/utils/strings.py
  tests/checks/integrity/string_mismatch_test.py
Labels: kind/fix

#372 replace RegressionSystematicError with box plot that has the mean as hover value
  deepchecks/checks/performance/regression_systematic_error.py
  examples/checks/performance/regression_systematic_error.ipynb
Labels: kind/fix
