Repository deepchecks/deepchecks, pull requests merged in 2022-05, with the labels that each got.

#1350 Explaining boosting overfit notebook
  docs/source/checks/tabular/methodology/plot_boosting_overfit.py
Labels: documentation

#1359 Rename check label ambiguity
  deepchecks/checks.py
  deepchecks/tabular/checks/__init__.py
  deepchecks/tabular/checks/integrity/__init__.py
  deepchecks/tabular/checks/integrity/conflicting_labels.py
  deepchecks/tabular/suites/default_suites.py
  docs/source/checks/tabular/integrity/plot_conflicting_labels.py
  tests/checks/integrity/conflicting_labels_test.py
Labels: feature

#1362 Fixing tutorials and checks examples
  docs/source/_templates/layout.html
  docs/source/auto_tutorials/index.rst
  docs/source/tutorials/vision/plot_classification_tutorial.py
  docs/source/tutorials/vision/plot_detection_tutorial.py
  docs/source/tutorials/vision/plot_simple_classification_tutorial.py
Labels: bugfix

#1366 adding submodule to each doc page
  docs/source/_templates/layout.html
Labels: documentation, bugfix

#1361 Update plot model error analysis
  deepchecks/tabular/checks/performance/segment_performance.py
  docs/source/checks/tabular/performance/plot_model_error_analysis.py
  tests/checks/performance/segment_performance_test.py
Labels: documentation

#1357 Torch transformers support
  deepchecks/vision/checks/performance/robustness_report.py
  deepchecks/vision/task_type.py
  deepchecks/vision/utils/transformations.py
  deepchecks/vision/vision_data.py
  tests/vision/checks/performance/robustness_report_test.py
  tests/vision/vision_conftest.py
Labels: feature

#1368 Added margin_quantile_filter to EMD drift score
  deepchecks/tabular/checks/distribution/train_test_feature_drift.py
  deepchecks/tabular/checks/distribution/train_test_label_drift.py
  deepchecks/tabular/checks/distribution/train_test_prediction_drift.py
  deepchecks/utils/distribution/drift.py
  deepchecks/vision/checks/distribution/image_property_drift.py
  deepchecks/vision/checks/distribution/train_test_label_drift.py
  deepchecks/vision/checks/distribution/train_test_prediction_drift.py
  tests/utils/drift_test.py
Labels: bugfix

#1356 [issue-892] modified VisionData ctor
  deepchecks/vision/vision_data.py
  tests/base/to_wandb_test.py
  tests/vision/base/test_vision_data.py
  tests/vision/checks/performance/robustness_report_test.py
  tests/vision/docs/test_plots.py
  tests/vision/vision_conftest.py
Labels: feature

#1363 Update mixed data types plot
  deepchecks/tabular/checks/integrity/mixed_data_types.py
  docs/source/checks/tabular/integrity/plot_mixed_data_types.py
Labels: documentation

#1373 redo plotly version <5.6
  requirements/requirements.txt
Labels: bugfix

#1374 Fix minor link issue & cast to float in log loss
  deepchecks/utils/single_sample_metrics.py
  docs/source/checks/tabular/performance/plot_model_error_analysis.py
Labels: bugfix

#1369 Nb/vision/new label
  deepchecks/vision/checks/__init__.py
  deepchecks/vision/checks/distribution/__init__.py
  deepchecks/vision/checks/distribution/new_labels.py
  deepchecks/vision/suites/default_suites.py
  deepchecks/vision/utils/image_functions.py
  docs/source/checks/vision/distribution/plot_new_labels.py
  tests/vision/checks/distribution/new_labels_test.py
Labels: feature

#1279 [issue-1077] Display logic refactoring
  .licenserc_fix.yaml
  deepchecks/core/check_result.py
  deepchecks/core/checks.py
  deepchecks/core/display_pandas.py
  deepchecks/core/display_suite.py
  deepchecks/core/resources/requirejs.min.js
  deepchecks/core/serialization/abc.py
  deepchecks/core/serialization/check_failure/__init__.py
  deepchecks/core/serialization/check_failure/html.py
  deepchecks/core/serialization/check_failure/json.py
  deepchecks/core/serialization/check_failure/wandb.py
  deepchecks/core/serialization/check_failure/widget.py
  deepchecks/core/serialization/check_result/__init__.py
  deepchecks/core/serialization/check_result/html.py
  deepchecks/core/serialization/check_result/json.py
  deepchecks/core/serialization/check_result/wandb.py
  deepchecks/core/serialization/check_result/widget.py
  deepchecks/core/serialization/common.py
  deepchecks/core/serialization/dataframe/__init__.py
  deepchecks/core/serialization/dataframe/html.py
  deepchecks/core/serialization/dataframe/widget.py
  deepchecks/core/serialization/suite_result/__init__.py
  deepchecks/core/serialization/suite_result/html.py
  deepchecks/core/serialization/suite_result/json.py
  deepchecks/core/serialization/suite_result/wandb.py
  deepchecks/core/serialization/suite_result/widget.py
  deepchecks/core/suite.py
  deepchecks/tabular/model_base.py
  deepchecks/tabular/suite.py
  deepchecks/utils/function.py
  deepchecks/utils/html.py
  deepchecks/utils/ipython.py
  deepchecks/utils/wandb_utils.py
  deepchecks/vision/base_checks.py
  deepchecks/vision/suite.py
  deepchecks/vision/utils/image_functions.py
  docs/source/user-guide/general/exporting_results/plot_export_outputs_to_json.py
  makefile
  requirements/dev-requirements.txt
  requirements/requirements.txt
  spelling-allowlist.txt
  tests/base/display_test.py
  tests/base/to_json_test.py
  tests/serialization/test_check_failure_serialization.py
  tests/serialization/test_check_result_serialization.py
  tests/serialization/test_suite_result_serialization.py
  tests/serialization/utils.py
Labels: feature

#1376 Add mean and median to dist plots
  deepchecks/utils/distribution/drift.py
  deepchecks/utils/distribution/plot.py
Labels: feature

#1389 Serialization subpackage fix - added __init__.py module
  deepchecks/core/check_result.py
  deepchecks/core/serialization/__init__.py
  deepchecks/core/serialization/abc.py
  deepchecks/core/serialization/check_failure/wandb.py
  deepchecks/core/serialization/check_result/html.py
  deepchecks/core/serialization/check_result/json.py
  deepchecks/core/serialization/check_result/wandb.py
  deepchecks/core/serialization/common.py
  deepchecks/core/serialization/suite_result/html.py
  deepchecks/core/serialization/suite_result/wandb.py
Labels: bugfix

#1380 [issue-1370] fixed coco labels map
  deepchecks/vision/datasets/detection/coco.py
  docs/source/checks/vision/distribution/plot_image_property_drift.py
  tests/vision/checks/distribution/heatmap_comparison_test.py
  tests/vision/checks/distribution/image_property_drift_test.py
  tests/vision/checks/distribution/new_labels_test.py
  tests/vision/checks/methodology/simple_feature_contribution_test.py
Labels: bugfix

#1390 Fix emd drift 1276 revised
  deepchecks/tabular/checks/distribution/train_test_feature_drift.py
  deepchecks/tabular/checks/distribution/train_test_label_drift.py
  deepchecks/tabular/checks/distribution/train_test_prediction_drift.py
  deepchecks/tabular/checks/distribution/whole_dataset_drift.py
  deepchecks/utils/distribution/drift.py
  deepchecks/utils/distribution/plot.py
  deepchecks/utils/distribution/preprocessing.py
  deepchecks/vision/checks/distribution/image_property_drift.py
  deepchecks/vision/checks/distribution/train_test_label_drift.py
  deepchecks/vision/checks/distribution/train_test_prediction_drift.py
  spelling-allowlist.txt
  tests/checks/distribution/train_test_feature_drift_test.py
  tests/checks/distribution/train_test_label_drift_test.py
  tests/checks/distribution/train_test_prediction_drift_test.py
  tests/utils/preprocessing_test.py
  tests/vision/checks/distribution/image_property_drift_test.py
  tests/vision/checks/distribution/train_test_label_drift_test.py
  tests/vision/checks/distribution/train_test_prediction_drift_test.py
Labels: feature

#1388 Nb/vision/map output + doc
  deepchecks/vision/checks/performance/mean_average_precision_report.py
  deepchecks/vision/metrics_utils/detection_precision_recall.py
  deepchecks/vision/metrics_utils/metrics.py
  deepchecks/vision/metrics_utils/object_detection_precision_recall.py
  deepchecks/vision/suites/default_suites.py
  docs/source/checks/vision/performance/plot_mean_average_precision_report.py
  tests/vision/checks/performance/class_performance_test.py
  tests/vision/checks/performance/image_segment_performance_test.py
  tests/vision/checks/performance/mean_average_precision_report_test.py
  tests/vision/checks/performance/robustness_report_test.py
Labels: feature

#1377 Confusion matrix normalized display
  deepchecks/tabular/checks/performance/confusion_matrix_report.py
  deepchecks/utils/plot.py
  deepchecks/utils/strings.py
  deepchecks/vision/checks/methodology/similar_image_leakage.py
  deepchecks/vision/checks/performance/confusion_matrix.py
  docs/source/checks/vision/performance/plot_confusion_matrix.py
  tests/checks/performance/confusion_matrix_report_test.py
  tests/vision/checks/performance/confusion_matrix_test.py
Labels: feature

#1391 Added feature_importance.rst
  deepchecks/utils/features.py
  docs/source/user-guide/tabular/feature_importance.rst
  tests/base/feature_importance_utils_test.py
Labels: feature

#1395 Adding spark databricks integration
  docs/source/user-guide/index.rst
  docs/source/user-guide/integrations/spark_databricks.rst
Labels: documentation

#1396 Fixing validations on GPU
  tests/vision/docs/test_plots.py
Labels: bugfix

#1413 `save_as_html` hot-fix
  deepchecks/core/check_result.py
  deepchecks/core/suite.py
  tests/base/feature_importance_utils_test.py
  tests/base/to_json_test.py
  tests/utils/drift_test.py
  tests/utils/preprocessing_test.py
  tests/vision/checks/distribution/new_labels_test.py
  tests/vision/docs/test_plots.py
Labels: bugfix

#1403 Adding pytest integration
  docs/source/user-guide/index.rst
  docs/source/user-guide/integrations/pytest.rst
Labels: documentation

#1417 Run the phishing integrity suite on a Dataset instead of a DataFrame.
  docs/source/tutorials/tabular/plot_phishing_urls.py
Labels: documentation, bugfix

#1422 Minor fixes to the vision documentation
  deepchecks/vision/classification_data.py
  deepchecks/vision/detection_data.py
  deepchecks/vision/vision_data.py
Labels: documentation

#1400 Add rst example of using H2O with deepchecks
  deepchecks/tabular/checks/integrity/string_mismatch.py
  deepchecks/tabular/checks/integrity/string_mismatch_comparison.py
  deepchecks/tabular/integrations/__init__.py
  deepchecks/tabular/integrations/h2o.py
  deepchecks/utils/features.py
  docs/source/user-guide/index.rst
  docs/source/user-guide/integrations/h2o.rst
  examples/integrations/h2o/README.rst
  examples/integrations/h2o/deepchecks_h2o_tutorial.ipynb
Labels: documentation

#1414 Nb/tabular/increase speed outlier detection + timeout
  deepchecks/core/errors.py
  deepchecks/tabular/checks/integrity/outlier_sample_detection.py
  deepchecks/tabular/suites/default_suites.py
  deepchecks/utils/array_math.py
  deepchecks/utils/gower_distance.py
  docs/source/checks/tabular/integrity/plot_outlier_sample_detection.py
  makefile
  requirements/dev-requirements.txt
  tests/checks/integrity/outlier_sample_detection_test.py
  tests/utils/test_gower_distance.py
Labels: bugfix

#1420 [BUGFIX] Serialization logic - additional fixes.
  deepchecks/core/check_result.py
  deepchecks/core/serialization/abc.py
  deepchecks/core/serialization/check_failure/html.py
  deepchecks/core/serialization/check_failure/ipython.py
  deepchecks/core/serialization/check_failure/wandb.py
  deepchecks/core/serialization/check_result/html.py
  deepchecks/core/serialization/check_result/ipython.py
  deepchecks/core/serialization/check_result/wandb.py
  deepchecks/core/serialization/common.py
  deepchecks/core/serialization/suite_result/html.py
  deepchecks/core/serialization/suite_result/ipython.py
  deepchecks/core/serialization/suite_result/wandb.py
  deepchecks/core/serialization/suite_result/widget.py
  deepchecks/core/suite.py
  deepchecks/utils/ipython.py
  deepchecks/utils/strings.py
  makefile
  tests/base/display_test.py
  tests/checks/overview/columns_info_test.py
  tests/common.py
  tests/serialization/test_check_failure_serialization.py
  tests/serialization/test_check_result_serialization.py
  tests/serialization/test_suite_result_serialization.py
  tests/vision/checks/methodology/simple_feature_contribution_test.py
  tests/vision/datasets/test_coco.py
Labels: bugfix

#1419 Simple feature fixes
  deepchecks/core/check_utils/single_feature_contribution_utils.py
  deepchecks/ppscore.py
  deepchecks/tabular/checks/methodology/single_feature_contribution_train_test.py
  deepchecks/vision/checks/methodology/simple_feature_contribution.py
  docs/source/checks/vision/methodology/plot_simple_feature_contribution.py
  tests/checks/methodology/single_feature_contribution_test.py
  tests/vision/checks/methodology/simple_feature_contribution_test.py
Labels: bugfix

#1426 Fixes to rst files.
  deepchecks/tabular/datasets/classification/phishing.py
  docs/source/user-guide/integrations/h2o.rst
  docs/source/user-guide/integrations/spark_databricks.rst
Labels: documentation, bugfix

#1432 Fix string mismatch performance
  deepchecks/tabular/checks/integrity/string_mismatch.py
  deepchecks/tabular/checks/integrity/string_mismatch_comparison.py
  deepchecks/utils/strings.py
  requirements/dev-requirements.txt
Labels: bugfix

#1434 Create about.RST
  about.RST
Labels: documentation

#1412 Airflow integration
  docs/source/_static/airflow_dag.png
  docs/source/user-guide/index.rst
  docs/source/user-guide/integrations/airflow.rst
  examples/integrations/airflow/README.rst
  examples/integrations/airflow/deepchecks_airflow_tutorial.py
  makefile
Labels: feature

#1441 Update docs main image
  docs/source/_static/checks_and_conditions.png
Labels: documentation

#1439 Add datasets tests
  .github/workflows/build.yml
  deepchecks/tabular/datasets/classification/adult.py
  deepchecks/tabular/datasets/classification/breast_cancer.py
  deepchecks/tabular/datasets/classification/iris.py
  deepchecks/tabular/datasets/classification/phishing.py
  deepchecks/tabular/datasets/regression/avocado.py
  makefile
  requirements/dev-requirements.txt
  tests/tabular/test_datasets.py
Labels: tests

#1450 Doc mainpage redirect
  docs/source/conf.py
  docs/source/getting-started/index.rst
  docs/source/user-guide/general/exporting_results/plot_exports_output_to_wandb.py
  docs/source/user-guide/index.rst
Labels: documentation

#1451 Catch warnings in detection metric
  deepchecks/vision/metrics_utils/detection_precision_recall.py
Labels: bugfix

#1446 Cramers v
  deepchecks/tabular/checks/distribution/train_test_feature_drift.py
  deepchecks/tabular/checks/distribution/train_test_label_drift.py
  deepchecks/tabular/checks/distribution/train_test_prediction_drift.py
  deepchecks/utils/distribution/drift.py
  deepchecks/vision/checks/distribution/image_property_drift.py
  deepchecks/vision/checks/distribution/train_test_label_drift.py
  deepchecks/vision/checks/distribution/train_test_prediction_drift.py
  docs/source/checks/tabular/distribution/plot_train_test_feature_drift.py
  docs/source/checks/tabular/distribution/plot_train_test_prediction_drift.py
  docs/source/checks/vision/distribution/plot_train_test_label_drift.py
  docs/source/checks/vision/distribution/plot_train_test_prediction_drift.py
  docs/source/user-guide/vision/tomato-detection/train.py
  docs/source/user-guide/vision/tutorials/plot_detection_tutorial.py
  tests/checks/distribution/train_test_feature_drift_test.py
  tests/checks/distribution/train_test_label_drift_test.py
  tests/checks/distribution/train_test_prediction_drift_test.py
  tests/vision/checks/distribution/image_dataset_drift_test.py
  tests/vision/checks/distribution/train_test_label_drift_test.py
  tests/vision/checks/distribution/train_test_prediction_drift_test.py
Labels: feature

#1428 better format validation for detection data class
  .github/workflows/build.yml
  deepchecks/vision/detection_data.py
  deepchecks/vision/utils/validation.py
  docs/source/user-guide/vision/tutorials/plot_extractors_validating.py
  tests/vision/base/test_vision_data.py
Labels: feature

#1456 Segment Performance: fix figure and unnecessary feature importance usage
  deepchecks/tabular/checks/performance/segment_performance.py
Labels: bugfix

#1458 [BUGFIX] Check/Suite Result _repr_html_ fix
  deepchecks/core/check_result.py
  deepchecks/core/serialization/suite_result/widget.py
  deepchecks/core/suite.py
  deepchecks/utils/strings.py
  tests/checks/methodology/single_feature_contribution_test.py
Labels: bugfix

#1466 Docs get started update
  deepchecks/swindler-detection/README.rst
  docs/source/conf.py
  docs/source/getting-started/get-started.rst
  docs/source/getting-started/index.rst
  docs/source/getting-started/welcome.rst
  docs/source/index.rst
  docs/source/user-guide/tabular/feature_importance.rst
Labels: documentation

#1470 Hide checks without display and remove links (widgets serializer)
  deepchecks/core/serialization/common.py
  deepchecks/core/serialization/suite_result/widget.py
Labels: bugfix

#1460 Replace logger.warnings with warnings.warn
  deepchecks/tabular/dataset.py
  deepchecks/utils/distribution/drift.py
  deepchecks/vision/context.py
  deepchecks/vision/datasets/classification/mnist.py
  deepchecks/vision/vision_data.py
  tests/base/dataset_test.py
  tests/base/feature_importance_utils_test.py
Labels: bugfix

#1442 1409 feat single dataset performance check
  .gitignore
  deepchecks/vision/checks/performance/single_dataset_scalar_performance.py
  docs/source/checks/vision/performance/plot_single_dataset_scalar_performance.py
  tests/vision/checks/performance/single_dataset_scalar_performance_test.py
Labels: feature

#1486 [issue-1340][BUGFIX] fixed TrainTestSamplesMix fillna issue
  .github/workflows/build.yml
  deepchecks/tabular/checks/train_test_validation/train_test_samples_mix.py
  tests/base/feature_importance_utils_test.py
  tests/tabular/checks/integrity/data_duplicate_test.py
  tests/tabular/checks/integrity/is_single_value_test.py
  tests/tabular/checks/integrity/mixed_data_types_test.py
  tests/tabular/checks/integrity/special_chars_test.py
  tests/tabular/checks/model_evaluation/model_inference_time_test.py
  tests/tabular/checks/model_evaluation/multi_model_performance_report_test.py
  tests/tabular/checks/model_evaluation/regression_error_distribution_test.py
  tests/tabular/checks/model_evaluation/regression_systematic_error_test.py
  tests/tabular/checks/train_test_validation/dominant_frequency_change_test.py
  tests/tabular/checks/train_test_validation/new_category_test.py
  tests/tabular/checks/train_test_validation/single_feature_contribution_test.py
  tests/tabular/checks/train_test_validation/train_test_samples_mix_test.py
  tests/tabular/test_datasets.py
  tests/vision/checks/model_evaluation/single_dataset_scalar_performance_test.py
Labels: bugfix

#1474 [Docs] Avocado Sales - Integrity Suite Quickstart
  .gitignore
  docs/source/user-guide/tabular/tutorials/plot_quick_data_integrity.py
Labels: documentation

#1482 Make sure segment performance run only on numeric or categoric features
  deepchecks/tabular/checks/model_evaluation/segment_performance.py
  deepchecks/tabular/checks/model_evaluation/train_test_prediction_drift.py
  deepchecks/tabular/suites/default_suites.py
  tests/tabular/checks/model_evaluation/segment_performance_test.py
Labels: bugfix

#1489 Add details to conditions for tabular model evaluation
  deepchecks/tabular/checks/model_evaluation/boosting_overfit.py
  deepchecks/tabular/checks/model_evaluation/model_error_analysis.py
  deepchecks/tabular/checks/model_evaluation/model_inference_time.py
  deepchecks/tabular/checks/model_evaluation/performance_report.py
  deepchecks/tabular/checks/model_evaluation/regression_error_distribution.py
  deepchecks/tabular/checks/model_evaluation/regression_systematic_error.py
  deepchecks/tabular/checks/model_evaluation/roc_report.py
  deepchecks/tabular/checks/model_evaluation/simple_model_comparison.py
  deepchecks/tabular/checks/model_evaluation/train_test_prediction_drift.py
  deepchecks/tabular/checks/model_evaluation/unused_features.py
  tests/tabular/checks/model_evaluation/boosting_overfit_test.py
  tests/tabular/checks/model_evaluation/model_error_analysis_test.py
  tests/tabular/checks/model_evaluation/model_inference_time_test.py
  tests/tabular/checks/model_evaluation/performance_report_test.py
  tests/tabular/checks/model_evaluation/regression_error_distribution_test.py
  tests/tabular/checks/model_evaluation/regression_systematic_error_test.py
  tests/tabular/checks/model_evaluation/roc_report_test.py
  tests/tabular/checks/model_evaluation/simple_model_comparison_test.py
  tests/tabular/checks/model_evaluation/train_test_prediction_drift_test.py
Labels: feature

#1478 Improve sfc 1399
  deepchecks/core/check_utils/single_feature_contribution_utils.py
  deepchecks/tabular/checks/data_integrity/single_feature_contribution.py
  deepchecks/tabular/checks/train_test_validation/single_feature_contribution_train_test.py
  deepchecks/utils/strings.py
  deepchecks/vision/checks/train_test_validation/simple_feature_contribution.py
  tests/tabular/checks/train_test_validation/single_feature_contribution_test.py
  tests/vision/checks/train_test_validation/simple_feature_contribution_test.py
Labels: refactoring

#1471 [Issue 1410] Progress Bar fix
  deepchecks/tabular/model_base.py
  deepchecks/tabular/suite.py
  deepchecks/utils/ipython.py
  deepchecks/vision/base_checks.py
  deepchecks/vision/suite.py
  spelling-allowlist.txt
  tests/utils/test_ipython.py
Labels: bugfix

#1485 Update conditions details for tabular integrity checks
  deepchecks/tabular/checks/data_integrity/conflicting_labels.py
  deepchecks/tabular/checks/data_integrity/data_duplicates.py
  deepchecks/tabular/checks/data_integrity/is_single_value.py
  deepchecks/tabular/checks/data_integrity/mixed_data_types.py
  deepchecks/tabular/checks/data_integrity/mixed_nulls.py
  deepchecks/tabular/checks/data_integrity/outlier_sample_detection.py
  deepchecks/tabular/checks/data_integrity/single_feature_contribution.py
  deepchecks/tabular/checks/data_integrity/special_chars.py
  deepchecks/tabular/checks/data_integrity/string_length_out_of_bounds.py
  deepchecks/tabular/checks/data_integrity/string_mismatch.py
  deepchecks/tabular/utils/integrity_messages.py
  tests/base/display_test.py
  tests/tabular/checks/integrity/conflicting_labels_test.py
  tests/tabular/checks/integrity/data_duplicate_test.py
  tests/tabular/checks/integrity/is_single_value_test.py
  tests/tabular/checks/integrity/mixed_data_types_test.py
  tests/tabular/checks/integrity/mixed_nulls_test.py
  tests/tabular/checks/integrity/outlier_sample_detection_test.py
  tests/tabular/checks/integrity/special_chars_test.py
  tests/tabular/checks/integrity/string_length_out_of_bounds_test.py
  tests/tabular/checks/integrity/string_mismatch_test.py
  tests/tabular/checks/train_test_validation/single_feature_contribution_test.py
Labels: feature

#1494 Fixing copybutton
  docs/source/_templates/layout.html
  docs/source/user-guide/tabular/tutorials/plot_quick_data_integrity.py
Labels: bugfix

#1484 Nb/feat/correlation methods
  deepchecks/utils/correlation_methods.py
  tests/utils/correlation_methods_test.py
Labels: feature

#1495 Tabular train-test checks conditions details
  deepchecks/tabular/checks/data_integrity/is_single_value.py
  deepchecks/tabular/checks/data_integrity/mixed_data_types.py
  deepchecks/tabular/checks/data_integrity/mixed_nulls.py
  deepchecks/tabular/checks/data_integrity/single_feature_contribution.py
  deepchecks/tabular/checks/data_integrity/special_chars.py
  deepchecks/tabular/checks/data_integrity/string_length_out_of_bounds.py
  deepchecks/tabular/checks/data_integrity/string_mismatch.py
  deepchecks/tabular/checks/train_test_validation/category_mismatch_train_test.py
  deepchecks/tabular/checks/train_test_validation/datasets_size_comparison.py
  deepchecks/tabular/checks/train_test_validation/date_train_test_leakage_duplicates.py
  deepchecks/tabular/checks/train_test_validation/date_train_test_leakage_overlap.py
  deepchecks/tabular/checks/train_test_validation/dominant_frequency_change.py
  deepchecks/tabular/checks/train_test_validation/identifier_leakage.py
  deepchecks/tabular/checks/train_test_validation/index_leakage.py
  deepchecks/tabular/checks/train_test_validation/new_label_train_test.py
  deepchecks/tabular/checks/train_test_validation/single_feature_contribution_train_test.py
  deepchecks/tabular/checks/train_test_validation/string_mismatch_comparison.py
  deepchecks/tabular/checks/train_test_validation/train_test_feature_drift.py
  deepchecks/tabular/checks/train_test_validation/train_test_label_drift.py
  deepchecks/tabular/checks/train_test_validation/train_test_samples_mix.py
  deepchecks/tabular/checks/train_test_validation/whole_dataset_drift.py
  deepchecks/tabular/utils/messages.py
  deepchecks/utils/distribution/drift.py
  tests/tabular/checks/integrity/is_single_value_test.py
  tests/tabular/checks/integrity/mixed_data_types_test.py
  tests/tabular/checks/integrity/mixed_nulls_test.py
  tests/tabular/checks/integrity/special_chars_test.py
  tests/tabular/checks/integrity/string_length_out_of_bounds_test.py
  tests/tabular/checks/integrity/string_mismatch_test.py
  tests/tabular/checks/train_test_validation/category_mismatch_test.py
  tests/tabular/checks/train_test_validation/datasets_size_comparison_test.py
  tests/tabular/checks/train_test_validation/date_leakage_test.py
  tests/tabular/checks/train_test_validation/dominant_frequency_change_test.py
  tests/tabular/checks/train_test_validation/identifier_leakage_test.py
  tests/tabular/checks/train_test_validation/index_train_val_leakage_test.py
  tests/tabular/checks/train_test_validation/new_label_test.py
  tests/tabular/checks/train_test_validation/single_feature_contribution_test.py
  tests/tabular/checks/train_test_validation/string_mismatch_comparison_test.py
  tests/tabular/checks/train_test_validation/train_test_feature_drift_test.py
  tests/tabular/checks/train_test_validation/train_test_label_drift_test.py
  tests/tabular/checks/train_test_validation/train_test_samples_mix_test.py
  tests/tabular/checks/train_test_validation/whole_dataset_drift_test.py
Labels: feature

#1499 Fix H2O subsection title
  docs/source/user-guide/integrations/h2o.rst
Labels: bugfix

#1502 Fixing avocado dataset
  deepchecks/tabular/datasets/regression/avocado.py
  docs/source/user-guide/tabular/tutorials/plot_quick_data_integrity.py
Labels: bugfix

#1491 Static model
  deepchecks/tabular/checks/data_integrity/outlier_sample_detection.py
  deepchecks/tabular/context.py
  deepchecks/tabular/dataset.py
  deepchecks/tabular/utils/validation.py
  deepchecks/utils/metrics.py
  deepchecks/vision/__init__.py
  deepchecks/vision/base_checks.py
  deepchecks/vision/classification_data.py
  deepchecks/vision/detection_data.py
  deepchecks/vision/suite.py
  tests/tabular/checks/train_test_validation/train_test_samples_mix_test.py
  tests/tabular/test_dummy_model.py
Labels: feature

#1483 [Issue-1365][V2] Plotly figures width&height
  deepchecks/core/check_result.py
  deepchecks/core/check_utils/feature_label_correlation_utils.py
  deepchecks/core/check_utils/whole_dataset_drift_utils.py
  deepchecks/core/serialization/abc.py
  deepchecks/core/serialization/check_result/widget.py
  deepchecks/core/suite.py
  deepchecks/tabular/checks/data_integrity/feature_label_correlation.py
  deepchecks/tabular/checks/model_evaluation/boosting_overfit.py
  deepchecks/tabular/checks/model_evaluation/calibration_score.py
  deepchecks/tabular/checks/model_evaluation/regression_error_distribution.py
  deepchecks/tabular/checks/model_evaluation/regression_systematic_error.py
  deepchecks/tabular/checks/model_evaluation/roc_report.py
  deepchecks/tabular/checks/model_evaluation/segment_performance.py
  deepchecks/tabular/checks/model_evaluation/unused_features.py
  deepchecks/tabular/checks/train_test_validation/identifier_leakage.py
  deepchecks/utils/distribution/drift.py
  deepchecks/utils/distribution/plot.py
  deepchecks/utils/plot.py
  deepchecks/vision/checks/model_evaluation/robustness_report.py
  tests/base/display_test.py
  tests/tabular/checks/integrity/special_chars_test.py
  tests/tabular/checks/train_test_validation/string_mismatch_comparison_test.py
  tests/tabular/test_dummy_model.py
  tests/utils/correlation_methods_test.py
Labels: bugfix

#1515 added kwargs for tabular suite + fixed missing kwargs in checks
  deepchecks/tabular/suites/default_suites.py
  deepchecks/vision/checks/train_test_validation/similar_image_leakage.py
  tests/tabular/suites/test_suites.py
  tests/vision/base/test_suite.py
Labels: bugfix

#1519 remove DominantFrequencyChange from default suite
  deepchecks/tabular/suites/default_suites.py
  docs/source/checks/tabular/train_test_validation/plot_dominant_frequency_change.py
  docs/source/user-guide/general/customizations/plot_configure_check_conditions.py
  makefile
Labels: bugfix

#1526 Fixing right nav scroll
  docs/source/_templates/layout.html
Labels: documentation

#1529 Fixing the release pipeline
  .github/workflows/release.yml
  makefile
Labels: feature

#1447 Drift guide 1066
  docs/source/_static/images/general/deepchecks_label_drift.png
  docs/source/_static/images/general/patterns-of-concept-drift.png
  docs/source/_static/images/general/types-of-drift.png
  docs/source/checks/tabular/model_evaluation/plot_train_test_prediction_drift.py
  docs/source/checks/tabular/train_test_validation/plot_train_test_feature_drift.py
  docs/source/checks/tabular/train_test_validation/plot_train_test_label_drift.py
  docs/source/checks/tabular/train_test_validation/plot_whole_dataset_drift.py
  docs/source/checks/vision/model_evaluation/plot_train_test_prediction_drift.py
  docs/source/checks/vision/train_test_validation/plot_image_dataset_drift.py
  docs/source/checks/vision/train_test_validation/plot_image_property_drift.py
  docs/source/checks/vision/train_test_validation/plot_train_test_label_drift.py
  docs/source/user-guide/general/drift_guide.rst
  docs/source/user-guide/index.rst
  docs/source/user-guide/tabular/feature_importance.rst
Labels: documentation

#1525 Static vision model
  deepchecks/vision/base_checks.py
  deepchecks/vision/batch_wrapper.py
  deepchecks/vision/classification_data.py
  deepchecks/vision/context.py
  deepchecks/vision/detection_data.py
  deepchecks/vision/vision_data.py
  tests/vision/base/test_static_predictions.py
Labels: feature, vision

#1524 Adding device to missing tests
  tests/vision/checks/model_evaluation/cv_simple_model_comparison_test.py
  tests/vision/checks/model_evaluation/image_segment_performance_test.py
  tests/vision/checks/train_test_validation/feature_label_correlation_test.py
  tests/vision/checks/train_test_validation/similar_image_leakage_test.py
Labels: bugfix

#1520 Update dataset exceptions
  deepchecks/core/errors.py
  deepchecks/core/serialization/suite_result/html.py
  deepchecks/tabular/checks/train_test_validation/identifier_leakage.py
  deepchecks/tabular/dataset.py
  deepchecks/utils/strings.py
  tests/tabular/checks/model_evaluation/calibration_score_test.py
  tests/tabular/checks/model_evaluation/confusion_matrix_report_test.py
  tests/tabular/checks/model_evaluation/model_error_analysis_test.py
  tests/tabular/checks/model_evaluation/performance_report_test.py
  tests/tabular/checks/model_evaluation/regression_error_distribution_test.py
  tests/tabular/checks/model_evaluation/regression_systematic_error_test.py
  tests/tabular/checks/model_evaluation/roc_report_test.py
  tests/tabular/checks/model_evaluation/segment_performance_test.py
  tests/tabular/checks/train_test_validation/date_leakage_test.py
  tests/tabular/checks/train_test_validation/feature_label_correlation_test.py
  tests/tabular/checks/train_test_validation/identifier_leakage_test.py
  tests/tabular/checks/train_test_validation/index_train_val_leakage_test.py
Labels: feature

#1528 Mixed data types examples
  deepchecks/tabular/checks/data_integrity/mixed_data_types.py
  tests/tabular/checks/integrity/mixed_data_types_test.py
Labels: feature

#1530 Enable validation of empty predictions
  deepchecks/tabular/suites/README.rst
  deepchecks/vision/detection_data.py
  docs/requirements.txt
  tests/vision/base/test_vision_data.py
Labels: bugfix

#1522 [issue-1448] `IsSingleValue` check - ignore nan
  deepchecks/tabular/checks/data_integrity/is_single_value.py
  docs/source/checks/tabular/data_integrity/plot_is_single_value.py
  tests/tabular/checks/integrity/is_single_value_test.py
  tests/vision/base/test_static_predictions.py
Labels: feature

#1548 Deprecation error 1536
  deepchecks/tabular/checks/model_evaluation/train_test_prediction_drift.py
  deepchecks/tabular/checks/train_test_validation/train_test_feature_drift.py
  deepchecks/tabular/checks/train_test_validation/train_test_label_drift.py
  deepchecks/tabular/deprecation_warnings.py
  deepchecks/vision/checks/model_evaluation/train_test_prediction_drift.py
  deepchecks/vision/checks/train_test_validation/train_test_label_drift.py
  deepchecks/vision/deprecation_warnings.py
Labels: bugfix

#1554 1433 feat support scikit learn 110
  .github/workflows/build.yml
  deepchecks/tabular/checks/model_evaluation/calibration_score.py
  makefile
Labels: bugfix
