Repository deepchecks/deepchecks, pull requests merged in 2022-08, with the labels that each got.

#1827 [suggestion] small fixes to the result display guide
  docs/source/user-guide/general/showing_results.rst
Labels: documentation

#1798 1770 seperate quickstarts in user guide
  .gitignore
  README.rst
  deepchecks/vision/README.rst
  docs/source/checks/tabular/train_test_validation/plot_date_train_test_leakage_duplicates.py
  docs/source/checks/tabular/train_test_validation/plot_date_train_test_leakage_overlap.py
  docs/source/conf.py
  docs/source/getting-started/welcome.rst
  docs/source/user-guide/index.rst
  docs/source/user-guide/tabular/quickstarts/README.txt
  docs/source/user-guide/tabular/quickstarts/plot_quick_data_integrity.py
  docs/source/user-guide/tabular/quickstarts/plot_quick_model_evaluation.py
  docs/source/user-guide/tabular/quickstarts/plot_quick_train_test_validation.py
  docs/source/user-guide/tabular/quickstarts/plot_quickstart_in_5_minutes.py
  docs/source/user-guide/vision/quickstarts/README.txt
  docs/source/user-guide/vision/quickstarts/plot_classification_tutorial.py
  docs/source/user-guide/vision/quickstarts/plot_detection_tutorial.py
  docs/source/user-guide/vision/quickstarts/plot_simple_classification_tutorial.py
Labels: documentation

#1851 Nb/bug/drift na
  deepchecks/core/check_utils/whole_dataset_drift_utils.py
  deepchecks/tabular/_shared_docs.py
  deepchecks/tabular/base_checks.py
  deepchecks/tabular/checks/model_evaluation/multi_model_performance_report.py
  deepchecks/tabular/context.py
  deepchecks/tabular/model_base.py
  deepchecks/tabular/suite.py
Labels: bug

#1857 Fix the deprecated import warning by importing directly from source
  deepchecks/tabular/checks/model_evaluation/single_dataset_performance.py
  deepchecks/tabular/feature_importance.py
  deepchecks/utils/distribution/drift.py
  deepchecks/vision/checks/data_integrity/abstract_property_outliers.py
  deepchecks/vision/checks/model_evaluation/image_segment_performance.py
  deepchecks/vision/checks/model_evaluation/model_error_analysis.py
  deepchecks/vision/checks/model_evaluation/robustness_report.py
  deepchecks/vision/checks/train_test_validation/property_label_correlation_change.py
  deepchecks/vision/checks/train_test_validation/similar_image_leakage.py
  deepchecks/vision/context.py
  tests/base/check_suite_test.py
  tests/examples_validation.py
  tests/tabular/checks/model_evaluation/model_error_analysis_test.py
  tests/vision/base/test_base_checks.py
  tests/vision/checks/data_integrity/image_property_outliers_test.py
  tests/vision/checks/data_integrity/label_property_outliers_test.py
  tests/vision/checks/model_evaluation/vision_model_error_analysis_test.py
Labels: bug

#1860 Correctly count the ratio of new categories
  deepchecks/tabular/checks/train_test_validation/category_mismatch_train_test.py
  docs/source/checks/vision/train_test_validation/plot_image_property_drift.py
Labels: bug

#1866 Add FeatureFeatureCorrelation to suite and fix python 3.6 bug
  deepchecks/tabular/suites/default_suites.py
  deepchecks/utils/correlation_methods.py
Labels: bug, feature

#1870 aggregation methods for object detection
  deepchecks/tabular/metric_utils/additional_classification_metrics.py
  deepchecks/tabular/metric_utils/scorers.py
  deepchecks/utils/metrics.py
  deepchecks/vision/checks/model_evaluation/class_performance.py
  deepchecks/vision/checks/model_evaluation/simple_model_comparison.py
  deepchecks/vision/checks/model_evaluation/single_dataset_performance.py
  deepchecks/vision/metrics_utils/__init__.py
  deepchecks/vision/metrics_utils/custom_scorer.py
  deepchecks/vision/metrics_utils/detection_precision_recall.py
  deepchecks/vision/metrics_utils/detection_tp_fp_fn_calc.py
  deepchecks/vision/metrics_utils/scorers.py
  tests/tabular/checks/model_evaluation/train_test_performance_test.py
  tests/utils/metrics_test.py
  tests/vision/checks/model_evaluation/class_performance_test.py
  tests/vision/checks/model_evaluation/single_dataset_performance_test.py
  tests/vision/utils_tests/metrics_test.py
Labels: bug, feature, vision

#1873 Adding a section for evaluating a suite in pytest
  docs/source/user-guide/integrations/pytest.rst
Labels: documentation

#1876 Added max_num_categories_for_display and show_categories_by to ImageDatasetDrift
  deepchecks/vision/checks/train_test_validation/image_dataset_drift.py
Labels: bug

#1799 Metrics Guide
  docs/source/user-guide/general/metrics_guide.rst
  docs/source/user-guide/index.rst
  examples/examples_metrics_guide.py
Labels: documentation

#1881 Fixing bugs in the docs
  docs/source/conf.py
  requirements/dev-requirements.txt
Labels: documentation

#1877 Fix links
  docs/source/checks/tabular/custom/plot_create_a_custom_check.py
  docs/source/user-guide/general/customizations/plot_create_a_custom_check.py
  docs/source/user-guide/tabular/custom_check_templates.rst
  docs/source/user-guide/vision/custom_check_templates.rst
Labels: bug

#1879 Fix issues with image docs
  deepchecks/vision/checks/train_test_validation/image_property_drift.py
  docs/source/checks/vision/model_evaluation/plot_train_test_prediction_drift.py
  docs/source/checks/vision/train_test_validation/plot_image_property_drift.py
Labels: documentation, bug

#1882 Adding warning if the user is not on the latest version
  deepchecks/__init__.py
  deepchecks/analytics/anonymous_telemetry.py
  docs/source/getting-started/installation.rst
Labels: feature

#1864 1706 static properties
  deepchecks/vision/base_checks.py
  deepchecks/vision/batch_wrapper.py
  deepchecks/vision/checks/data_integrity/abstract_property_outliers.py
  deepchecks/vision/checks/data_integrity/image_property_outliers.py
  deepchecks/vision/checks/data_integrity/label_property_outliers.py
  deepchecks/vision/checks/model_evaluation/image_segment_performance.py
  deepchecks/vision/checks/model_evaluation/model_error_analysis.py
  deepchecks/vision/checks/model_evaluation/train_test_prediction_drift.py
  deepchecks/vision/checks/train_test_validation/image_dataset_drift.py
  deepchecks/vision/checks/train_test_validation/image_property_drift.py
  deepchecks/vision/checks/train_test_validation/property_label_correlation_change.py
  deepchecks/vision/checks/train_test_validation/train_test_label_drift.py
  deepchecks/vision/context.py
  deepchecks/vision/utils/image_properties.py
  deepchecks/vision/utils/label_prediction_properties.py
  deepchecks/vision/utils/vision_properties.py
  docs/source/checks/vision/train_test_validation/plot_image_property_drift.py
  docs/source/user-guide/vision/tutorials/plot_custom_task_tutorial.py
  tests/base/check_suite_test.py
  tests/base/feature_importance_utils_test.py
  tests/base/test_tabular_deprecation_warnings.py
  tests/tabular/checks/model_evaluation/model_error_analysis_test.py
  tests/tabular/checks/model_evaluation/single_dataset_performance_test.py
  tests/tabular/checks/model_evaluation/train_test_prediction_drift_test.py
  tests/tabular/test_feature_importance_user_utils.py
  tests/utils/metrics_test.py
  tests/vision/base/test_base_checks.py
  tests/vision/base/test_static_properties.py
  tests/vision/checks/data_integrity/image_property_outliers_test.py
  tests/vision/checks/data_integrity/label_property_outliers_test.py
  tests/vision/checks/model_evaluation/class_performance_test.py
  tests/vision/checks/model_evaluation/train_test_prediction_drift_test.py
  tests/vision/checks/train_test_validation/image_property_drift_test.py
  tests/vision/checks/train_test_validation/property_label_correlation_change_test.py
  tests/vision/checks/train_test_validation/train_test_label_drift_test.py
  tests/vision/datasets/test_simple.py
  tests/vision/utils_tests/properties_utils_tests.py
Labels: refactoring, feature, vision

#1891 remove 'actual' kwarg from testing
  deepchecks/utils/features.py
  requirements/dev-requirements.txt
  tests/base/dataset_test.py
  tests/conftest.py
  tests/tabular/checks/train_test_validation/datasets_size_comparison_test.py
Labels: bug

#1890 fix feature order in TrainTestFeatureDrift if a column is selected
  deepchecks/tabular/checks/train_test_validation/train_test_feature_drift.py
  tests/tabular/checks/train_test_validation/train_test_feature_drift_test.py
Labels: bug

#1896 Fixing feat imp to skip running feature importance with static predictions
  deepchecks/tabular/context.py
Labels: bug

#1894 add details for columns_info check
  docs/source/checks/tabular/data_integrity/plot_columns_info.py
Labels: documentation

#1885 [Issue-1739] Suite/check instances serialization/deserialization to/from config
  .github/scripts/update_version.sh
  .github/workflows/release.yml
  .licenserc_fix.yaml
  MANIFEST.in
  VERSION
  deepchecks/__init__.py
  deepchecks/core/checks.py
  deepchecks/core/common.py
  deepchecks/core/suite.py
  deepchecks/tabular/checks/data_integrity/feature_label_correlation.py
  deepchecks/tabular/checks/model_evaluation/boosting_overfit.py
  deepchecks/tabular/checks/model_evaluation/model_error_analysis.py
  deepchecks/tabular/checks/model_evaluation/multi_model_performance_report.py
  deepchecks/tabular/checks/model_evaluation/segment_performance.py
  deepchecks/tabular/checks/model_evaluation/simple_model_comparison.py
  deepchecks/tabular/checks/model_evaluation/single_dataset_performance.py
  deepchecks/tabular/checks/model_evaluation/train_test_performance.py
  deepchecks/tabular/checks/model_evaluation/weak_segments_performance.py
  deepchecks/utils/docref.py
  deepchecks/utils/function.py
  deepchecks/vision/checks/model_evaluation/single_dataset_performance.py
  deepchecks/vision/checks/model_evaluation/train_test_prediction_drift.py
  deepchecks/vision/checks/train_test_validation/train_test_label_drift.py
  deepchecks/vision/utils/vision_properties.py
  docs/source/conf.py
  makefile
  requirements/requirements.txt
  setup.py
  spelling-allowlist.txt
  tests/base/check_suite_test.py
  tests/base/check_test.py
  tests/tabular/checks/model_evaluation/train_test_performance_test.py
Labels: refactoring, feature, dev

#1898 l2 combination feature drift
  .github/workflows/build.yml
  deepchecks/tabular/checks/train_test_validation/train_test_feature_drift.py
  tests/tabular/checks/train_test_validation/train_test_feature_drift_test.py
Labels: feature

#1915 [Issue-1846] fixed CheckResult.priority property
  deepchecks/core/check_result.py
  deepchecks/core/serialization/check_result/json.py
  deepchecks/core/serialization/suite_result/widget.py
Labels: bug

#1916 Nb/bug/small fixes
  deepchecks/core/check_utils/whole_dataset_drift_utils.py
  deepchecks/core/serialization/common.py
  deepchecks/tabular/checks/model_evaluation/train_test_prediction_drift.py
  deepchecks/tabular/checks/train_test_validation/train_test_feature_drift.py
  deepchecks/tabular/checks/train_test_validation/train_test_label_drift.py
  deepchecks/utils/distribution/drift.py
  deepchecks/utils/features.py
  deepchecks/vision/checks/model_evaluation/train_test_prediction_drift.py
  deepchecks/vision/checks/train_test_validation/image_property_drift.py
  deepchecks/vision/checks/train_test_validation/train_test_label_drift.py
  tests/tabular/checks/model_evaluation/train_test_prediction_drift_test.py
  tests/tabular/checks/train_test_validation/train_test_feature_drift_test.py
Labels: bug

#1911 bug fixed
  deepchecks/tabular/checks/data_integrity/conflicting_labels.py
Labels: bug

#1910 Documentation/static predictions vision
  docs/source/user-guide/index.rst
  docs/source/user-guide/vision/using_precomputed_predictions_vision.rst
  examples/vision/precomputed_predictions_examples.py
Labels: documentation, vision

#1919 Vision Properties v2
  deepchecks/vision/batch_wrapper.py
  deepchecks/vision/checks/data_integrity/abstract_property_outliers.py
  deepchecks/vision/checks/data_integrity/image_property_outliers.py
  deepchecks/vision/checks/data_integrity/label_property_outliers.py
  deepchecks/vision/checks/model_evaluation/image_segment_performance.py
  deepchecks/vision/checks/model_evaluation/model_error_analysis.py
  deepchecks/vision/checks/model_evaluation/train_test_prediction_drift.py
  deepchecks/vision/checks/train_test_validation/image_dataset_drift.py
  deepchecks/vision/checks/train_test_validation/image_property_drift.py
  deepchecks/vision/checks/train_test_validation/property_label_correlation_change.py
  deepchecks/vision/checks/train_test_validation/train_test_label_drift.py
  deepchecks/vision/context.py
  deepchecks/vision/utils/vision_properties.py
  requirements/requirements.txt
  tests/vision/base/test_static_properties.py
  tests/vision/checks/data_integrity/image_property_outliers_test.py
  tests/vision/checks/data_integrity/label_property_outliers_test.py
Labels: bug, feature

#1924 Remove percent change from display of label correlation checks
  deepchecks/core/check_utils/feature_label_correlation_utils.py
Labels: feature, ds

#1922 Add option to sort columns in drift according to drift + importance
  deepchecks/tabular/checks/train_test_validation/train_test_feature_drift.py
  tests/tabular/checks/train_test_validation/train_test_feature_drift_test.py
Labels: feature

#1925 Fixed truncate_zero_percent
  deepchecks/utils/strings.py
  spelling-allowlist.txt
Labels: bug

#1897 1608 property label correlation check
  deepchecks/utils/dataframes.py
  deepchecks/vision/checks/__init__.py
  deepchecks/vision/checks/data_integrity/__init__.py
  deepchecks/vision/checks/data_integrity/property_label_correlation.py
  deepchecks/vision/checks/train_test_validation/property_label_correlation_change.py
  deepchecks/vision/suites/default_suites.py
  deepchecks/vision/utils/property_label_correlation_utils.py
  docs/source/checks/vision/data_integrity/plot_property_label_correlation.py
  docs/source/checks/vision/train_test_validation/plot_property_label_correlation_change.py
  tests/utils/dataframes_test.py
  tests/vision/checks/data_integrity/property_label_correlation_test.py
  tests/vision/checks/train_test_validation/property_label_correlation_change_test.py
Labels: feature, vision

#1923 Categorical drift methods update
  deepchecks/tabular/checks/model_evaluation/train_test_prediction_drift.py
  deepchecks/tabular/checks/train_test_validation/train_test_feature_drift.py
  deepchecks/tabular/checks/train_test_validation/train_test_label_drift.py
  deepchecks/utils/distribution/drift.py
  deepchecks/utils/distribution/plot.py
  deepchecks/utils/distribution/preprocessing.py
  deepchecks/vision/checks/model_evaluation/train_test_prediction_drift.py
  deepchecks/vision/checks/train_test_validation/image_property_drift.py
  deepchecks/vision/checks/train_test_validation/train_test_label_drift.py
  tests/tabular/checks/model_evaluation/train_test_prediction_drift_test.py
  tests/tabular/checks/train_test_validation/train_test_feature_drift_test.py
  tests/utils/drift_test.py
  tests/utils/preprocessing_test.py
  tests/vision/base/test_static_predictions.py
  tests/vision/checks/model_evaluation/train_test_prediction_drift_test.py
  tests/vision/checks/train_test_validation/train_test_label_drift_test.py
Labels: bug

#1926 [issue-1917] result.show_in_window fix
  deepchecks/core/display.py
Labels: bug

#1921 [DOC] Consistent structure for tabular and vision checks #1893
  docs/source/checks/tabular/data_integrity/plot_columns_info.py
  docs/source/checks/tabular/data_integrity/plot_conflicting_labels.py
  docs/source/checks/tabular/data_integrity/plot_data_duplicates.py
  docs/source/checks/tabular/data_integrity/plot_feature_feature_correlation.py
  docs/source/checks/tabular/data_integrity/plot_feature_label_correlation.py
  docs/source/checks/tabular/data_integrity/plot_identifier_label_correlation.py
  docs/source/checks/tabular/data_integrity/plot_is_single_value.py
  docs/source/checks/tabular/data_integrity/plot_mixed_data_types.py
  docs/source/checks/tabular/data_integrity/plot_mixed_nulls.py
  docs/source/checks/tabular/data_integrity/plot_outlier_sample_detection.py
  docs/source/checks/tabular/data_integrity/plot_percent_of_nulls.py
  docs/source/checks/tabular/data_integrity/plot_special_chars.py
  docs/source/checks/tabular/data_integrity/plot_string_length_out_of_bounds.py
  docs/source/checks/tabular/data_integrity/plot_string_mismatch.py
Labels: documentation

#1886 [FEAT] Add package installation explanation to vision quickstarts
  docs/source/user-guide/vision/quickstarts/plot_simple_classification_tutorial.py
Labels: documentation

#1935 Adding concurrency to CI jobs
  .github/workflows/benchmark.yml
  .github/workflows/build.yml
  .github/workflows/docs.yaml
  .github/workflows/lint.yml
Labels: ci

#1933 `AveragePrecisionRecall._evaluate_image`: Don't recompute on each `min_iou`.
  deepchecks/vision/metrics_utils/detection_precision_recall.py
Labels: bug

#1936 run time improvements
  deepchecks/tabular/context.py
  deepchecks/tabular/metric_utils/scorers.py
Labels: feature

#1937 1863 resolve two ways of passing n samples to vision suites checks
  deepchecks/vision/_shared_docs.py
  deepchecks/vision/checks/train_test_validation/image_dataset_drift.py
  deepchecks/vision/suites/default_suites.py
  tests/vision/checks/train_test_validation/image_dataset_drift_test.py
Labels: bug, vision

#1954 fixing md5 coco
  deepchecks/vision/datasets/detection/coco.py
  deepchecks/vision/datasets/segmentation/segmentation_coco.py
  docs/source/user-guide/vision/tutorials/plot_custom_task_tutorial.py
  makefile
  tests/vision/checks/train_test_validation/property_label_correlation_change_test.py
Labels: ci, bug

#1956 [DOCS] Many docs fixes (links, various warnings, and content updates)
  .gitignore
  deepchecks/tabular/checks/model_evaluation/model_error_analysis.py
  deepchecks/tabular/checks/model_evaluation/simple_model_comparison.py
  deepchecks/tabular/checks/model_evaluation/train_test_performance.py
  deepchecks/tabular/dataset.py
  deepchecks/tabular/datasets/classification/adult.py
  deepchecks/tabular/suites/default_suites.py
  deepchecks/vision/_shared_docs.py
  deepchecks/vision/checks/data_integrity/abstract_property_outliers.py
  deepchecks/vision/checks/data_integrity/image_property_outliers.py
  deepchecks/vision/checks/data_integrity/label_property_outliers.py
  deepchecks/vision/checks/data_integrity/property_label_correlation.py
  deepchecks/vision/checks/model_evaluation/image_segment_performance.py
  deepchecks/vision/checks/model_evaluation/model_error_analysis.py
  deepchecks/vision/checks/model_evaluation/train_test_prediction_drift.py
  deepchecks/vision/checks/train_test_validation/image_dataset_drift.py
  deepchecks/vision/checks/train_test_validation/image_property_drift.py
  deepchecks/vision/checks/train_test_validation/property_label_correlation_change.py
  deepchecks/vision/checks/train_test_validation/train_test_label_drift.py
  deepchecks/vision/suites/default_suites.py
  docs/source/api/deepchecks.tabular.suites.rst
  docs/source/api/deepchecks.vision.suites.rst
  docs/source/checks/tabular/custom/plot_create_a_custom_check.py
  docs/source/checks/tabular/data_integrity/plot_columns_info.py
  docs/source/checks/tabular/data_integrity/plot_feature_label_correlation.py
  docs/source/checks/tabular/data_integrity/plot_identifier_label_correlation.py
  docs/source/checks/tabular/data_integrity/plot_is_single_value.py
  docs/source/checks/tabular/data_integrity/plot_mixed_nulls.py
  docs/source/checks/tabular/data_integrity/plot_outlier_sample_detection.py
  docs/source/checks/tabular/data_integrity/plot_percent_of_nulls.py
  docs/source/checks/tabular/data_integrity/plot_special_chars.py
  docs/source/checks/tabular/data_integrity/plot_string_length_out_of_bounds.py
  docs/source/checks/tabular/model_evaluation/plot_single_dataset_performance.py
  docs/source/checks/tabular/model_evaluation/plot_train_test_performance.py
  docs/source/checks/tabular/train_test_validation/plot_feature_label_correlation_change.py
  docs/source/checks/vision/custom/plot_create_a_custom_check.py
  docs/source/checks/vision/model_evaluation/plot_class_performance.py
  docs/source/checks/vision/train_test_validation/plot_property_label_correlation_change.py
  docs/source/conf.py
  docs/source/getting-started/welcome.rst
  docs/source/user-guide/general/customizations/plot_create_a_custom_check.py
  docs/source/user-guide/general/deepchecks_hierarchy.rst
  docs/source/user-guide/general/export_save_results.rst
  docs/source/user-guide/general/metrics_guide.rst
  docs/source/user-guide/tabular/custom_check_templates.rst
  docs/source/user-guide/tabular/feature_importance.rst
  docs/source/user-guide/tabular/quickstarts/plot_quick_model_evaluation.py
  docs/source/user-guide/tabular/quickstarts/plot_quick_train_test_validation.py
  docs/source/user-guide/tabular/supported_models.rst
  docs/source/user-guide/tabular/tutorials/plot_add_a_custom_check.py
  docs/source/user-guide/vision/custom_check_templates.rst
  docs/source/user-guide/vision/data-classes/index.rst
  docs/source/user-guide/vision/quickstarts/plot_classification_tutorial.py
  docs/source/user-guide/vision/quickstarts/plot_detection_tutorial.py
  docs/source/user-guide/vision/quickstarts/plot_simple_classification_tutorial.py
  docs/source/user-guide/vision/tutorials/plot_custom_checks.py
  docs/source/user-guide/vision/tutorials/plot_extractors_validating.py
  docs/source/user-guide/vision/using_precomputed_predictions_vision.rst
  docs/source/user-guide/vision/vision_properties.rst
Labels: documentation

#1950 make unused feature a single dataset check
  deepchecks/tabular/checks/model_evaluation/unused_features.py
  deepchecks/tabular/feature_importance.py
  docs/source/checks/tabular/model_evaluation/plot_unused_features.py
  tests/tabular/checks/model_evaluation/unused_features_test.py
Labels: bug

#1943 Reduce mixin v2
  deepchecks/core/check_result.py
  deepchecks/core/checks.py
  deepchecks/core/reduce_classes.py
  deepchecks/tabular/checks/data_integrity/percent_of_nulls.py
  deepchecks/tabular/checks/model_evaluation/single_dataset_performance.py
  deepchecks/tabular/checks/model_evaluation/train_test_performance.py
  deepchecks/tabular/checks/model_evaluation/train_test_prediction_drift.py
  deepchecks/tabular/checks/train_test_validation/category_mismatch_train_test.py
  deepchecks/tabular/checks/train_test_validation/new_label_train_test.py
  deepchecks/tabular/checks/train_test_validation/train_test_feature_drift.py
  deepchecks/tabular/checks/train_test_validation/train_test_label_drift.py
  deepchecks/vision/checks/model_evaluation/single_dataset_performance.py
  deepchecks/vision/checks/model_evaluation/train_test_prediction_drift.py
  deepchecks/vision/checks/train_test_validation/image_property_drift.py
  deepchecks/vision/checks/train_test_validation/new_labels.py
  deepchecks/vision/checks/train_test_validation/train_test_label_drift.py
  tests/tabular/checks/integrity/percent_of_nulls_test.py
  tests/tabular/checks/train_test_validation/category_mismatch_test.py
  tests/vision/checks/train_test_validation/image_property_drift_test.py
Labels: feature

#1958 1900 nlp tf idf drift check PR draft
  deepchecks/nlp/checks/__init__.py
  deepchecks/nlp/checks/train_test_validation/__init__.py
  deepchecks/nlp/checks/train_test_validation/keyword_frequency_drift.py
  deepchecks/nlp/context.py
  deepchecks/nlp/text_data.py
  deepchecks/utils/distribution/drift.py
  deepchecks/utils/distribution/plot.py
  tests/conftest.py
  tests/nlp/checks/train_test_validation/keyword_frequency_drift_test.py
  tests/nlp/nlp_conftest.py
Labels: feature, nlp

#1946 Dataset name
  deepchecks/core/check_utils/feature_label_correlation_utils.py
  deepchecks/core/check_utils/whole_dataset_drift_utils.py
  deepchecks/tabular/checks/data_integrity/feature_label_correlation.py
  deepchecks/tabular/checks/model_evaluation/train_test_performance.py
  deepchecks/tabular/checks/train_test_validation/feature_label_correlation_change.py
  deepchecks/tabular/checks/train_test_validation/train_test_feature_drift.py
  deepchecks/tabular/checks/train_test_validation/train_test_label_drift.py
  deepchecks/tabular/checks/train_test_validation/whole_dataset_drift.py
  deepchecks/tabular/context.py
  deepchecks/tabular/dataset.py
  deepchecks/utils/distribution/drift.py
  deepchecks/utils/distribution/plot.py
  deepchecks/utils/plot.py
  deepchecks/vision/checks/data_integrity/property_label_correlation.py
  deepchecks/vision/checks/train_test_validation/heatmap_comparison.py
  deepchecks/vision/checks/train_test_validation/image_dataset_drift.py
  deepchecks/vision/checks/train_test_validation/image_property_drift.py
  deepchecks/vision/checks/train_test_validation/new_labels.py
  deepchecks/vision/checks/train_test_validation/property_label_correlation_change.py
  deepchecks/vision/checks/train_test_validation/similar_image_leakage.py
  deepchecks/vision/checks/train_test_validation/train_test_label_drift.py
  deepchecks/vision/context.py
  deepchecks/vision/vision_data.py
  docs/source/user-guide/tabular/dataset_object.rst
  docs/source/user-guide/vision/data-classes/VisionData.rst
  tests/tabular/checks/train_test_validation/feature_label_correlation_test.py
  tests/vision/checks/train_test_validation/heatmap_comparison_test.py
Labels: refactoring

#1955 Changed gower distance to use actual given samples instead of only indices.
  deepchecks/utils/gower_distance.py
  tests/utils/test_gower_distance.py
Labels: feature

#1968 minor fix to the default dataset name
  deepchecks/core/check_utils/single_dataset_performance_base.py
  deepchecks/utils/distribution/drift.py
  deepchecks/utils/distribution/plot.py
Labels: bug, nlp

#1966 minor improvement in cramers-v runtime
  deepchecks/utils/distribution/preprocessing.py
  tests/utils/drift_test.py
Labels: feature
