Repository deepchecks/deepchecks, pull requests merged in 2022-06, with the labels that each got.

#1557 Fixing API reference
  docs/source/api/deepchecks.core.rst
  docs/source/api/deepchecks.tabular.rst
  docs/source/api/deepchecks.vision.rst
Labels: documentation

#1558 static_model_suites_fix
  deepchecks/tabular/checks/model_evaluation/unused_features.py
  deepchecks/tabular/context.py
  deepchecks/tabular/suite.py
  deepchecks/vision/suite.py
  tests/tabular/test_dummy_model.py
  tests/vision/base/test_static_predictions.py
Labels: bugfix

#1563 Centralize Requirements dir and file to variable
  makefile
Labels: ci

#1549 [Issue-1443] tabular Dataset repr
  deepchecks/tabular/dataset.py
  tests/tabular/test_dummy_model.py
  tests/vision/base/test_static_predictions.py
  tests/vision/checks/train_test_validation/new_labels_test.py
Labels: feature

#1559 Some performance reduce-mixin fixes
  deepchecks/core/check_result.py
  deepchecks/tabular/checks/model_evaluation/performance_report.py
  tests/tabular/checks/model_evaluation/performance_report_test.py
Labels: bugfix

#1570 Fixed bug in cramers V for single value
  .github/workflows/label-new-issue.yml
  deepchecks/utils/distribution/drift.py
  tests/utils/drift_test.py
Labels: bugfix, hotfix

#1568 Add display in python gui
  deepchecks/core/check_json.py
  deepchecks/core/check_result.py
  deepchecks/core/serialization/check_result/html.py
  deepchecks/core/suite.py
  deepchecks/utils/display.py
  deepchecks/utils/html.py
  deepchecks/vision/utils/image_functions.py
Labels: feature

#1579 Nb/infa/pylint violations fix
  makefile
  tests/base/check_suite_test.py
  tests/base/check_test.py
  tests/base/dataset_test.py
  tests/base/display_test.py
  tests/base/feature_importance_utils_test.py
  tests/base/test_tabular_deprecation_warnings.py
  tests/base/to_wandb_test.py
Labels: ci

#1578 improved condition argument for feature drift
  deepchecks/tabular/checks/train_test_validation/train_test_feature_drift.py
  deepchecks/utils/distribution/drift.py
  tests/tabular/checks/train_test_validation/train_test_feature_drift_test.py
  tests/vision/checks/model_evaluation/train_test_prediction_drift_test.py
Labels: bugfix

#1581 base form operates only if at least one alphanumeric char exist
  deepchecks/tabular/checks/data_integrity/special_chars.py
  deepchecks/utils/strings.py
  tests/base/feature_importance_utils_test.py
  tests/tabular/checks/integrity/mixed_nulls_test.py
Labels: bugfix

#1590 Bugfix/seg infinite loop
  deepchecks/tabular/checks/model_evaluation/unused_features.py
  deepchecks/utils/performance/partition.py
  docs/requirements.txt
  docs/source/user-guide/vision/data-classes/VisionData.rst
  makefile
Labels: bugfix

#1595 adding lending club dataset to __init__
  deepchecks/tabular/datasets/classification/__init__.py
Labels: bugfix

#1594 Add passed function to suite result
  deepchecks/core/check_result.py
  deepchecks/core/condition.py
  deepchecks/core/suite.py
  deepchecks/tabular/dataset.py
  deepchecks/vision/checks/model_evaluation/class_performance.py
  deepchecks/vision/checks/model_evaluation/single_dataset_scalar_performance.py
  docs/source/checks/tabular/data_integrity/plot_string_mismatch.py
  tests/base/check_suite_test.py
  tests/base/check_test.py
  tests/base/utils.py
  tests/vision/checks/model_evaluation/class_performance_test.py
  tests/vision/checks/model_evaluation/single_dataset_scalar_performance_test.py
  tests/vision/checks/train_test_validation/image_property_drift_test.py
Labels: bugfix

#1531 [DOCS] train test validation quickstart
  docs/source/user-guide/tabular/tutorials/plot_quick_data_integrity.py
  docs/source/user-guide/tabular/tutorials/plot_quick_train_test_validation.py
Labels: documentation

#1562 static_model_tab_docs
  deepchecks/tabular/context.py
  deepchecks/tabular/utils/validation.py
  docs/source/user-guide/tabular/supported_models.rst
  docs/source/user-guide/tabular/tutorials/plot_static_predictions.py
  docs/source/user-guide/vision/tutorials/plot_classification_tutorial.py
  docs/source/user-guide/vision/tutorials/plot_detection_tutorial.py
  tests/tabular/test_dummy_model.py
Labels: documentation

#1615 FeatureLabelCorrelation: Fix display bug on numeric column names
  deepchecks/core/check_utils/feature_label_correlation_utils.py
Labels: bugfix

#1616 Tabular: Replace dataset type with dataset kind
  deepchecks/tabular/base_checks.py
  deepchecks/tabular/checks/data_integrity/columns_info.py
  deepchecks/tabular/checks/data_integrity/conflicting_labels.py
  deepchecks/tabular/checks/data_integrity/data_duplicates.py
  deepchecks/tabular/checks/data_integrity/feature_label_correlation.py
  deepchecks/tabular/checks/data_integrity/is_single_value.py
  deepchecks/tabular/checks/data_integrity/mixed_data_types.py
  deepchecks/tabular/checks/data_integrity/mixed_nulls.py
  deepchecks/tabular/checks/data_integrity/outlier_sample_detection.py
  deepchecks/tabular/checks/data_integrity/special_chars.py
  deepchecks/tabular/checks/data_integrity/string_length_out_of_bounds.py
  deepchecks/tabular/checks/data_integrity/string_mismatch.py
  deepchecks/tabular/checks/model_evaluation/calibration_score.py
  deepchecks/tabular/checks/model_evaluation/confusion_matrix_report.py
  deepchecks/tabular/checks/model_evaluation/model_inference_time.py
  deepchecks/tabular/checks/model_evaluation/regression_error_distribution.py
  deepchecks/tabular/checks/model_evaluation/regression_systematic_error.py
  deepchecks/tabular/checks/model_evaluation/roc_report.py
  deepchecks/tabular/checks/model_evaluation/segment_performance.py
  deepchecks/tabular/checks/train_test_validation/identifier_leakage.py
  deepchecks/tabular/suite.py
  tests/base/check_suite_test.py
Labels: refactoring

#1623 Fixed broken links
  deepchecks/tabular/checks/data_integrity/feature_label_correlation.py
  deepchecks/tabular/checks/train_test_validation/feature_label_correlation_change.py
  deepchecks/vision/checks/train_test_validation/feature_label_correlation_change.py
Labels: bugfix

#1610 added logger util
  deepchecks/__init__.py
  deepchecks/core/check_result.py
  deepchecks/core/suite.py
  deepchecks/tabular/context.py
  deepchecks/tabular/dataset.py
  deepchecks/utils/display.py
  deepchecks/utils/distribution/trust_score.py
  deepchecks/utils/features.py
  deepchecks/utils/ipython.py
  deepchecks/utils/logger.py
  deepchecks/utils/metrics.py
  deepchecks/vision/context.py
  deepchecks/vision/vision_data.py
  tests/base/dataset_test.py
  tests/base/feature_importance_utils_test.py
  tests/conftest.py
  tests/tabular/checks/train_test_validation/train_test_feature_drift_test.py
Labels: feature

#1612 Improved categorical feature inference + label column description
  deepchecks/tabular/checks/data_integrity/string_length_out_of_bounds.py
  deepchecks/tabular/checks/model_evaluation/model_error_analysis.py
  deepchecks/tabular/checks/model_evaluation/multi_model_performance_report.py
  deepchecks/tabular/checks/model_evaluation/performance_report.py
  deepchecks/tabular/checks/model_evaluation/simple_model_comparison.py
  deepchecks/tabular/checks/model_evaluation/train_test_prediction_drift.py
  deepchecks/tabular/checks/train_test_validation/train_test_label_drift.py
  deepchecks/tabular/context.py
  deepchecks/tabular/dataset.py
  deepchecks/tabular/utils/task_type.py
  deepchecks/utils/features.py
  deepchecks/utils/metrics.py
  docs/source/user-guide/tabular/dataset_object.rst
  tests/base/dataset_test.py
  tests/tabular/checks/integrity/string_length_out_of_bounds_test.py
  tests/tabular/checks/model_evaluation/simple_model_comparison_test.py
  tests/utils/metrics_test.py
Labels: bugfix

#1636 Fix bug caused by new albumentations version
  docs/source/user-guide/vision/tutorials/plot_custom_task_tutorial.py
Labels: bugfix

#1644 fixing databricks tutorial
  .github/workflows/build.yml
  docs/source/user-guide/integrations/spark_databricks.rst
  makefile
Labels: documentation

#1639 Update Readme
  README.rst
  docs/source/_static/images/general/pipeline_when_to_validate.svg
Labels: documentation

#1641 Docs Welcome Page Update
  docs/source/checks/vision/train_test_validation/plot_image_dataset_drift.py
  docs/source/checks/vision/train_test_validation/plot_similar_image_leakage.py
  docs/source/getting-started/welcome.rst
  docs/source/user-guide/tabular/tutorials/plot_quick_train_test_validation.py
Labels: documentation

#1624 Update city_arrogance test dataset
  tests/conftest.py
  tests/tabular/checks/integrity/columns_info_test.py
  tests/tabular/checks/model_evaluation/segment_performance_test.py
  tests/tabular/checks/model_evaluation/simple_model_comparison_test.py
  tests/tabular/suites/test_suites.py
Labels: tests, refactoring

#1627 [Issue-1501] new suite output design
  deepchecks/core/condition.py
  deepchecks/core/serialization/common.py
  deepchecks/core/serialization/suite_result/html.py
  deepchecks/core/serialization/suite_result/widget.py
  deepchecks/core/suite.py
  tests/base/check_suite_test.py
  tests/base/check_test.py
  tests/base/utils.py
  tests/common.py
  tests/conftest.py
  tests/serialization/test_check_result_serialization.py
  tests/serialization/test_suite_result_serialization.py
  tests/tabular/checks/model_evaluation/performance_report_test.py
  tests/tabular/checks/model_evaluation/simple_model_comparison_test.py
  tests/tabular/test_datasets.py
  tests/utils/drift_test.py
  tests/utils/metrics_test.py
  tests/vision/checks/model_evaluation/class_performance_test.py
  tests/vision/checks/model_evaluation/single_dataset_scalar_performance_test.py
  tests/vision/checks/train_test_validation/image_property_drift_test.py
Labels: feature

#1645 skip timeout/calculation msg in our fi calculations
  deepchecks/core/check_utils/whole_dataset_drift_utils.py
  deepchecks/utils/features.py
  deepchecks/utils/performance/error_model.py
Labels: feature

#1638 [Issue-1574] new display item type - `DisplayMap`
  deepchecks/core/check_result.py
  deepchecks/core/serialization/abc.py
  deepchecks/core/serialization/check_result/html.py
  deepchecks/core/serialization/check_result/ipython.py
  deepchecks/core/serialization/check_result/json.py
  deepchecks/core/serialization/check_result/wandb.py
  deepchecks/core/serialization/check_result/widget.py
  deepchecks/core/serialization/common.py
  tests/common.py
  tests/serialization/test_check_result_serialization.py
Labels: feature

#1606 1164 feat tabular new check correlation between features
  deepchecks/tabular/checks/data_integrity/__init__.py
  deepchecks/tabular/checks/data_integrity/feature_feature_correlation.py
  deepchecks/tabular/datasets/classification/adult.py
  deepchecks/utils/correlation_methods.py
  deepchecks/utils/dataframes.py
  deepchecks/utils/distribution/preprocessing.py
  docs/source/checks/tabular/data_integrity/plot_feature_feature_correlation.py
  tests/conftest.py
  tests/tabular/checks/integrity/feature_feature_correlation_test.py
  tests/utils/correlation_methods_test.py
  tests/utils/dataframes_test.py
  tests/utils/preprocessing_test.py
Labels: feature

#1651 Fixed typo
  deepchecks/utils/distribution/drift.py
Labels: bugfix

#1655 🐞 [DOCS] Fix link in Getting Started
  docs/source/getting-started/welcome.rst
Labels: documentation, bug

#1611 [suggestion] new suite/check result display api
  deepchecks/core/check_json.py
  deepchecks/core/check_result.py
  deepchecks/core/display.py
  deepchecks/core/resources/suite_output.html
  deepchecks/core/serialization/abc.py
  deepchecks/core/serialization/check_failure/html.py
  deepchecks/core/serialization/check_failure/ipython.py
  deepchecks/core/serialization/check_failure/json.py
  deepchecks/core/serialization/check_failure/wandb.py
  deepchecks/core/serialization/check_failure/widget.py
  deepchecks/core/serialization/check_result/html.py
  deepchecks/core/serialization/check_result/ipython.py
  deepchecks/core/serialization/check_result/json.py
  deepchecks/core/serialization/check_result/wandb.py
  deepchecks/core/serialization/check_result/widget.py
  deepchecks/core/serialization/common.py
  deepchecks/core/serialization/dataframe/html.py
  deepchecks/core/serialization/dataframe/widget.py
  deepchecks/core/serialization/suite_result/html.py
  deepchecks/core/serialization/suite_result/ipython.py
  deepchecks/core/serialization/suite_result/json.py
  deepchecks/core/serialization/suite_result/wandb.py
  deepchecks/core/serialization/suite_result/widget.py
  deepchecks/core/suite.py
  deepchecks/utils/html.py
  deepchecks/utils/ipython.py
  deepchecks/vision/utils/image_functions.py
  requirements/dev-requirements.txt
  spelling-allowlist.txt
  tests/base/display_test.py
  tests/serialization/test_check_result_serialization.py
  tests/utils/test_ipython.py
Labels: suggestion, feature

#1659 Kaggle display fix
  deepchecks/core/display.py
  deepchecks/core/serialization/suite_result/widget.py
  deepchecks/utils/ipython.py
Labels: bugfix

#1653 Static pred vision to use dicts
  deepchecks/vision/base_checks.py
  deepchecks/vision/batch_wrapper.py
  deepchecks/vision/context.py
  deepchecks/vision/detection_data.py
  deepchecks/vision/suite.py
  tests/vision/base/test_static_predictions.py
  tests/vision/base/test_vision_data.py
  tests/vision/vision_conftest.py
Labels: bugfix

#1658 [Issue-1545] progress bar text
  deepchecks/utils/ipython.py
Labels: feature

#1665 1586 add condition to image dataset drift
  deepchecks/vision/checks/train_test_validation/image_dataset_drift.py
  docs/source/checks/vision/train_test_validation/plot_image_dataset_drift.py
  tests/vision/checks/train_test_validation/image_dataset_drift_test.py
Labels: feature, vision

#1664 Adding benchmarks to CI
  .github/scripts/benchmark-history.sh
  .github/scripts/benchmark.sh
  .github/workflows/benchmark-history.yml
  .github/workflows/benchmark.yml
Labels: ci

#1633 Add new custom check templates
  docs/source/user-guide/tabular/custom_check_templates.rst
  docs/source/user-guide/tabular/tutorials/plot_add_a_custom_check.py
  docs/source/user-guide/vision/custom_check_templates.rst
  docs/source/user-guide/vision/tutorials/plot_custom_checks.py
Labels: documentation

#1667 [Issue-1561] `features_importance` parameter deprecation
  deepchecks/tabular/checks/data_integrity/columns_info.py
  deepchecks/tabular/checks/data_integrity/mixed_data_types.py
  deepchecks/tabular/checks/data_integrity/mixed_nulls.py
  deepchecks/tabular/checks/data_integrity/special_chars.py
  deepchecks/tabular/checks/data_integrity/string_length_out_of_bounds.py
  deepchecks/tabular/checks/data_integrity/string_mismatch.py
  deepchecks/tabular/checks/model_evaluation/segment_performance.py
  deepchecks/tabular/checks/model_evaluation/unused_features.py
  deepchecks/tabular/checks/train_test_validation/dominant_frequency_change.py
  deepchecks/tabular/checks/train_test_validation/string_mismatch_comparison.py
  deepchecks/tabular/checks/train_test_validation/train_test_feature_drift.py
  deepchecks/tabular/context.py
  deepchecks/tabular/suite.py
  deepchecks/utils/decorators.py
  tests/base/check_test.py
  tests/vision/base/test_static_predictions.py
Labels: refactoring

#1670 1585 rename identifier leakage
  deepchecks/checks.py
  deepchecks/tabular/checks/__init__.py
  deepchecks/tabular/checks/data_integrity/identifier_label_correlation.py
  deepchecks/tabular/checks/methodology/__init__.py
  deepchecks/tabular/checks/train_test_validation/__init__.py
  deepchecks/tabular/checks/train_test_validation/identifier_leakage.py
  deepchecks/tabular/deprecation_warnings.py
  deepchecks/tabular/suites/default_suites.py
  docs/source/checks/tabular/data_integrity/plot_identifier_label_correlation.py
  docs/source/checks/tabular/train_test_validation/plot_identifier_leakage.py
  docs/source/user-guide/general/customizations/plot_configure_check_conditions.py
  tests/tabular/checks/integrity/identifier_label_correlation_test.py
Labels: refactoring

#1671 Weak segments performance
  deepchecks/utils/performance/partition.py
  tests/utils/partition_tests.py
Labels: feature

#1673 Update docs index.rst
  docs/source/user-guide/index.rst
Labels: bug

#1682 1577 doc update how to use package in ide
  .gitignore
  docs/requirements.txt
  docs/source/checks/vision/data_integrity/plot_image_property_outliers.py
  docs/source/checks/vision/data_integrity/plot_label_property_outliers.py
  docs/source/checks/vision/model_evaluation/plot_class_performance.py
  docs/source/checks/vision/model_evaluation/plot_confusion_matrix.py
  docs/source/checks/vision/model_evaluation/plot_image_segment_performance.py
  docs/source/checks/vision/model_evaluation/plot_mean_average_precision_report.py
  docs/source/checks/vision/model_evaluation/plot_mean_average_recall_report.py
  docs/source/checks/vision/model_evaluation/plot_model_error_analysis.py
  docs/source/checks/vision/model_evaluation/plot_robustness_report.py
  docs/source/checks/vision/model_evaluation/plot_simple_model_comparison.py
  docs/source/checks/vision/model_evaluation/plot_single_dataset_scalar_performance.py
  docs/source/checks/vision/model_evaluation/plot_train_test_prediction_drift.py
  docs/source/checks/vision/train_test_validation/plot_feature_label_correlation_change.py
  docs/source/checks/vision/train_test_validation/plot_heatmap_comparison.py
  docs/source/checks/vision/train_test_validation/plot_image_dataset_drift.py
  docs/source/checks/vision/train_test_validation/plot_image_property_drift.py
  docs/source/checks/vision/train_test_validation/plot_new_labels.py
  docs/source/checks/vision/train_test_validation/plot_similar_image_leakage.py
  docs/source/checks/vision/train_test_validation/plot_train_test_label_drift.py
  makefile
Labels: documentation

#1676 Fix nullable int bug
  deepchecks/core/check_utils/whole_dataset_drift_utils.py
  deepchecks/tabular/checks/train_test_validation/train_test_samples_mix.py
  deepchecks/utils/dataframes.py
  deepchecks/utils/gower_distance.py
  requirements/rtd-requirements.txt
  spelling-allowlist.txt
  tests/conftest.py
  tests/tabular/checks/integrity/columns_info_test.py
  tests/tabular/suites/test_suites.py
Labels: bug

#1684 doc update check result
  docs/source/checks/vision/model_evaluation/plot_class_performance.py
  docs/source/checks/vision/model_evaluation/plot_confusion_matrix.py
  docs/source/checks/vision/model_evaluation/plot_image_segment_performance.py
  docs/source/checks/vision/model_evaluation/plot_model_error_analysis.py
  docs/source/checks/vision/model_evaluation/plot_train_test_prediction_drift.py
  docs/source/checks/vision/train_test_validation/plot_feature_label_correlation_change.py
  docs/source/checks/vision/train_test_validation/plot_heatmap_comparison.py
  docs/source/checks/vision/train_test_validation/plot_image_dataset_drift.py
  docs/source/checks/vision/train_test_validation/plot_similar_image_leakage.py
  docs/source/checks/vision/train_test_validation/plot_train_test_label_drift.py
Labels: documentation

#1679 [Issue-1542] MixedNull display table order
  deepchecks/tabular/checks/data_integrity/mixed_nulls.py
  tests/tabular/checks/integrity/feature_feature_correlation_test.py
  tests/tabular/checks/integrity/mixed_data_types_test.py
  tests/tabular/checks/integrity/mixed_nulls_test.py
  tests/tabular/checks/model_evaluation/calibration_score_test.py
  tests/tabular/checks/model_evaluation/segment_performance_test.py
  tests/tabular/checks/model_evaluation/simple_model_comparison_test.py
  tests/utils/partition_tests.py
  tests/vision/checks/data_integrity/image_property_outliers_test.py
  tests/vision/checks/data_integrity/label_property_outliers_test.py
Labels: bug, bugfix

#1685 Deprecating the DominantFrequencyChange check
  deepchecks/tabular/checks/train_test_validation/dominant_frequency_change.py
  deepchecks/tabular/deprecation_warnings.py
  tests/base/test_tabular_deprecation_warnings.py
Labels: feature

#1677 [issue-1674] mixed nulls bug fix
  deepchecks/tabular/checks/data_integrity/mixed_nulls.py
  deepchecks/utils/strings.py
  spelling-allowlist.txt
  tests/base/test_tabular_deprecation_warnings.py
  tests/tabular/checks/integrity/mixed_nulls_test.py
Labels: bug, bugfix

#1680 [Issue-1560] fix effect of display control parameters on `CheckResult.value`
  deepchecks/tabular/checks/data_integrity/columns_info.py
  deepchecks/tabular/checks/data_integrity/special_chars.py
  deepchecks/tabular/checks/model_evaluation/performance_report.py
  deepchecks/tabular/checks/train_test_validation/category_mismatch_train_test.py
  deepchecks/vision/checks/model_evaluation/class_performance.py
  deepchecks/vision/checks/model_evaluation/image_segment_performance.py
  deepchecks/vision/checks/model_evaluation/simple_model_comparison.py
  deepchecks/vision/checks/train_test_validation/similar_image_leakage.py
  tests/base/to_json_test.py
  tests/common.py
  tests/tabular/checks/integrity/columns_info_test.py
  tests/vision/base/test_static_predictions.py
  tests/vision/checks/model_evaluation/class_performance_test.py
  tests/vision/checks/model_evaluation/cv_simple_model_comparison_test.py
Labels: refactoring, bug, bugfix

#1696 display map widget representation fix
  deepchecks/core/serialization/check_result/widget.py
  tests/serialization/test_check_result_serialization.py
Labels: bug, bugfix

#1694 [issue-1514] conflicting labels check fix
  deepchecks/tabular/checks/data_integrity/conflicting_labels.py
  tests/tabular/checks/integrity/conflicting_labels_test.py
Labels: feature

#1669 Shared docstrings
  deepchecks/tabular/_shared_docs.py
  deepchecks/tabular/base_checks.py
  deepchecks/tabular/context.py
  deepchecks/tabular/suite.py
  deepchecks/tabular/suites/default_suites.py
  deepchecks/utils/decorators.py
  deepchecks/vision/_shared_docs.py
  deepchecks/vision/base_checks.py
  deepchecks/vision/context.py
  deepchecks/vision/suite.py
  spelling-allowlist.txt
Labels: refactoring

#1681 Vision benchmark
  .github/scripts/benchmark-history.sh
  .github/scripts/benchmark.sh
  .github/workflows/benchmark-history.yml
  .github/workflows/benchmark.yml
  .gitignore
  benchmarks/tabular_bench.py
  benchmarks/vision_bench.py
  deepchecks/vision/datasets/detection/coco.py
Labels: feature
