Repository deepchecks/deepchecks, pull requests merged in 2022-07, with the labels that each got.

#1698 New vis metrics
  deepchecks/vision/checks/model_evaluation/class_performance.py
  deepchecks/vision/checks/model_evaluation/mean_average_precision_report.py
  deepchecks/vision/checks/model_evaluation/mean_average_recall_report.py
  deepchecks/vision/checks/model_evaluation/single_dataset_scalar_performance.py
  deepchecks/vision/metrics_utils/confusion_matrix_counts_metrics.py
  deepchecks/vision/metrics_utils/detection_precision_recall.py
  deepchecks/vision/metrics_utils/detection_tp_fp_fn_calc.py
  deepchecks/vision/metrics_utils/metric_mixin.py
  deepchecks/vision/metrics_utils/metrics.py
  deepchecks/vision/metrics_utils/object_detection_precision_recall.py
  tests/vision/checks/model_evaluation/class_performance_test.py
  tests/vision/utils_tests/metrics_test.py
Labels: feature

#1704 custom vision scorer
  deepchecks/vision/metrics_utils/custom_scorer.py
  tests/vision/checks/model_evaluation/single_dataset_scalar_performance_test.py
Labels: feature

#1678 Nb/feat/weak segments performance
  deepchecks/checks.py
  deepchecks/core/check_json.py
  deepchecks/core/check_result.py
  deepchecks/core/check_utils/whole_dataset_drift_utils.py
  deepchecks/datasets/regression/avocado.py
  deepchecks/tabular/checks/__init__.py
  deepchecks/tabular/checks/model_evaluation/__init__.py
  deepchecks/tabular/checks/model_evaluation/weak_segments_performance.py
  deepchecks/tabular/context.py
  deepchecks/tabular/datasets/classification/lending_club.py
  deepchecks/tabular/suites/default_suites.py
  deepchecks/utils/dataframes.py
  deepchecks/utils/metrics.py
  deepchecks/utils/performance/error_model.py
  deepchecks/utils/performance/partition.py
  deepchecks/utils/single_sample_metrics.py
  docs/source/checks/tabular/model_evaluation/plot_weak_segments_performance.py
  docs/source/user-guide/tabular/tutorials/plot_quickstart_in_5_minutes.py
  tests/conftest.py
  tests/tabular/checks/model_evaluation/weak_segments_performance_test.py
Labels: feature, ds

#1720 Class performance / performance report condition details upgrade
  deepchecks/core/check_utils/class_performance_utils.py
  deepchecks/tabular/checks/model_evaluation/performance_report.py
  deepchecks/tabular/suites/default_suites.py
  deepchecks/vision/checks/model_evaluation/class_performance.py
  docs/source/checks/tabular/model_evaluation/plot_performance_report.py
  docs/source/user-guide/general/customizations/plot_create_a_custom_suite.py
  tests/tabular/checks/model_evaluation/performance_report_test.py
  tests/vision/checks/model_evaluation/class_performance_test.py
Labels: bug

#1718 Ignore NaNs in FeatureFeatureCorrelation
  deepchecks/tabular/checks/data_integrity/feature_feature_correlation.py
  deepchecks/utils/correlation_methods.py
  tests/tabular/checks/integrity/feature_feature_correlation_test.py
Labels: bug

#1727 Update label-new-issue.yml
  .github/workflows/label-new-issue.yml
Labels: bug

#1732 deprecation warnings
  deepchecks/tabular/checks/model_evaluation/model_error_analysis.py
  deepchecks/tabular/checks/model_evaluation/segment_performance.py
  deepchecks/tabular/deprecation_warnings.py
  tests/base/test_tabular_deprecation_warnings.py
Labels: feature

#1726 Quick start model evaluation + new dataset
  deepchecks/tabular/checks/model_evaluation/model_error_analysis.py
  deepchecks/tabular/checks/model_evaluation/train_test_prediction_drift.py
  deepchecks/tabular/checks/model_evaluation/weak_segments_performance.py
  deepchecks/tabular/context.py
  deepchecks/tabular/datasets/regression/__init__.py
  deepchecks/tabular/datasets/regression/wine_quality.py
  deepchecks/utils/single_sample_metrics.py
  docs/source/checks/tabular/model_evaluation/plot_weak_segments_performance.py
  docs/source/getting-started/welcome.rst
  docs/source/user-guide/tabular/tutorials/plot_quick_data_integrity.py
  docs/source/user-guide/tabular/tutorials/plot_quick_model_evaluation.py
  docs/source/user-guide/tabular/tutorials/plot_quick_train_test_validation.py
  docs/source/user-guide/tabular/tutorials/plot_quickstart_in_5_minutes.py
  tests/tabular/test_datasets.py
Labels: documentation, ds

#1733 fixing double output in docs
  deepchecks/core/display.py
Labels: bug

#1741 handle single value columns gower dist
  .github/workflows/build.yml
  deepchecks/utils/gower_distance.py
  tests/utils/test_gower_distance.py
Labels: bug

#1744 Fixing a deprecated call in the create a custom suite tutorial
  docs/source/user-guide/general/customizations/plot_create_a_custom_suite.py
Labels: documentation

#1746 Separate gower distance function
  deepchecks/tabular/checks/data_integrity/outlier_sample_detection.py
  deepchecks/utils/gower_distance.py
  tests/utils/test_gower_distance.py
Labels: feature

#1740 [issue-1660] dataframe index display fix
  deepchecks/core/serialization/check_result/ipython.py
  tests/base/test_tabular_deprecation_warnings.py
  tests/tabular/checks/model_evaluation/weak_segments_performance_test.py
Labels: bug

#1735 [Issue 1654] added "connected" parameter to the "save_as_html" method
  .licenserc_fix.yaml
  deepchecks/core/check_result.py
  deepchecks/core/display.py
  deepchecks/core/resources/__init__.py
  deepchecks/core/resources/jupyterlab-plotly.js
  deepchecks/core/resources/suite-template-full.html
  deepchecks/core/resources/suite-template.html
  deepchecks/core/resources/widgets-embed-amd.js
  deepchecks/core/resources/widgets-embed.js
  deepchecks/core/serialization/check_result/html.py
  deepchecks/core/serialization/common.py
  deepchecks/core/serialization/suite_result/html.py
  deepchecks/core/suite.py
  deepchecks/utils/strings.py
Labels: feature

#1745 Scorers string
  deepchecks/tabular/checks/model_evaluation/performance_report.py
  deepchecks/tabular/checks/model_evaluation/weak_segments_performance.py
  deepchecks/tabular/context.py
  deepchecks/tabular/metric_utils/__init__.py
  deepchecks/tabular/metric_utils/metrics.py
  deepchecks/utils/features.py
  deepchecks/utils/metrics.py
  deepchecks/vision/metrics_utils/__init__.py
  deepchecks/vision/metrics_utils/metrics.py
  tests/tabular/checks/model_evaluation/performance_report_test.py
  tests/tabular/checks/model_evaluation/simple_model_comparison_test.py
  tests/utils/metrics_test.py
  tests/vision/checks/model_evaluation/class_performance_test.py
Labels: feature

#1751 Nb/feat/new metrics
  deepchecks/tabular/_shared_docs.py
  deepchecks/tabular/base_checks.py
  deepchecks/tabular/checks/model_evaluation/multi_model_performance_report.py
  deepchecks/tabular/checks/model_evaluation/performance_report.py
  deepchecks/tabular/checks/model_evaluation/simple_model_comparison.py
  deepchecks/tabular/checks/model_evaluation/weak_segments_performance.py
  deepchecks/tabular/context.py
  deepchecks/tabular/metric_utils/__init__.py
  deepchecks/tabular/metric_utils/additional_metrics.py
  deepchecks/tabular/metric_utils/scorers.py
  deepchecks/tabular/suite.py
  deepchecks/utils/features.py
  deepchecks/utils/gower_distance.py
  tests/tabular/checks/model_evaluation/performance_report_test.py
  tests/tabular/checks/model_evaluation/simple_model_comparison_test.py
  tests/utils/metrics_test.py
Labels: feature

#1763 Fixed docs links in data classes
  docs/source/user-guide/vision/data-classes/ClassificationData.rst
  docs/source/user-guide/vision/data-classes/DetectionData.rst
  docs/source/user-guide/vision/data-classes/index.rst
Labels: documentation

#1765 Fixed README links
  README.rst
  deepchecks/vision/README.rst
Labels: documentation, bug

#1773 Nb/feat/drift scores
  deepchecks/tabular/checks/model_evaluation/train_test_prediction_drift.py
  deepchecks/tabular/checks/train_test_validation/train_test_feature_drift.py
  deepchecks/tabular/checks/train_test_validation/train_test_label_drift.py
  deepchecks/vision/checks/model_evaluation/train_test_prediction_drift.py
  deepchecks/vision/checks/train_test_validation/train_test_label_drift.py
  docs/source/checks/tabular/train_test_validation/plot_train_test_feature_drift.py
  tests/tabular/checks/model_evaluation/train_test_prediction_drift_test.py
  tests/tabular/checks/train_test_validation/train_test_feature_drift_test.py
  tests/tabular/checks/train_test_validation/train_test_label_drift_test.py
  tests/vision/checks/model_evaluation/train_test_prediction_drift_test.py
  tests/vision/checks/train_test_validation/train_test_label_drift_test.py
Labels: documentation, feature, ds

#1779 Adding the run function of the suite to the suite api docs
  docs/source/_templates/autosummary/suite.rst
  docs/source/api/deepchecks.tabular.suites.rst
  docs/source/api/deepchecks.vision.suites.rst
  docs/source/conf.py
Labels: feature

#1758 [Monitoring][issue-52] Added PercentOfNull check / added ReduceMixin to checks
  deepchecks/tabular/checks/data_integrity/__init__.py
  deepchecks/tabular/checks/data_integrity/percent_of_nulls.py
  deepchecks/tabular/checks/train_test_validation/category_mismatch_train_test.py
  deepchecks/tabular/checks/train_test_validation/new_label_train_test.py
  deepchecks/vision/checks/train_test_validation/new_labels.py
  docs/source/checks/tabular/data_integrity/plot_percent_of_nulls.py
  tests/base/check_suite_test.py
  tests/base/test_tabular_deprecation_warnings.py
  tests/examples_validation.py
  tests/tabular/checks/integrity/percent_of_nulls_test.py
  tests/tabular/checks/model_evaluation/simple_model_comparison_test.py
  tests/tabular/checks/model_evaluation/train_test_performance_test.py
  tests/utils/metrics_test.py
  tests/utils/test_gower_distance.py
Labels: feature

#1784 Update README.rst
  README.rst
Labels: documentation, bug

#1778 1637 SingleDatasetPerformance update to support multiple scorers
  deepchecks/vision/checks/__init__.py
  deepchecks/vision/checks/data_integrity/abstract_property_outliers.py
  deepchecks/vision/checks/model_evaluation/__init__.py
  deepchecks/vision/checks/model_evaluation/class_performance.py
  deepchecks/vision/checks/model_evaluation/image_segment_performance.py
  deepchecks/vision/checks/model_evaluation/robustness_report.py
  deepchecks/vision/checks/model_evaluation/simple_model_comparison.py
  deepchecks/vision/checks/model_evaluation/single_dataset_performance.py
  deepchecks/vision/checks/model_evaluation/single_dataset_scalar_performance.py
  deepchecks/vision/metrics_utils/__init__.py
  deepchecks/vision/metrics_utils/custom_scorer.py
  deepchecks/vision/metrics_utils/metrics.py
  docs/source/checks/vision/model_evaluation/plot_single_dataset_performance.py
  docs/source/checks/vision/model_evaluation/plot_single_dataset_scalar_performance.py
  tests/vision/checks/model_evaluation/single_dataset_performance_test.py
  tests/vision/checks/model_evaluation/single_dataset_scalar_performance_test.py
Labels: feature, vision

#1788 tabular single dataset performance
  deepchecks/checks.py
  deepchecks/core/checks.py
  deepchecks/tabular/checks/__init__.py
  deepchecks/tabular/checks/model_evaluation/__init__.py
  deepchecks/tabular/checks/model_evaluation/single_dataset_performance.py
  deepchecks/tabular/checks/model_evaluation/train_test_performance.py
  deepchecks/tabular/checks/performance/__init__.py
  deepchecks/tabular/metric_utils/scorers.py
  deepchecks/utils/metrics.py
  docs/source/checks/tabular/model_evaluation/plot_single_dataset_performance.py
  tests/tabular/checks/model_evaluation/single_dataset_performance_test.py
  tests/tabular/checks/model_evaluation/train_test_performance_test.py
  tests/vision/checks/model_evaluation/class_performance_test.py
Labels: feature

#1787 [Issue-1646] renamed 'FeatureLabelCorrelationChange' check
  deepchecks/vision/checks/__init__.py
  deepchecks/vision/checks/methodology/__init__.py
  deepchecks/vision/checks/train_test_validation/__init__.py
  deepchecks/vision/checks/train_test_validation/property_label_correlation_change.py
  deepchecks/vision/suites/default_suites.py
  docs/source/checks/vision/train_test_validation/plot_property_label_correlation_change.py
  docs/source/user-guide/vision/tutorials/plot_custom_task_tutorial.py
  docs/source/user-guide/vision/tutorials/plot_simple_classification_tutorial.py
  tests/tabular/checks/train_test_validation/train_test_feature_drift_test.py
  tests/vision/checks/train_test_validation/property_label_correlation_test.py
Labels: refactoring

#1785 Adapting tabular SimpleModelComparison API
  deepchecks/tabular/checks/model_evaluation/simple_model_comparison.py
  deepchecks/tabular/deprecation_warnings.py
  deepchecks/tabular/suites/README.rst
  deepchecks/utils/simple_models.py
  docs/source/checks/tabular/model_evaluation/plot_simple_model_comparison.py
  docs/source/user-guide/general/customizations/plot_create_a_custom_suite.py
  tests/base/test_tabular_deprecation_warnings.py
  tests/tabular/checks/model_evaluation/simple_model_comparison_test.py
  tests/tabular/test_dummy_model.py
Labels: documentation, feature

#1793 Adding methods and attributes to API ref classes
  docs/source/api/deepchecks.core.rst
  docs/source/api/deepchecks.tabular.rst
  docs/source/api/deepchecks.vision.rst
Labels: documentation

#1792 Nb/feat/update custom check guide
  docs/source/checks/tabular/custom/README.txt
  docs/source/checks/tabular/custom/plot_create_a_custom_check.py
  docs/source/checks/vision/custom/README.txt
  docs/source/checks/vision/custom/plot_create_a_custom_check.py
  docs/source/checks_gallery/tabular.rst
  docs/source/checks_gallery/vision.rst
  docs/source/user-guide/general/customizations/plot_create_a_custom_check.py
  docs/source/user-guide/tabular/custom_check_templates.rst
  docs/source/user-guide/tabular/tutorials/plot_add_a_custom_check.py
  docs/source/user-guide/tabular/tutorials/plot_quick_model_evaluation.py
  docs/source/user-guide/vision/custom_check_templates.rst
  docs/source/user-guide/vision/tutorials/plot_custom_checks.py
Labels: documentation

#1791 SingleDatasetPerformance Minor adjustment to the scorers signature and display
  deepchecks/vision/checks/model_evaluation/single_dataset_performance.py
Labels: bug, vision

#1797 fix_static_model_bug
  deepchecks/tabular/context.py
  tests/tabular/test_dummy_model.py
Labels: bug

#1805 updated unused features plot example
  docs/source/checks/tabular/model_evaluation/plot_unused_features.py
Labels: documentation, feature

#1803 updated classification_dataset_from_directory
  deepchecks/vision/README.rst
  deepchecks/vision/__init__.py
  deepchecks/vision/metrics_utils/custom_scorer.py
  deepchecks/vision/simple_classification_data.py
  docs/source/getting-started/welcome.rst
  docs/source/user-guide/vision/tutorials/plot_simple_classification_tutorial.py
  tests/vision/datasets/test_simple.py
Labels: documentation, feature, vision

#1794 small fixes to drift and gower distance
  deepchecks/utils/distribution/drift.py
Labels: bug

#1811 Add indices to conflicting labels display
  deepchecks/tabular/checks/data_integrity/conflicting_labels.py
  spelling-allowlist.txt
  tests/tabular/checks/integrity/conflicting_labels_test.py
Labels: feature

#1812 [DOCS] Guide for Viewing Results (show) and for Exporting them (json & html)
  deepchecks/tabular/dataset.py
  docs/source/checks/vision/train_test_validation/plot_new_labels.py
  docs/source/user-guide/general/customizations/plot_create_a_custom_check.py
  docs/source/user-guide/general/drift_guide.rst
  docs/source/user-guide/general/export_save_results.rst
  docs/source/user-guide/general/showing_results.rst
  docs/source/user-guide/index.rst
  docs/source/user-guide/integrations/hugging_face.rst
  docs/source/user-guide/tabular/custom_check_templates.rst
  docs/source/user-guide/vision/custom_check_templates.rst
  docs/source/user-guide/vision/data-classes/DetectionData.rst
Labels: documentation

#1806 Removing Similar image leakage from the suites because of performance issues
  .github/workflows/build.yml
  benchmarks/vision_bench.py
  deepchecks/vision/suites/default_suites.py
  docs/source/checks/tabular/model_evaluation/plot_weak_segments_performance.py
  docs/source/checks/tabular/train_test_validation/plot_train_test_feature_drift.py
  spelling-allowlist.txt
Labels: ci

#1826 fixed license dependency
  .github/workflows/build.yml
Labels: ci

#1818 bugfix - label in evaluation suite example inferred incorrectly
  docs/source/user-guide/tabular/tutorials/plot_quick_model_evaluation.py
Labels: bug

#1815 Added text for drift differentiation
  deepchecks/tabular/checks/model_evaluation/train_test_prediction_drift.py
  deepchecks/tabular/checks/train_test_validation/train_test_feature_drift.py
  deepchecks/tabular/checks/train_test_validation/train_test_label_drift.py
  deepchecks/vision/checks/model_evaluation/train_test_prediction_drift.py
  docs/source/user-guide/general/drift_guide.rst
Labels: documentation

#1822 FI new function for users
  deepchecks/tabular/feature_importance.py
  deepchecks/utils/features.py
  deepchecks/utils/performance/error_model.py
  docs/source/user-guide/tabular/feature_importance.rst
  docs/source/user-guide/tabular/tutorials/plot_static_predictions.py
  tests/base/feature_importance_utils_test.py
  tests/tabular/test_feature_importance_user_utils.py
Labels: documentation, feature

#1834 run checks without labels if they are not needed
  deepchecks/tabular/checks/data_integrity/conflicting_labels.py
  deepchecks/tabular/checks/data_integrity/feature_label_correlation.py
  deepchecks/tabular/checks/data_integrity/identifier_label_correlation.py
  deepchecks/tabular/checks/model_evaluation/model_error_analysis.py
  deepchecks/tabular/checks/train_test_validation/feature_label_correlation_change.py
  deepchecks/tabular/checks/train_test_validation/new_label_train_test.py
  deepchecks/tabular/checks/train_test_validation/train_test_samples_mix.py
  deepchecks/tabular/context.py
  deepchecks/tabular/dataset.py
  deepchecks/tabular/metric_utils/scorers.py
  deepchecks/utils/features.py
  tests/base/dataset_test.py
  tests/tabular/checks/train_test_validation/train_test_samples_mix_test.py
Labels: bug

#1809 Add probability drift on proba
  deepchecks/tabular/checks/model_evaluation/train_test_prediction_drift.py
  docs/source/checks/tabular/model_evaluation/plot_train_test_prediction_drift.py
  tests/conftest.py
  tests/tabular/checks/model_evaluation/train_test_prediction_drift_test.py
Labels: feature

#1837 Nb/doc/small fixes
  deepchecks/tabular/datasets/classification/adult.py
  deepchecks/tabular/datasets/classification/breast_cancer.py
  deepchecks/tabular/datasets/classification/iris.py
  deepchecks/tabular/datasets/classification/lending_club.py
  deepchecks/tabular/datasets/classification/phishing.py
  deepchecks/tabular/datasets/regression/avocado.py
  deepchecks/tabular/datasets/regression/wine_quality.py
  docs/source/checks/vision/train_test_validation/plot_property_label_correlation_change.py
Labels: documentation

#1844 Fixing dependencies
  .github/workflows/build.yml
Labels: feature

#1843 Added flag for users to not ignore nulls in categorical columns
  deepchecks/tabular/checks/model_evaluation/train_test_prediction_drift.py
  deepchecks/tabular/checks/train_test_validation/train_test_feature_drift.py
  deepchecks/tabular/checks/train_test_validation/train_test_label_drift.py
  deepchecks/utils/distribution/drift.py
  deepchecks/vision/checks/model_evaluation/train_test_prediction_drift.py
  deepchecks/vision/checks/train_test_validation/train_test_label_drift.py
  tests/conftest.py
  tests/tabular/checks/train_test_validation/train_test_feature_drift_test.py
Labels: feature

#1840 Shir was right, I was wrong
  deepchecks/tabular/checks/model_evaluation/train_test_prediction_drift.py
  docs/source/user-guide/tabular/tutorials/plot_quick_model_evaluation.py
Labels: bug

#1835 Unify supported models and static predictions
  docs/source/user-guide/tabular/supported_models.rst
  docs/source/user-guide/tabular/tutorials/plot_static_predictions.py
  examples/examples_supported_models.py
Labels: documentation

#1853 Update plot_create_a_custom_suite.py
  docs/source/user-guide/general/customizations/plot_create_a_custom_suite.py
Labels: documentation, bug
