Repository deepchecks/deepchecks, pull requests merged in 2022-10, with the labels that each got.

#2082 Fix typo in makefile
  makefile
Labels: documentation, bug

#2085 [Doc] fix tabular class imbalance
  docs/source/checks/tabular/data_integrity/plot_class_imbalance.py
Labels: documentation, bug

#2079 1984 detection scorers averaging
  deepchecks/vision/metrics_utils/detection_precision_recall.py
  deepchecks/vision/metrics_utils/scorers.py
  docs/source/user-guide/general/metrics_guide.rst
  tests/vision/utils_tests/metrics_test.py
Labels: feature, vision

#2088 [DOCS] Update readme to markdown [skip ci]
  DESCRIPTION.rst
  MANIFEST.in
  README.md
  README.rst
Labels: documentation

#2081 Make deepchecks work with classification tasks when no proba is given
  deepchecks/tabular/checks/model_evaluation/calibration_score.py
  deepchecks/tabular/checks/model_evaluation/roc_report.py
  deepchecks/tabular/checks/model_evaluation/weak_segments_performance.py
  deepchecks/tabular/context.py
  deepchecks/tabular/metric_utils/scorers.py
  deepchecks/tabular/utils/task_inference.py
  deepchecks/utils/single_sample_metrics.py
  deepchecks/vision/datasets/detection/coco.py
  deepchecks/vision/datasets/segmentation/segmentation_coco.py
  docs/source/user-guide/general/metrics_guide.rst
  docs/source/user-guide/tabular/supported_models.rst
  tests/conftest.py
  tests/tabular/checks/model_evaluation/weak_segments_performance_test.py
  tests/tabular/test_dummy_model.py
  tests/utils/metrics_test.py
  tests/vision/checks/model_evaluation/single_dataset_performance_test.py
  tests/vision/utils_tests/metrics_test.py
Labels: feature

#2087 calc_default_image_properties
  deepchecks/vision/utils/image_properties.py
  deepchecks/vision/utils/label_prediction_properties.py
  tests/vision/utils_tests/properties_utils_tests.py
Labels: feature, vision

#2089 Small changes in Class Imbalance texts
  deepchecks/tabular/checks/data_integrity/class_imbalance.py
  deepchecks/tabular/context.py
  docs/source/checks/tabular/data_integrity/plot_class_imbalance.py
  tests/tabular/checks/integrity/class_imbalance_test.py
Labels: documentation, tabular

#2091 2027 single dataset check select dataset
  deepchecks/tabular/suite.py
  deepchecks/vision/suite.py
  tests/tabular/suites/test_suites.py
  tests/vision/base/test_suite.py
Labels: feature

#2094 Remove warning
  deepchecks/tabular/checks/data_integrity/mixed_nulls.py
  deepchecks/tabular/checks/train_test_validation/train_test_samples_mix.py
  deepchecks/vision/checks/model_evaluation/robustness_report.py
Labels: bug

#2098 [DOCS] Update .all-contributorsrc to readme.md
  .all-contributorsrc
Labels: documentation, bug

#2096 iou range parameter in mean average precision
  deepchecks/vision/metrics_utils/detection_precision_recall.py
  tests/vision/utils_tests/metrics_test.py
Labels: feature, vision

#2100 Nb/feat/airbnb dataset
  .github/workflows/build.yml
  deepchecks/tabular/datasets/regression/airbnb.py
  tests/tabular/test_datasets.py
Labels: feature

#2097 1867 doc for static properties
  deepchecks/vision/utils/__init__.py
  deepchecks/vision/utils/vision_properties.py
  docs/source/user-guide/vision/vision_properties.rst
  examples/vision/static_properties_example.py
  tests/vision/base/test_static_properties.py
Labels: documentation, feature

#2102 adult dataset no split fixed issue with the label
  deepchecks/tabular/datasets/classification/adult.py
Labels: bug, tabular

#2103 Fix `len()` on None in single dataset performance
  deepchecks/tabular/checks/model_evaluation/single_dataset_performance.py
  tests/tabular/checks/model_evaluation/single_dataset_performance_test.py
Labels: bug

#2104 updated warning comment
  deepchecks/tabular/context.py
Labels: feature

#2101 1743 feat pass scorer list to model evaluation suite
  deepchecks/tabular/checks/model_evaluation/multi_model_performance_report.py
  deepchecks/tabular/checks/model_evaluation/simple_model_comparison.py
  deepchecks/tabular/checks/model_evaluation/single_dataset_performance.py
  deepchecks/tabular/checks/model_evaluation/train_test_performance.py
  deepchecks/tabular/deprecation_warnings.py
  deepchecks/vision/checks/model_evaluation/class_performance.py
  deepchecks/vision/checks/model_evaluation/image_segment_performance.py
  deepchecks/vision/checks/model_evaluation/robustness_report.py
  deepchecks/vision/checks/model_evaluation/simple_model_comparison.py
  deepchecks/vision/deprecation_warnings.py
  docs/source/user-guide/general/customizations/plot_create_a_custom_suite.py
  docs/source/user-guide/general/metrics_guide.rst
  tests/base/test_tabular_deprecation_warnings.py
  tests/tabular/checks/model_evaluation/simple_model_comparison_test.py
  tests/vision/base/test_vision_deprecation_warnings.py
  tests/vision/checks/model_evaluation/class_performance_test.py
  tests/vision/checks/model_evaluation/image_segment_performance_test.py
Labels: bug

#2114 Display nlp words
  deepchecks/nlp/checks/train_test_validation/keyword_frequency_drift.py
  tests/nlp/checks/train_test_validation/keyword_frequency_drift_test.py
Labels: bug, nlp

#2113 Plotly relax requirements
  requirements/requirements.txt
Labels: feature

#2111 1852 single dataset static predictions
  deepchecks/tabular/base_checks.py
  deepchecks/tabular/deprecation_warnings.py
  deepchecks/vision/base_checks.py
  deepchecks/vision/deprecation_warnings.py
  docs/source/user-guide/tabular/supported_models.rst
  docs/source/user-guide/vision/using_precomputed_predictions_vision.rst
  tests/base/test_tabular_deprecation_warnings.py
  tests/vision/base/test_static_predictions.py
  tests/vision/base/test_vision_deprecation_warnings.py
Labels: feature

#2112 regression_error_distribution makeover
  deepchecks/tabular/checks/model_evaluation/regression_error_distribution.py
  deepchecks/tabular/checks/model_evaluation/regression_systematic_error.py
  deepchecks/tabular/dataset.py
  deepchecks/tabular/deprecation_warnings.py
  deepchecks/tabular/suites/default_suites.py
  docs/source/checks/tabular/model_evaluation/plot_regression_error_distribution.py
  docs/source/checks/tabular/model_evaluation/plot_regression_systematic_error.py
  tests/base/test_tabular_deprecation_warnings.py
  tests/tabular/checks/model_evaluation/regression_error_distribution_test.py
  tests/tabular/suites/test_suites.py
  tests/tabular/test_dummy_model.py
Labels: feature

#2107 Fix scorer per class bug
  .github/workflows/build.yml
  deepchecks/core/check_utils/multivariate_drift_utils.py
  deepchecks/tabular/_shared_docs.py
  deepchecks/tabular/base_checks.py
  deepchecks/tabular/checks/model_evaluation/multi_model_performance_report.py
  deepchecks/tabular/checks/model_evaluation/simple_model_comparison.py
  deepchecks/tabular/checks/model_evaluation/single_dataset_performance.py
  deepchecks/tabular/checks/model_evaluation/train_test_performance.py
  deepchecks/tabular/checks/model_evaluation/weak_segments_performance.py
  deepchecks/tabular/context.py
  deepchecks/tabular/dataset.py
  deepchecks/tabular/feature_importance.py
  deepchecks/tabular/metric_utils/additional_classification_metrics.py
  deepchecks/tabular/metric_utils/scorers.py
  deepchecks/tabular/utils/feature_importance.py
  deepchecks/tabular/utils/task_inference.py
  deepchecks/utils/performance/error_model.py
  deepchecks/utils/strings.py
  deepchecks/vision/metrics_utils/custom_scorer.py
  deepchecks/vision/metrics_utils/scorers.py
  docs/source/user-guide/general/metrics_guide.rst
  spelling-allowlist.txt
  tests/base/dataset_test.py
  tests/base/feature_importance_utils_test.py
  tests/common.py
  tests/tabular/checks/integrity/class_imbalance_test.py
  tests/tabular/checks/integrity/mixed_data_types_test.py
  tests/tabular/checks/integrity/special_chars_test.py
  tests/tabular/checks/integrity/string_length_out_of_bounds_test.py
  tests/tabular/checks/integrity/string_mismatch_test.py
  tests/tabular/checks/model_evaluation/simple_model_comparison_test.py
  tests/tabular/checks/model_evaluation/single_dataset_performance_test.py
  tests/tabular/checks/model_evaluation/weak_segments_performance_test.py
  tests/tabular/checks/train_test_validation/string_mismatch_comparison_test.py
  tests/tabular/test_feature_importance_user_utils.py
  tests/utils/metrics_test.py
  tests/utils/test_task_inference.py
  tests/vision/checks/train_test_validation/property_label_correlation_change_test.py
Labels: bug

#2118 Small fix to NLP
  deepchecks/nlp/checks/train_test_validation/keyword_frequency_drift.py
  tests/nlp/checks/train_test_validation/keyword_frequency_drift_test.py
  tests/nlp/nlp_conftest.py
Labels: bug, nlp
