Repository deepchecks/deepchecks, pull requests merged in 2022-09, with the labels that each got.

#1969 positive_regression_scorers
  deepchecks/tabular/metric_utils/additional_classification_metrics.py
  deepchecks/tabular/metric_utils/scorers.py
  docs/source/user-guide/general/metrics_guide.rst
  tests/tabular/checks/model_evaluation/single_dataset_performance_test.py
Labels: feature

#1952 [issue-1917][v2] display_in_window fix
  deepchecks/core/display.py
  tests/vision/base/test_static_properties.py
Labels: bug

#1959 add scorers for token classification
  deepchecks/nlp/checks/model_evaluation/single_dataset_performance.py
  deepchecks/nlp/context.py
  deepchecks/nlp/metric_utils/token_classification.py
  deepchecks/nlp/text_data.py
  requirements/nlp-requirements.txt
  tests/nlp/checks/model_evaluation/single_dataset_performance_nlp_test.py
  tests/nlp/nlp_conftest.py
  tests/nlp/test_context.py
  tests/nlp/test_text_data.py
Labels: feature, ds, nlp

#1985 Fixed tqdm version for correct license
  .github/workflows/build.yml
Labels: ci

#1977 Small scorer update
  deepchecks/tabular/metric_utils/scorers.py
Labels: feature

#1987 top_5 aggregation method + bug fix in percent_of_nulls.py
  deepchecks/checks.py
  deepchecks/core/reduce_classes.py
  deepchecks/tabular/_shared_docs.py
  deepchecks/tabular/checks/__init__.py
  deepchecks/tabular/checks/data_integrity/percent_of_nulls.py
  deepchecks/tabular/checks/train_test_validation/category_mismatch_train_test.py
  deepchecks/tabular/checks/train_test_validation/train_test_feature_drift.py
  deepchecks/vision/_shared_docs.py
  deepchecks/vision/checks/model_evaluation/train_test_prediction_drift.py
  deepchecks/vision/checks/train_test_validation/image_property_drift.py
  deepchecks/vision/checks/train_test_validation/train_test_label_drift.py
  deepchecks/vision/metrics_utils/__init__.py
  deepchecks/vision/metrics_utils/confusion_matrix_counts_metrics.py
  deepchecks/vision/metrics_utils/detection_tp_fp_fn_calc.py
  tests/tabular/checks/integrity/percent_of_nulls_test.py
  tests/tabular/checks/train_test_validation/train_test_feature_drift_test.py
  tests/vision/checks/model_evaluation/class_performance_test.py
Labels: feature, monitoring

#1996 Fixed dependencies check
  .github/workflows/build.yml
Labels: ci

#1953 feature: Task type warning for multiclass label containing integer
  deepchecks/tabular/dataset.py
  tests/base/dataset_test.py
Labels: feature

#1995 Deprecate old modules
  deepchecks/checks.py
  deepchecks/core/check_result.py
  deepchecks/suites.py
  deepchecks/tabular/checks/__init__.py
  deepchecks/tabular/checks/distribution/__init__.py
  deepchecks/tabular/checks/methodology/__init__.py
  deepchecks/tabular/checks/model_evaluation/__init__.py
  deepchecks/tabular/checks/model_evaluation/model_error_analysis.py
  deepchecks/tabular/checks/model_evaluation/performance_report.py
  deepchecks/tabular/checks/model_evaluation/simple_model_comparison.py
  deepchecks/tabular/checks/model_evaluation/train_test_prediction_drift.py
  deepchecks/tabular/checks/overview/__init__.py
  deepchecks/tabular/checks/performance/__init__.py
  deepchecks/tabular/checks/train_test_validation/__init__.py
  deepchecks/tabular/checks/train_test_validation/dominant_frequency_change.py
  deepchecks/tabular/checks/train_test_validation/identifier_leakage.py
  deepchecks/tabular/checks/train_test_validation/train_test_feature_drift.py
  deepchecks/tabular/checks/train_test_validation/train_test_label_drift.py
  deepchecks/tabular/checks/train_test_validation/whole_dataset_drift.py
  deepchecks/tabular/deprecation_warnings.py
  deepchecks/tabular/suites/__init__.py
  deepchecks/tabular/suites/default_suites.py
  deepchecks/vision/checks/distribution/__init__.py
  deepchecks/vision/checks/methodology/__init__.py
  deepchecks/vision/checks/model_evaluation/train_test_prediction_drift.py
  deepchecks/vision/checks/performance/__init__.py
  deepchecks/vision/checks/train_test_validation/image_dataset_drift.py
  deepchecks/vision/checks/train_test_validation/image_property_drift.py
  deepchecks/vision/checks/train_test_validation/train_test_label_drift.py
  deepchecks/vision/deprecation_warnings.py
  deepchecks/vision/suites/__init__.py
  deepchecks/vision/suites/default_suites.py
  deepchecks/vision/utils/image_properties.py
  deepchecks/vision/utils/vision_properties.py
  docs/source/checks/tabular/train_test_validation/plot_dominant_frequency_change.py
  docs/source/user-guide/tabular/quickstarts/plot_quickstart_in_5_minutes.py
  docs/source/user-guide/tabular/tutorials/plot_phishing_urls.py
  docs/source/user-guide/vision/tutorials/plot_custom_task_tutorial.py
  tests/base/check_suite_test.py
  tests/base/test_tabular_deprecation_warnings.py
  tests/examples_validation.py
  tests/tabular/checks/model_evaluation/model_error_analysis_test.py
  tests/tabular/checks/train_test_validation/dominant_frequency_change_test.py
  tests/tabular/test_dummy_model.py
  tests/vision/base/test_vision_deprecation_warnings.py
  tests/vision/checks/data_integrity/image_property_outliers_test.py
  tests/vision/checks/data_integrity/label_property_outliers_test.py
  tests/vision/checks/model_evaluation/train_test_prediction_drift_test.py
  tests/vision/checks/train_test_validation/train_test_label_drift_test.py
Labels: breaking-backwards-compatabillity, feature

#1998 Changed owners:
  .github/CODEOWNERS
Labels: ci

#2001 Nb/feat/reduce performance
  deepchecks/tabular/checks/model_evaluation/single_dataset_performance.py
  deepchecks/vision/checks/model_evaluation/single_dataset_performance.py
  tests/tabular/checks/model_evaluation/single_dataset_performance_test.py
  tests/vision/checks/model_evaluation/single_dataset_performance_test.py
Labels: bug

#1993 Nlp docs base & supported tasks
  deepchecks/nlp/__init__.py
  deepchecks/nlp/_shared_docs.py
  deepchecks/nlp/metric_utils/__init__.py
  docs/source/api/deepchecks.nlp.checks.rst
  docs/source/api/deepchecks.nlp.rst
  docs/source/api/deepchecks.nlp.suites.rst
  docs/source/user-guide/index.rst
  docs/source/user-guide/nlp/coming_soon.rst
  docs/source/user-guide/nlp/supported_tasks.rst
Labels: documentation

#2006 use deepchecks metrics for precision recall f1
  deepchecks/tabular/checks/model_evaluation/single_dataset_performance.py
  deepchecks/tabular/metric_utils/scorers.py
Labels: feature

#1994 Added duplicate column validation
  deepchecks/tabular/dataset.py
  tests/base/dataset_test.py
Labels: feature

#2004 1939 semantic segmentation metrics
  deepchecks/vision/metrics_utils/scorers.py
  deepchecks/vision/metrics_utils/semantic_segmentation_metric_utils.py
  deepchecks/vision/metrics_utils/semantic_segmentation_metrics.py
  tests/vision/checks/model_evaluation/single_dataset_performance_test.py
  tests/vision/utils_tests/metrics_test.py
Labels: feature, vision

#2007 Remove the ever-present warnings about direct imports from deepchecks
  deepchecks/vision/checks/data_integrity/abstract_property_outliers.py
  deepchecks/vision/checks/data_integrity/property_label_correlation.py
  deepchecks/vision/utils/property_label_correlation_utils.py
  extensive_testing/run_extensive_tests.py
Labels: bug

#1991 Segmentation docs and tests 1888
  deepchecks/vision/datasets/segmentation/__init__.py
  deepchecks/vision/datasets/segmentation/segmentation_coco.py
  deepchecks/vision/metrics_utils/scorers.py
  deepchecks/vision/metrics_utils/semantic_segmentation_metric_utils.py
  deepchecks/vision/metrics_utils/semantic_segmentation_metrics.py
  deepchecks/vision/segmentation_data.py
  docs/source/_static/images/tutorials/segmentation_5_examples.png
  docs/source/getting-started/welcome.rst
  docs/source/user-guide/vision/data-classes/DetectionData.rst
  docs/source/user-guide/vision/data-classes/SegmentationData.rst
  docs/source/user-guide/vision/data-classes/index.rst
  docs/source/user-guide/vision/quickstarts/plot_detection_tutorial.py
  docs/source/user-guide/vision/quickstarts/plot_segmentation_tutorial.py
  spelling-allowlist.txt
  tests/vision/base/test_vision_data.py
  tests/vision/checks/data_integrity/label_property_outliers_test.py
  tests/vision/checks/model_evaluation/class_performance_test.py
  tests/vision/checks/model_evaluation/image_segment_performance_test.py
  tests/vision/checks/model_evaluation/single_dataset_performance_test.py
  tests/vision/checks/model_evaluation/train_test_prediction_drift_test.py
  tests/vision/checks/train_test_validation/train_test_label_drift_test.py
  tests/vision/utils_tests/label_prediction_properties_test.py
  tests/vision/utils_tests/metrics_test.py
  tests/vision/utils_tests/properties_utils_tests.py
Labels: documentation

#2014 Add code to load the airbnb dataset
  .github/workflows/build.yml
  deepchecks/tabular/datasets/regression/__init__.py
  deepchecks/tabular/datasets/regression/airbnb.py
  requirements/requirements.txt
  tests/tabular/test_datasets.py
Labels: feature

#2011 Feat/added deprecation warning to whole dataset drift check
  deepchecks/checks.py
  deepchecks/core/check_utils/multivariate_drift_utils.py
  deepchecks/tabular/checks/__init__.py
  deepchecks/tabular/checks/train_test_validation/__init__.py
  deepchecks/tabular/checks/train_test_validation/multivariate_drift.py
  deepchecks/tabular/checks/train_test_validation/whole_dataset_drift.py
  deepchecks/tabular/deprecation_warnings.py
  deepchecks/tabular/suites/default_suites.py
  deepchecks/vision/checks/train_test_validation/image_dataset_drift.py
  docs/source/checks/tabular/train_test_validation/plot_multivariate_drift.py
  docs/source/checks/tabular/train_test_validation/plot_train_test_feature_drift.py
  docs/source/user-guide/general/drift_guide.rst
  docs/source/user-guide/general/exporting_results/plot_export_outputs_to_json.py
  docs/source/user-guide/general/exporting_results/plot_exports_output_to_wandb.py
  docs/source/user-guide/tabular/feature_importance.rst
  docs/source/user-guide/tabular/quickstarts/plot_quick_train_test_validation.py
  tests/base/test_tabular_deprecation_warnings.py
  tests/examples_validation.py
  tests/tabular/checks/train_test_validation/multivariate_drift_test.py
Labels: feature

#2019 Add n_samples to all tabular checks (except dataset size check)
  deepchecks/tabular/_shared_docs.py
  deepchecks/tabular/base_checks.py
  deepchecks/tabular/checks/data_integrity/conflicting_labels.py
  deepchecks/tabular/checks/data_integrity/data_duplicates.py
  deepchecks/tabular/checks/data_integrity/feature_feature_correlation.py
  deepchecks/tabular/checks/data_integrity/feature_label_correlation.py
  deepchecks/tabular/checks/data_integrity/identifier_label_correlation.py
  deepchecks/tabular/checks/data_integrity/is_single_value.py
  deepchecks/tabular/checks/data_integrity/mixed_data_types.py
  deepchecks/tabular/checks/data_integrity/mixed_nulls.py
  deepchecks/tabular/checks/data_integrity/percent_of_nulls.py
  deepchecks/tabular/checks/data_integrity/special_chars.py
  deepchecks/tabular/checks/data_integrity/string_length_out_of_bounds.py
  deepchecks/tabular/checks/model_evaluation/boosting_overfit.py
  deepchecks/tabular/checks/model_evaluation/calibration_score.py
  deepchecks/tabular/checks/model_evaluation/confusion_matrix_report.py
  deepchecks/tabular/checks/model_evaluation/model_inference_time.py
  deepchecks/tabular/checks/model_evaluation/multi_model_performance_report.py
  deepchecks/tabular/checks/model_evaluation/regression_error_distribution.py
  deepchecks/tabular/checks/model_evaluation/regression_systematic_error.py
  deepchecks/tabular/checks/model_evaluation/roc_report.py
  deepchecks/tabular/checks/model_evaluation/segment_performance.py
  deepchecks/tabular/checks/model_evaluation/simple_model_comparison.py
  deepchecks/tabular/checks/model_evaluation/single_dataset_performance.py
  deepchecks/tabular/checks/model_evaluation/train_test_performance.py
  deepchecks/tabular/checks/model_evaluation/train_test_prediction_drift.py
  deepchecks/tabular/checks/model_evaluation/unused_features.py
  deepchecks/tabular/checks/train_test_validation/category_mismatch_train_test.py
  deepchecks/tabular/checks/train_test_validation/date_train_test_leakage_duplicates.py
  deepchecks/tabular/checks/train_test_validation/date_train_test_leakage_overlap.py
  deepchecks/tabular/checks/train_test_validation/feature_label_correlation_change.py
  deepchecks/tabular/checks/train_test_validation/index_leakage.py
  deepchecks/tabular/checks/train_test_validation/new_label_train_test.py
  deepchecks/tabular/checks/train_test_validation/train_test_label_drift.py
  deepchecks/tabular/checks/train_test_validation/train_test_samples_mix.py
  deepchecks/tabular/context.py
  deepchecks/tabular/dataset.py
  deepchecks/tabular/suite.py
  tests/tabular/checks/integrity/identifier_label_correlation_test.py
  tests/tabular/checks/model_evaluation/simple_model_comparison_test.py
  tests/tabular/checks/train_test_validation/feature_label_correlation_test.py
Labels: feature

#2020 Add all sklearn scorers
  deepchecks/tabular/metric_utils/scorers.py
  docs/source/user-guide/general/metrics_guide.rst
  spelling-allowlist.txt
Labels: feature

#2025 0.9 hf
  docs/source/_static/switcher.json
  requirements/requirements.txt
Labels: bug

#1999 added documentation for tabular Model Evaluation checks
  docs/source/checks/tabular/model_evaluation/plot_boosting_overfit.py
  docs/source/checks/tabular/model_evaluation/plot_calibration_score.py
  docs/source/checks/tabular/model_evaluation/plot_confusion_matrix_report.py
  docs/source/checks/tabular/model_evaluation/plot_model_inference_time.py
  docs/source/checks/tabular/model_evaluation/plot_model_info.py
  docs/source/checks/tabular/model_evaluation/plot_multi_model_performance_report.py
  docs/source/checks/tabular/model_evaluation/plot_regression_error_distribution.py
  docs/source/checks/tabular/model_evaluation/plot_regression_systematic_error.py
  docs/source/checks/tabular/model_evaluation/plot_roc_report.py
  docs/source/checks/tabular/model_evaluation/plot_simple_model_comparison.py
  docs/source/checks/tabular/model_evaluation/plot_single_dataset_performance.py
  docs/source/checks/tabular/model_evaluation/plot_train_test_performance.py
  docs/source/checks/tabular/model_evaluation/plot_train_test_prediction_drift.py
  docs/source/checks/tabular/model_evaluation/plot_weak_segments_performance.py
Labels: documentation

#2024 1964 improve tf idf drift
  deepchecks/nlp/checks/train_test_validation/keyword_frequency_drift.py
  deepchecks/tabular/checks/model_evaluation/single_dataset_performance.py
  deepchecks/tabular/metric_utils/scorers.py
  tests/nlp/checks/train_test_validation/keyword_frequency_drift_test.py
Labels: feature, nlp

#2015 [FEAT] new class imbalance check
  deepchecks/checks.py
  deepchecks/tabular/checks/__init__.py
  deepchecks/tabular/checks/data_integrity/__init__.py
  deepchecks/tabular/checks/data_integrity/class_imbalance.py
  docs/source/checks/tabular/data_integrity/plot_class_imbalance.py
  tests/tabular/checks/integrity/class_imbalance_test.py
Labels: feature

#2032 Static properties enum fix
  deepchecks/vision/batch_wrapper.py
  deepchecks/vision/utils/vision_properties.py
  tests/vision/base/test_static_properties.py
Labels: bug, vision

#2026 ability to pass classes argument + auto infer to context
  deepchecks/core/check_utils/multivariate_drift_utils.py
  deepchecks/tabular/checks/data_integrity/class_imbalance.py
  deepchecks/tabular/checks/data_integrity/columns_info.py
  deepchecks/tabular/checks/data_integrity/mixed_data_types.py
  deepchecks/tabular/checks/data_integrity/mixed_nulls.py
  deepchecks/tabular/checks/data_integrity/special_chars.py
  deepchecks/tabular/checks/data_integrity/string_length_out_of_bounds.py
  deepchecks/tabular/checks/data_integrity/string_mismatch.py
  deepchecks/tabular/checks/model_evaluation/boosting_overfit.py
  deepchecks/tabular/checks/model_evaluation/calibration_score.py
  deepchecks/tabular/checks/model_evaluation/multi_model_performance_report.py
  deepchecks/tabular/checks/model_evaluation/roc_report.py
  deepchecks/tabular/checks/model_evaluation/segment_performance.py
  deepchecks/tabular/checks/model_evaluation/simple_model_comparison.py
  deepchecks/tabular/checks/model_evaluation/single_dataset_performance.py
  deepchecks/tabular/checks/model_evaluation/train_test_performance.py
  deepchecks/tabular/checks/model_evaluation/train_test_prediction_drift.py
  deepchecks/tabular/checks/model_evaluation/weak_segments_performance.py
  deepchecks/tabular/checks/train_test_validation/string_mismatch_comparison.py
  deepchecks/tabular/checks/train_test_validation/train_test_label_drift.py
  deepchecks/tabular/context.py
  deepchecks/tabular/dataset.py
  deepchecks/tabular/deprecation_warnings.py
  deepchecks/tabular/feature_importance.py
  deepchecks/tabular/metric_utils/__init__.py
  deepchecks/tabular/metric_utils/scorers.py
  deepchecks/tabular/utils/feature_importance.py
  deepchecks/tabular/utils/feature_inference.py
  deepchecks/tabular/utils/task_inference.py
  deepchecks/tabular/utils/task_type.py
  deepchecks/utils/docref.py
  deepchecks/utils/performance/error_model.py
  docs/source/checks/tabular/data_integrity/plot_columns_info.py
  docs/source/checks/tabular/data_integrity/plot_mixed_data_types.py
  docs/source/checks/tabular/model_evaluation/plot_boosting_overfit.py
  docs/source/user-guide/general/metrics_guide.rst
  docs/source/user-guide/tabular/supported_models.rst
  tests/base/dataset_test.py
  tests/base/feature_importance_utils_test.py
  tests/base/test_tabular_deprecation_warnings.py
  tests/tabular/checks/integrity/class_imbalance_test.py
  tests/tabular/checks/integrity/conflicting_labels_test.py
  tests/tabular/checks/integrity/percent_of_nulls_test.py
  tests/tabular/checks/model_evaluation/calibration_score_test.py
  tests/tabular/checks/model_evaluation/confusion_matrix_report_test.py
  tests/tabular/checks/model_evaluation/regression_error_distribution_test.py
  tests/tabular/checks/model_evaluation/regression_systematic_error_test.py
  tests/tabular/checks/model_evaluation/roc_report_test.py
  tests/tabular/checks/model_evaluation/single_dataset_performance_test.py
  tests/tabular/checks/model_evaluation/train_test_performance_test.py
  tests/tabular/checks/train_test_validation/category_mismatch_test.py
  tests/tabular/checks/train_test_validation/train_test_feature_drift_test.py
  tests/tabular/test_datasets.py
  tests/utils/metrics_test.py
  tests/utils/test_task_inference.py
  tests/vision/checks/data_integrity/label_property_outliers_test.py
  tests/vision/checks/model_evaluation/single_dataset_performance_test.py
  tests/vision/utils_tests/metrics_test.py
Labels: feature

#2035 [DOCS] Test for adding "all-contributors" to readme
  .all-contributorsrc
  .licenserc_fix.yaml
  README.rst
Labels: documentation

#2033 [DOCS] Omit double sentence in property label correlation check examples
  docs/source/checks/vision/data_integrity/plot_property_label_correlation.py
  docs/source/checks/vision/train_test_validation/plot_property_label_correlation_change.py
Labels: documentation

#2050 deepchecks scorer 2.0
  deepchecks/tabular/checks/model_evaluation/calibration_score.py
  deepchecks/tabular/checks/model_evaluation/weak_segments_performance.py
  deepchecks/tabular/context.py
  deepchecks/tabular/dataset.py
  deepchecks/tabular/metric_utils/scorers.py
  deepchecks/tabular/utils/feature_importance.py
  deepchecks/tabular/utils/task_inference.py
  deepchecks/utils/array_math.py
  deepchecks/utils/distribution/drift.py
  deepchecks/vision/metrics_utils/custom_scorer.py
  deepchecks/vision/metrics_utils/scorers.py
  docs/source/user-guide/tabular/supported_models.rst
  tests/tabular/checks/model_evaluation/single_dataset_performance_test.py
  tests/tabular/suites/test_suites.py
  tests/tabular/test_feature_importance_user_utils.py
  tests/vision/checks/model_evaluation/single_dataset_performance_test.py
Labels: bug, feature

#2049 Add favicon to suite html output
  deepchecks/core/resources/suite-template-full.html
Labels: feature

#2058 Fix add_condition_train_test_relative_degradation_less_than for Regression
  deepchecks/core/check_utils/class_performance_utils.py
  tests/tabular/checks/model_evaluation/train_test_performance_test.py
Labels: bug

#2059 image property drift static properties fix + properties conf fix
  deepchecks/utils/function.py
  deepchecks/vision/checks/train_test_validation/image_property_drift.py
Labels: bug
