Repository deepchecks/deepchecks, pull requests merged in 2022-04, with the labels that each got.

#1160 Using abstraction for vision average precision
  deepchecks/vision/checks/performance/mean_average_precision_report.py
  deepchecks/vision/checks/performance/mean_average_recall_report.py
  deepchecks/vision/metrics_utils/detection_precision_recall.py
  deepchecks/vision/metrics_utils/iou_utils.py
  deepchecks/vision/metrics_utils/metrics.py
  deepchecks/vision/metrics_utils/object_detection_precision_recall.py
  makefile
  tests/vision/utils_tests/metrics_test.py
Labels: refactoring

#1176 added texlive-latex-extra for missing style files
  .github/workflows/build.yml
  .github/workflows/docs.yaml
Labels: documentation

#1178 fix image array dtype
  deepchecks/vision/utils/image_functions.py
Labels: bugfix

#1180 custom metrics reuse bug
  deepchecks/vision/checks/performance/image_segment_performance.py
  deepchecks/vision/metrics_utils/metrics.py
  tests/vision/checks/performance/class_performance_test.py
  tests/vision/checks/performance/robustness_report_test.py
Labels: bugfix

#1190 Fix ModelErrorAnalysis task type error
  deepchecks/vision/checks/performance/model_error_analysis.py
Labels: bugfix

#1182 fi_random_state_fix
  deepchecks/utils/features.py
Labels: bugfix

#1192 Update robustness test
  tests/vision/checks/performance/robustness_report_test.py
Labels: bugfix

#1135 Similar image leakage 850
  README.rst
  deepchecks/tabular/checks/distribution/train_test_feature_drift.py
  deepchecks/vision/checks/__init__.py
  deepchecks/vision/checks/methodology/__init__.py
  deepchecks/vision/checks/methodology/similar_image_leakage.py
  deepchecks/vision/utils/test_utils.py
  docs/source/examples/vision/checks/methodology/source/plot_similar_image_leakage.py
  docs/source/examples/vision/checks/methodology/source/plot_simple_feature_contribution.py
  requirements/vision-requirements.txt
  spelling-allowlist.txt
  tests/vision/checks/methodology/similar_image_leakage_test.py
  tests/vision/checks/methodology/simple_feature_contribution_test.py
Labels: feature

#1181 fix_train_test_links
  deepchecks/core/check_result.py
  deepchecks/core/display_pandas.py
Labels: bugfix

#1185 fixed tooltips and getting started content on sidebar
  docs/source/conf.py
  docs/source/examples/tabular/checks/distribution/source/plot_train_test_feature_drift.py
  docs/source/examples/tabular/checks/distribution/source/plot_train_test_prediction_drift.py
  docs/source/examples/tabular/checks/distribution/source/plot_whole_dataset_drift.py
  docs/source/examples/tabular/checks/integrity/source/plot_data_duplicates.py
  docs/source/examples/tabular/checks/integrity/source/plot_label_ambiguity.py
  docs/source/examples/tabular/checks/methodology/source/plot_boosting_overfit.py
  docs/source/examples/tabular/checks/methodology/source/plot_single_feature_contribution_train_test.py
  docs/source/examples/tabular/checks/overview/source/plot_columns_info.py
  docs/source/examples/vision/checks/distribution/source/plot_heatmap_comparison.py
  docs/source/examples/vision/checks/distribution/source/plot_image_dataset_drift.py
  docs/source/examples/vision/checks/distribution/source/plot_image_property_check.py
  docs/source/examples/vision/checks/distribution/source/plot_image_property_outliers.py
  docs/source/examples/vision/checks/distribution/source/plot_label_property_outliers.py
  docs/source/examples/vision/checks/distribution/source/plot_train_test_label_drift.py
  docs/source/examples/vision/checks/distribution/source/plot_train_test_prediction_drift.py
  docs/source/examples/vision/checks/methodology/source/plot_simple_feature_contribution.py
  docs/source/examples/vision/checks/performance/source/plot_class_performance.py
  docs/source/examples/vision/checks/performance/source/plot_confusion_matrix.py
  docs/source/examples/vision/checks/performance/source/plot_image_segment_performance.py
  docs/source/examples/vision/checks/performance/source/plot_mean_average_precision_report.py
  docs/source/examples/vision/checks/performance/source/plot_mean_average_recall_report.py
  docs/source/examples/vision/checks/performance/source/plot_robustness_report.py
  docs/source/examples/vision/checks/performance/source/plot_simple_model_comparison.py
  docs/source/getting-started/get-started.rst
  docs/source/getting-started/index.rst
  docs/source/tutorials/tabular/plot_add_a_custom_check.py
  docs/source/tutorials/tabular/plot_phishing_urls.py
  docs/source/tutorials/tabular/plot_quickstart_in_5_minutes.py
  docs/source/tutorials/vision/plot_classification_tutorial.py
  docs/source/tutorials/vision/plot_detection_tutorial.py
  docs/source/tutorials/vision/plot_extractors_validating.py
  docs/source/user-guide/general/customizations/plot_configure_check_conditions.py
  docs/source/user-guide/general/customizations/plot_create_a_custom_suite.py
  docs/source/user-guide/general/exporting_results/plot_export_outputs_to_json.py
  docs/source/user-guide/general/exporting_results/plot_export_suite_results_as_html.py
  docs/source/user-guide/general/exporting_results/plot_exports_output_to_wandb.py
Labels: documentation

#1197 fix_tensor_gpu
  deepchecks/vision/batch_wrapper.py
  deepchecks/vision/checks/distribution/heatmap_comparison.py
  deepchecks/vision/checks/methodology/simple_feature_contribution.py
  deepchecks/vision/utils/transformations.py
  tests/vision/vision_conftest.py
Labels: bugfix

#1193 change image property drift to raise error instead of returning None
  deepchecks/vision/checks/distribution/image_property_drift.py
Labels: bugfix

#1194 add_condition_type and test suite condition category results
  deepchecks/core/checks.py
  deepchecks/core/condition.py
  deepchecks/core/display_suite.py
  tests/base/check_test.py
  tests/conftest.py
  tests/suites/test_suites.py
  tests/vision/base/test_suite.py
Labels: feature

#1195 Add sampling to checks and suite run
  deepchecks/core/display_suite.py
  deepchecks/core/suite.py
  deepchecks/vision/base_checks.py
  deepchecks/vision/context.py
  deepchecks/vision/suite.py
  deepchecks/vision/vision_data.py
  tests/vision/base/test_vision_data.py
  tests/vision/checks/distribution/heatmap_comparison_test.py
  tests/vision/checks/distribution/image_dataset_drift_test.py
  tests/vision/checks/distribution/image_property_outliers_test.py
  tests/vision/checks/distribution/label_property_outliers_test.py
  tests/vision/checks/distribution/train_test_prediction_drift_test.py
  tests/vision/checks/methodology/simple_feature_contribution_test.py
  tests/vision/checks/performance/class_performance_test.py
  tests/vision/checks/performance/image_segment_performance_test.py
  tests/vision/checks/performance/robustness_report_test.py
  tests/vision/checks/performance/vision_model_error_analysis_test.py
Labels: feature

#1207 fix confusion matrix bug caused when only one row
  deepchecks/vision/checks/performance/confusion_matrix.py
Labels: bugfix

#1209 Fix the logic finding the weak segment in categorical features.
  deepchecks/utils/performance/error_model.py
  deepchecks/vision/vision_data.py
Labels: bugfix

#1212 Fixing performance bugs
  deepchecks/vision/checks/performance/class_performance.py
  deepchecks/vision/checks/performance/simple_model_comparison.py
  deepchecks/vision/suites/default_suites.py
Labels: bugfix

#1217 Fix read more
  deepchecks/tabular/checks/integrity/__init__.py
  deepchecks/tabular/checks/integrity/category_mismatch_train_test.py
  deepchecks/tabular/checks/integrity/new_label_train_test.py
  deepchecks/tabular/checks/performance/__init__.py
  deepchecks/tabular/checks/performance/multi_model_performance_report.py
  deepchecks/tabular/checks/performance/performance_report.py
  deepchecks/utils/strings.py
  docs/source/examples/tabular/checks/integrity/source/plot_category_mismatch_train_test.py
  docs/source/examples/tabular/checks/integrity/source/plot_new_label_train_test.py
  docs/source/examples/tabular/checks/methodology/source/plot_single_feature_contribution.py
  docs/source/examples/vision/checks/distribution/source/plot_image_property_drift.py
  tests/utils/test_string_utils.py
Labels: bugfix

#1224 Fixing wandb example redirect
  docs/source/conf.py
Labels: documentation

#1213 wandb train/test fix plus better value formatting
  deepchecks/core/check_result.py
  deepchecks/tabular/context.py
  deepchecks/tabular/utils/__init__.py
  deepchecks/tabular/utils/validation.py
  deepchecks/utils/dataframes.py
  deepchecks/utils/features.py
  deepchecks/utils/validation.py
  tests/base/dataset_test.py
Labels: bugfix

#1226 Adding examples to conditions
  docs/source/conf.py
  docs/source/examples/vision/checks/performance/source/plot_class_performance.py
  docs/source/examples/vision/checks/performance/source/plot_simple_model_comparison.py
Labels: documentation

#1227 Disable CI telemetry
  .github/workflows/build.yml
  .github/workflows/docs.yaml
  .github/workflows/lint.yml
  .github/workflows/pr.yaml
  .github/workflows/release.yml
Labels: ci

#1199 Fix drift plots for few unique numerical values
  deepchecks/utils/distribution/drift.py
  deepchecks/utils/distribution/plot.py
  deepchecks/utils/plot.py
  deepchecks/vision/checks/distribution/image_property_drift.py
  spelling-allowlist.txt
Labels: bugfix

#1230 fixed simple model new classes in test behavior
  deepchecks/tabular/checks/performance/simple_model_comparison.py
  deepchecks/vision/checks/performance/simple_model_comparison.py
  tests/checks/performance/simple_model_comparison_test.py
Labels: bugfix

#1228 1140 bug cv add label map to conditions
  deepchecks/vision/checks/performance/class_performance.py
Labels: bugfix

#1231 Update README to accommodate beta release of vision package
  README.rst
  deepchecks/vision/README.rst
  docs/images/vision-checks/brightness-outlier-1.png
  docs/images/vision-checks/brightness-outlier-2.png
  docs/images/vision-checks/brightness-outlier-3.png
  docs/images/vision-checks/brightness-outlier-4.png
  docs/images/vision-checks/brightness-outlier-5.png
  docs/images/vision-checks/brightness-outlier-6.png
  docs/images/vision-checks/mAP-over-IoU.png
Labels: documentation

#1223 reduce runtime of jaccard_iou by more than 50 percent
  deepchecks/vision/checks/performance/confusion_matrix.py
  deepchecks/vision/metrics_utils/iou_utils.py
  deepchecks/vision/metrics_utils/object_detection_precision_recall.py
  tests/vision/checks/performance/vision_model_error_analysis_test.py
Labels: bugfix

#1234 Upgrade gpu torch vision
  makefile
Labels: ci

#1232 fix suite progress bar in single checks
  deepchecks/vision/suite.py
  tests/vision/base/test_suite.py
Labels: bugfix

#1235 RobustnessReport & ClassPerformance work on custom task
  deepchecks/vision/checks/performance/class_performance.py
  deepchecks/vision/checks/performance/robustness_report.py
  deepchecks/vision/metrics_utils/metrics.py
  tests/vision/checks/performance/class_performance_test.py
  tests/vision/checks/performance/image_segment_performance_test.py
  tests/vision/checks/performance/robustness_report_test.py
  tests/vision/vision_conftest.py
Labels: bugfix

#1229 Add tests for docs plots on GPU
  docs/source/tutorials/vision/plot_classification_tutorial.py
  docs/source/tutorials/vision/plot_detection_tutorial.py
  tests/vision/docs/test_plots.py
Labels: bugfix

#1236 Add progress bars to single checks runs
  deepchecks/vision/base_checks.py
Labels: feature

#1239 Fix model error plot
  deepchecks/utils/performance/error_model.py
Labels: bugfix

#1244 align the label index in LABEL_MAP to match cls_id
  docs/source/tutorials/vision/plot_detection_tutorial.py
Labels: bugfix

#1245 Update outliers & robustness image grid
  deepchecks/vision/checks/distribution/abstract_property_outliers.py
  deepchecks/vision/checks/performance/robustness_report.py
  deepchecks/vision/utils/image_functions.py
Labels: bugfix

#1225 Model error analysis gallery
  docs/source/examples/vision/checks/performance/source/plot_model_error_analysis.py
  tests/checks/performance/model_error_analysis_test.py
Labels: documentation

#1211 mixed nulls on non string columns
  deepchecks/tabular/checks/integrity/mixed_nulls.py
  tests/checks/integrity/mixed_nulls_test.py
Labels: feature

#1249 Update width: inherit to fill-available
  deepchecks/vision/checks/distribution/abstract_property_outliers.py
  deepchecks/vision/checks/performance/robustness_report.py
Labels: bugfix

#1252 allow checks to return CheckFailure
  deepchecks/core/check_result.py
  deepchecks/core/checks.py
  deepchecks/tabular/checks/performance/model_error_analysis.py
  deepchecks/vision/base_checks.py
  deepchecks/vision/checks/performance/model_error_analysis.py
  tests/checks/performance/model_error_analysis_test.py
  tests/vision/checks/performance/vision_model_error_analysis_test.py
Labels: feature

#1269 Remove difference from heatmap comparison
  deepchecks/vision/checks/distribution/heatmap_comparison.py
  docs/source/examples/vision/checks/distribution/source/plot_heatmap_comparison.py
Labels: bugfix

#1237 1168 feat single dataset outlier detection
  deepchecks/checks.py
  deepchecks/tabular/checks/__init__.py
  deepchecks/tabular/checks/integrity/__init__.py
  deepchecks/tabular/checks/integrity/outlier_sample_detection.py
  deepchecks/tabular/suites/default_suites.py
  deepchecks/utils/dataframes.py
  deepchecks/utils/gower_distance.py
  docs/requirements.txt
  docs/source/examples/tabular/checks/integrity/source/plot_outlier_sample_detection.py
  requirements/requirements.txt
  tests/checks/integrity/outlier_sample_detection_test.py
  tests/utils/test_gower_distance.py
Labels: feature

#1271 improve performance_report notebook
  docs/source/examples/tabular/checks/performance/source/plot_performance_report.py
  docs/source/examples/tabular/checks/performance/source/plot_simple_model_comparison.py
Labels: documentation

#1270 Get exception traceback in suite easily
  deepchecks/core/check_result.py
  deepchecks/core/display_suite.py
  deepchecks/core/suite.py
  tests/base/check_suite_test.py
Labels: feature

#1275 Manually set iris label type
  deepchecks/tabular/datasets/classification/iris.py
Labels: bugfix

#1277 Check to html
  deepchecks/core/check_result.py
  deepchecks/core/display_suite.py
  deepchecks/utils/strings.py
  requirements/requirements.txt
Labels: feature

#1264 Link examples with apis
  docs/requirements.txt
  docs/source/_templates/autosummary/check.rst
  docs/source/_templates/layout.html
  docs/source/conf.py
Labels: documentation

#1273 Prevent empty datasets, as that can create bugs down the line
  deepchecks/tabular/context.py
  deepchecks/tabular/dataset.py
  tests/base/dataset_test.py
  tests/checks/integrity/data_duplicate_test.py
  tests/checks/integrity/is_single_value_test.py
  tests/checks/integrity/mixed_nulls_test.py
Labels: bugfix

#1278 fix over 255 bug in whole dataset drift
  deepchecks/core/check_utils/whole_dataset_drift_utils.py
  deepchecks/utils/distribution/rare_category_encoder.py
  tests/checks/distribution/whole_dataset_drift_test.py
Labels: bugfix

#1241 Add similar image leakage to default suite
  deepchecks/vision/checks/methodology/similar_image_leakage.py
  deepchecks/vision/suites/default_suites.py
  tests/vision/checks/methodology/similar_image_leakage_test.py
Labels: bugfix

#1282 Segment Performance display fix
  deepchecks/tabular/checks/performance/segment_performance.py
Labels: bugfix

#1281 make show function work on sphinx + fixed double output
  deepchecks/core/check_result.py
  deepchecks/core/suite.py
  deepchecks/utils/strings.py
  docs/source/conf.py
  docs/source/tutorials/tabular/plot_quickstart_in_5_minutes.py
Labels: bugfix

#1285 Add option to pass FI in tabular to single run
  deepchecks/tabular/base_checks.py
  deepchecks/tabular/context.py
  tests/base/check_test.py
Labels: bugfix

#1293 Update warning on categorical infer
  deepchecks/tabular/dataset.py
  tests/base/dataset_test.py
Labels: feature

#1291 fix_check_html_style
  deepchecks/core/check_result.py
Labels: bugfix

#1289 disable tqdm globally in tests
  tests/conftest.py
Labels: tests

#1297 Similar image leakage 1243
  deepchecks/vision/checks/methodology/similar_image_leakage.py
Labels: bugfix

#1288 New categorical drift method 1138
  deepchecks/tabular/base_checks.py
  deepchecks/tabular/checks/distribution/train_test_feature_drift.py
  deepchecks/tabular/checks/distribution/train_test_label_drift.py
  deepchecks/tabular/checks/distribution/train_test_prediction_drift.py
  deepchecks/tabular/deprecation_warnings.py
  deepchecks/utils/distribution/drift.py
  deepchecks/utils/distribution/plot.py
  deepchecks/utils/distribution/preprocessing.py
  deepchecks/utils/features.py
  deepchecks/vision/base_checks.py
  deepchecks/vision/checks/distribution/image_property_drift.py
  deepchecks/vision/checks/distribution/train_test_label_drift.py
  deepchecks/vision/checks/distribution/train_test_prediction_drift.py
  deepchecks/vision/deprecation_warnings.py
  docs/source/examples/vision/checks/distribution/source/plot_image_property_drift.py
  tests/vision/checks/distribution/train_test_label_drift_test.py
  tests/vision/checks/distribution/train_test_prediction_drift_test.py
Labels: bugfix

#1296 Improve dominant frequency change example
  docs/source/examples/tabular/checks/integrity/source/plot_dominant_frequency_change.py
  docs/source/examples/tabular/checks/performance/source/plot_segment_performance.py
Labels: documentation

#1298 Adding examples validation
  .github/workflows/docs.yaml
  docs/requirements.txt
  docs/source/examples/tabular/checks/integrity/source/plot_special_chars.py
  makefile
  tests/examples_validation.py
Labels: ci, documentation

#1304 some fixes for a quick use of zenml
  deepchecks/core/check_result.py
  deepchecks/tabular/dataset.py
  requirements/requirements.txt
Labels: bugfix

#1306 fix inconsistent fi behavior
  deepchecks/utils/features.py
  tests/base/to_json_test.py
Labels: bugfix

#1316 Dc 1238 found nothing
  deepchecks/tabular/checks/integrity/category_mismatch_train_test.py
  deepchecks/tabular/checks/integrity/data_duplicates.py
  deepchecks/tabular/checks/integrity/is_single_value.py
  deepchecks/tabular/checks/integrity/mixed_data_types.py
  deepchecks/tabular/checks/integrity/mixed_nulls.py
  deepchecks/tabular/checks/integrity/special_chars.py
  deepchecks/tabular/checks/integrity/string_length_out_of_bounds.py
  deepchecks/tabular/checks/integrity/string_mismatch_comparison.py
  deepchecks/tabular/utils/display_utils.py
Labels: feature

#1318 Add test for depr warn
  deepchecks/core/check_utils/whole_dataset_drift_utils.py
  deepchecks/tabular/checks/distribution/whole_dataset_drift.py
  deepchecks/utils/distribution/drift.py
  deepchecks/vision/checks/distribution/image_dataset_drift.py
  tests/base/test_tabular_deprecation_warnings.py
  tests/vision/base/test_vision_deprecation_warnings.py
Labels: bugfix

#1321 Tutorial custom check quickfixes
  docs/source/tutorials/tabular/plot_add_a_custom_check.py
Labels: documentation, bugfix

#1317 Update unused features plot
  docs/source/examples/tabular/checks/methodology/source/plot_unused_features.py
Labels: documentation

#1315 Fi pipeline to always use permutation
  deepchecks/tabular/datasets/classification/adult.py
  deepchecks/utils/features.py
  deepchecks/utils/metrics.py
  deepchecks/utils/performance/error_model.py
  deepchecks/vision/checks/performance/model_error_analysis.py
  docs/source/examples/tabular/checks/performance/source/plot_model_error_analysis.py
  docs/source/examples/tabular/checks/performance/source/plot_segment_performance.py
  tests/base/feature_importance_utils_test.py
  tests/checks/distribution/train_test_feature_drift_test.py
  tests/checks/performance/model_error_analysis_test.py
  tests/vision/checks/performance/vision_model_error_analysis_test.py
Labels: bugfix

#1329 Condition image property fix
  deepchecks/vision/checks/distribution/image_property_drift.py
  tests/vision/checks/distribution/image_property_drift_test.py
Labels: bugfix

#1334 adds detach for tensor before using .numpy()
  deepchecks/vision/checks/performance/confusion_matrix.py
  deepchecks/vision/metrics_utils/iou_utils.py
Labels: bugfix

#1326 Update read more generation and add test
  deepchecks/utils/strings.py
  spelling-allowlist.txt
  tests/examples_validation.py
  tests/utils/test_string_utils.py
Labels: bugfix

#1324 Various single feature contribution fixes
  deepchecks/core/check_utils/single_feature_contribution_utils.py
  deepchecks/tabular/checks/methodology/single_feature_contribution.py
  deepchecks/tabular/checks/methodology/single_feature_contribution_train_test.py
  deepchecks/vision/checks/methodology/simple_feature_contribution.py
  deepchecks/vision/suites/__init__.py
  tests/checks/methodology/single_feature_contribution_test.py
  tests/vision/checks/methodology/simple_feature_contribution_test.py
Labels: bugfix

#1331 Similar image small fixes in docs
  deepchecks/vision/checks/methodology/similar_image_leakage.py
  docs/source/examples/vision/checks/methodology/source/plot_similar_image_leakage.py
  tests/vision/checks/methodology/similar_image_leakage_test.py
Labels: bugfix

#1325 Update train test samples mix docs
  docs/source/examples/tabular/checks/methodology/source/plot_train_test_samples_mix.py
Labels: documentation

#1337 Update single feature contribution plot
  deepchecks/core/check_utils/single_feature_contribution_utils.py
  deepchecks/tabular/checks/methodology/single_feature_contribution.py
  docs/source/examples/tabular/checks/methodology/source/plot_single_feature_contribution.py
Labels: feature

#1341 image segment memory fix
  deepchecks/vision/checks/performance/image_segment_performance.py
Labels: bugfix

#1352 Simple model global metric
  deepchecks/vision/checks/performance/simple_model_comparison.py
  docs/source/_templates/layout.html
  tests/vision/checks/performance/cv_simple_model_comparison_test.py
Labels: documentation, bugfix

#1345 Nb/documentation and autocasting pixels
  deepchecks/vision/batch_wrapper.py
  deepchecks/vision/checks/performance/image_segment_performance.py
  deepchecks/vision/vision_data.py
  docs/source/user-guide/vision/data-classes/DetectionData.rst
  tests/vision/checks/distribution/image_dataset_drift_test.py
  tests/vision/checks/distribution/image_property_outliers_test.py
  tests/vision/checks/methodology/simple_feature_contribution_test.py
  tests/vision/checks/performance/vision_model_error_analysis_test.py
  tests/vision/utils_tests/formatters_test.py
Labels: bugfix

#1333 Sklearn 0.23.2 support
  deepchecks/core/check_utils/whole_dataset_drift_utils.py
  requirements/dev-requirements.txt
  requirements/requirements.txt
Labels: feature
