Repository deepchecks/deepchecks, pull requests merged in 2022-11, with the labels that each got.

#2128 1945 additional property texture level
  deepchecks/vision/utils/image_properties.py
  tests/vision/utils_tests/properties_utils_tests.py
Labels: feature, vision

#2126 Enable getting model predictions using only the proba and the model_classes
  deepchecks/tabular/context.py
  deepchecks/tabular/metric_utils/scorers.py
  deepchecks/tabular/suite.py
  deepchecks/vision/metrics_utils/custom_scorer.py
  tests/tabular/test_dummy_model.py
Labels: feature

#2127 2095 deepcheck vision metrics access
  deepchecks/vision/metrics.py
  docs/source/api/deepchecks.vision.rst
  docs/source/user-guide/general/metrics_guide.rst
  examples/examples_metrics_guide.py
Labels: feature, vision

#2123 image properties linton
  deepchecks/vision/utils/image_properties.py
Labels: feature

#2132 1721 update cv quickstarts remove reference to full suite
  docs/source/user-guide/vision/quickstarts/plot_classification_tutorial.py
  docs/source/user-guide/vision/quickstarts/plot_detection_tutorial.py
Labels: documentation

#2136 change time_index to day_index
  deepchecks/vision/datasets/detection/mask.py
  tests/vision/datasets/test_mask.py
Labels: feature

#2138 Fix the x zoom in edge cases of drift
  deepchecks/utils/distribution/plot.py
Labels: bug

#2121 [Fix: 2110] Pass feature_importance_timeout through to feature importance
  deepchecks/core/check_utils/multivariate_drift_utils.py
  deepchecks/core/errors.py
  deepchecks/tabular/checks/train_test_validation/multivariate_drift.py
  deepchecks/tabular/context.py
  deepchecks/tabular/utils/feature_importance.py
  tests/tabular/checks/train_test_validation/multivariate_drift_test.py
Labels: bug

#2145 Fix _do_static_prop
  deepchecks/vision/batch_wrapper.py
Labels: bug

#2149 Fix warning in task_inference.py
  deepchecks/tabular/utils/task_inference.py
Labels: bug

#2155 Greater is better
  deepchecks/core/reduce_classes.py
  deepchecks/tabular/checks/model_evaluation/train_test_prediction_drift.py
  deepchecks/tabular/checks/train_test_validation/new_label_train_test.py
  deepchecks/tabular/checks/train_test_validation/train_test_label_drift.py
  deepchecks/tabular/metric_utils/scorers.py
  deepchecks/vision/checks/train_test_validation/new_labels.py
  tests/tabular/checks/model_evaluation/single_dataset_performance_test.py
  tests/tabular/checks/train_test_validation/train_test_label_drift_test.py
  tests/vision/checks/model_evaluation/single_dataset_performance_test.py
Labels: feature

#2154 Bug fix ROC report + some code cleanup
  deepchecks/tabular/checks/model_evaluation/roc_report.py
  deepchecks/tabular/utils/task_inference.py
  tests/tabular/checks/model_evaluation/roc_report_test.py
Labels: bug

#2157 docstring rule all
  deepchecks/tabular/checks/model_evaluation/roc_report.py
  tests/tabular/checks/model_evaluation/roc_report_test.py
Labels: documentation

#2156 Remove reduce from TrainTestPerformance
  deepchecks/tabular/checks/model_evaluation/train_test_performance.py
  docs/source/checks/tabular/train_test_validation/plot_train_test_feature_drift.py
  tests/tabular/checks/model_evaluation/train_test_performance_test.py
Labels: feature

#2148 1780 vision weak segment performance
  deepchecks/tabular/checks/model_evaluation/weak_segments_performance.py
  deepchecks/tabular/context.py
  deepchecks/utils/performance/weak_segment_abstract.py
  deepchecks/vision/checks/__init__.py
  deepchecks/vision/checks/model_evaluation/__init__.py
  deepchecks/vision/checks/model_evaluation/image_segment_performance.py
  deepchecks/vision/checks/model_evaluation/model_error_analysis.py
  deepchecks/vision/checks/model_evaluation/weak_segments_performance.py
  deepchecks/vision/deprecation_warnings.py
  deepchecks/vision/metrics_utils/semantic_segmentation_metrics.py
  docs/source/checks/vision/model_evaluation/plot_image_segment_performance.py
  docs/source/checks/vision/model_evaluation/plot_model_error_analysis.py
  docs/source/checks/vision/model_evaluation/plot_weak_segments_performance.py
  tests/utils/preprocessing_test.py
  tests/vision/base/test_vision_deprecation_warnings.py
  tests/vision/checks/model_evaluation/weak_segments_performance_test.py
  tests/vision/utils_tests/metrics_test.py
  tests/vision/vision_conftest.py
Labels: feature, vision

#2133 Add return statement to the validate_format function
  deepchecks/vision/utils/validation.py
  deepchecks/vision/vision_data.py
  tests/vision/utils_tests/formatters_test.py
Labels: feature

#2167 Make CI pipeline run also on major feature branches
  .github/workflows/build.yml
  .github/workflows/docs.yaml
  .github/workflows/lint.yml
Labels: ci

#2165 Nb/feat/vision checks without indexes
  .all-contributorsrc
  .github/workflows/build.yml
  .github/workflows/docs.yaml
  .github/workflows/lint.yml
  README.md
  deepchecks/vision/checks/data_integrity/abstract_property_outliers.py
  deepchecks/vision/checks/data_integrity/image_property_outliers.py
  deepchecks/vision/checks/data_integrity/label_property_outliers.py
  deepchecks/vision/checks/train_test_validation/new_labels.py
  deepchecks/vision/utils/display_utils.py
  deepchecks/vision/utils/validation.py
  deepchecks/vision/vision_data.py
  tests/vision/checks/data_integrity/image_property_outliers_test.py
  tests/vision/checks/data_integrity/label_property_outliers_test.py
  tests/vision/utils_tests/formatters_test.py
Labels: feature
