Repository deepchecks/deepchecks, pull requests merged in 2022-02, with the labels that each got.

#795 Fixing nb generation
  .github/workflows/nb-generation.yml
Labels: ci

#798 [issue-757] updated MNIST dataset api
  deepchecks/vision/datasets/classification/__init__.py
  deepchecks/vision/datasets/classification/mnist.py
  deepchecks/vision/datasets/detection/coco.py
  docs/source/examples/checks/vision/distribution/train_test_label_drift.ipynb
  docs/source/examples/checks/vision/performance/performance_report.ipynb
  requirements/vision-requirements.txt
  spelling-allowlist.txt
  tests/vision/datasets/test_mnsit.py
Labels: refactoring

#797 Label drift fixes
  deepchecks/vision/checks/distribution/train_test_label_drift.py
  deepchecks/vision/dataset.py
  docs/source/examples/checks/vision/distribution/train_test_label_drift.ipynb
  tests/vision/checks/distribution/train_test_label_drift_test.py
  tests/vision/vision_conftest.py
Labels: feature

#800 Adding labels and detection encoder classes
  deepchecks/vision/checks/performance/performance_report.py
  deepchecks/vision/dataset.py
  deepchecks/vision/datasets/classification/mnist.py
  deepchecks/vision/metrics_utils/metrics.py
  deepchecks/vision/utils/__init__.py
  deepchecks/vision/utils/base_formatters.py
  deepchecks/vision/utils/classification_formatters.py
  deepchecks/vision/utils/detection_formatters.py
  docs/source/examples/checks/vision/distribution/train_test_label_drift.ipynb
  docs/source/examples/checks/vision/performance/performance_report.ipynb
  makefile
  tests/vision/utils/formatters_test.py
  tests/vision/vision_conftest.py
Labels: feature

#807 Fix widget plotly bug
  deepchecks/utils/dataframes.py
  deepchecks/utils/distribution/plot.py
Labels: bugfix

#809 Fix widget plotly bug (#807)
  deepchecks/utils/dataframes.py
  deepchecks/utils/distribution/plot.py
Labels: bugfix

#817 Docs 0.4.x fixes
  README.rst
  VERSION
  docs/source/_static/checks_and_conditions.png
  docs/source/_static/pipeline_when_to_validate.png
  docs/source/_static/pipeline_when_to_validate.svg
  docs/source/examples/guides/quickstart_in_5_minutes.ipynb
  docs/source/getting-started/index.rst
  docs/source/index.rst
  docs/source/user-guide/when_should_you_use.rst
Labels: documentation

#820 rename VisionDataset to VisionData
  deepchecks/vision/__init__.py
  deepchecks/vision/base.py
  deepchecks/vision/checks/distribution/train_test_label_drift.py
  deepchecks/vision/dataset.py
  deepchecks/vision/datasets/classification/mnist.py
  deepchecks/vision/datasets/detection/coco.py
  deepchecks/vision/metrics_utils/metrics.py
  deepchecks/vision/utils/validation.py
  docs/source/examples/checks/vision/distribution/train_test_label_drift.ipynb
  docs/source/examples/checks/vision/performance/performance_report.ipynb
  tests/vision/checks/distribution/train_test_label_drift_test.py
  tests/vision/datasets/test_mnsit.py
  tests/vision/utils/formatters_test.py
  tests/vision/utils/metrics_test.py
  tests/vision/vision_conftest.py
Labels: refactoring

#812 add DataFormatter
  deepchecks/vision/dataset.py
  deepchecks/vision/utils/__init__.py
  deepchecks/vision/utils/base_formatters.py
  deepchecks/vision/utils/data_formatters.py
  tests/vision/utils/formatters_test.py
  tests/vision/vision_conftest.py
Labels: feature

#824 rename to ImageFormatter and fix bug in VisionData init
  deepchecks/vision/dataset.py
  deepchecks/vision/utils/__init__.py
  deepchecks/vision/utils/image_formatters.py
  tests/vision/utils/formatters_test.py
Labels: bugfix

#805 [issue-799] coco split into train/test; updated coco dataset module api
  .gitignore
  deepchecks/vision/dataset.py
  deepchecks/vision/datasets/detection/coco.py
  deepchecks/vision/metrics_utils/detection_precision_recall.py
  docs/source/examples/checks/vision/distribution/train_test_label_drift.ipynb
  docs/source/examples/checks/vision/performance/performance_report.ipynb
  tests/vision/datasets/test_coco.py
  tests/vision/datasets/test_mnsit.py
  tests/vision/vision_conftest.py
Labels: refactoring

#826 change checks to init - update - compute structure
  deepchecks/core/check.py
  deepchecks/tabular/base.py
  deepchecks/vision/base.py
  deepchecks/vision/checks/distribution/train_test_label_drift.py
  deepchecks/vision/checks/performance/performance_report.py
  deepchecks/vision/utils/classification_formatters.py
Labels: refactoring

#838 Fixing CI
  .github/workflows/lint.yml
Labels: ci

#808 Label drift fixes
  .github/workflows/build.yml
  deepchecks/vision/checks/distribution/train_test_label_drift.py
  deepchecks/vision/datasets/detection/coco.py
  docs/source/examples/checks/vision/distribution/train_test_label_drift.ipynb
  makefile
  tests/vision/checks/distribution/train_test_label_drift_test.py
  tests/vision/vision_conftest.py
Labels: refactoring

#843 Label drift refactor
  deepchecks/vision/checks/distribution/train_test_label_drift.py
  docs/source/examples/checks/vision/distribution/train_test_label_drift.ipynb
  tests/vision/checks/distribution/train_test_label_drift_test.py
Labels: refactoring

#844 Adding performance report nb
  deepchecks/vision/checks/__init__.py
  deepchecks/vision/checks/performance/__init__.py
  deepchecks/vision/checks/performance/class_performance.py
  deepchecks/vision/datasets/classification/mnist.py
  deepchecks/vision/datasets/detection/coco.py
  docs/source/examples/checks/vision/performance/class_performance.ipynb
  docs/source/examples/checks/vision/performance/performance_report.ipynb
Labels: documentation

#849 fix README.rst typo train-test
  README.rst
Labels: bugfix

#848 Added typehints where they were missing in CheckResult's methods.
  deepchecks/core/check.py
Labels: documentation

#837 Formatter docs
  deepchecks/vision/utils/classification_formatters.py
  deepchecks/vision/utils/detection_formatters.py
  docs/source/api/vision.rst
  docs/source/user-guide/formatter_objects.rst
  docs/source/user-guide/index.rst
  spelling-allowlist.txt
  tox.ini
Labels: documentation

#832 [issue-787] added device parameter to the vision checks context
  .github/workflows/build.yml
  deepchecks/core/check.py
  deepchecks/vision/base.py
  deepchecks/vision/checks/performance/class_performance.py
  deepchecks/vision/dataset.py
  deepchecks/vision/datasets/classification/mnist.py
  deepchecks/vision/datasets/detection/coco.py
  deepchecks/vision/metrics_utils/metrics.py
  deepchecks/vision/utils/validation.py
  makefile
  tests/vision/base/test_context.py
  tests/vision/base/test_suite.py
  tests/vision/base/test_vision_data.py
  tests/vision/utils_tests/__init__.py
  tests/vision/utils_tests/formatters_test.py
  tests/vision/utils_tests/metrics_test.py
  tests/vision/vision_conftest.py
  tox.ini
Labels: feature

#855 Added properties in image formatter
  deepchecks/vision/utils/image_formatters.py
Labels: feature

#858 Image properties
  deepchecks/vision/utils/image_formatters.py
  tests/vision/checks/performance/robustness_report_test.py
  tests/vision/utils_tests/formatters_test.py
Labels: tests

#857 suite fixes
  deepchecks/vision/base.py
Labels: bugfix

#867 Add title to drift plot
  deepchecks/utils/distribution/drift.py
  deepchecks/utils/distribution/plot.py
  deepchecks/vision/checks/distribution/train_test_label_drift.py
  docs/source/examples/tabular/checks/distribution/train_test_feature_drift.ipynb
  docs/source/examples/tabular/checks/distribution/train_test_label_drift.ipynb
  docs/source/examples/tabular/checks/distribution/whole_dataset_drift.ipynb
  docs/source/examples/vision/checks/distribution/train_test_label_drift.ipynb
Labels: feature

#869 Added imgaug-equivalent augmentations.
  deepchecks/vision/utils/transformations.py
Labels: feature

#868 add wrap_run to ModelComparisonCheck
  deepchecks/tabular/base.py
  docs/source/examples/tabular/checks/distribution/trust_score_comparison.ipynb
  docs/source/examples/tabular/checks/performance/multi_model_performance_report.ipynb
Labels: bugfix

#870 remove warnings
  deepchecks/core/check.py
  deepchecks/core/display_suite.py
  deepchecks/utils/distribution/preprocessing.py
Labels: bugfix

#873 Modifying make notebook
  makefile
Labels: ci

#885 Mean Average Recall Report check
  deepchecks/vision/checks/performance/__init__.py
  deepchecks/vision/checks/performance/mean_average_recall_report.py
  docs/source/examples/vision/checks/performance/mean_average_recall_report.ipynb
  tests/vision/checks/performance/mean_average_recall_report_test.py
Labels: feature

#891 Fix version read in init
  deepchecks/__init__.py
  deepchecks/vision/checks/performance/mean_average_recall_report.py
Labels: bugfix

#877 Adding label_map to dataset
  deepchecks/vision/checks/distribution/train_test_label_drift.py
  deepchecks/vision/checks/performance/class_performance.py
  deepchecks/vision/checks/performance/robustness_report.py
  deepchecks/vision/dataset.py
  deepchecks/vision/datasets/detection/coco.py
  deepchecks/vision/metrics_utils/metrics.py
  tests/vision/checks/distribution/train_test_label_drift_test.py
Labels: feature

#893 Fixed (maybe?) the tests
  tests/vision/checks/distribution/image_dataset_drift_test.py
Labels: bugfix

#902 Make image drift tests consistent
  deepchecks/vision/dataset.py
  deepchecks/vision/datasets/classification/mnist.py
  deepchecks/vision/datasets/detection/coco.py
  spelling-allowlist.txt
  tests/vision/checks/distribution/image_dataset_drift_test.py
  tests/vision/checks/distribution/train_test_label_drift_test.py
  tests/vision/vision_conftest.py
Labels: bugfix

#897 Vision model comparison
  deepchecks/vision/checks/performance/__init__.py
  deepchecks/vision/checks/performance/class_performance.py
  deepchecks/vision/checks/performance/simple_model_comparison.py
  deepchecks/vision/metrics_utils/metrics.py
  docs/source/examples/vision/checks/performance/simple_model_comparison.ipynb
  tests/vision/checks/performance/cv_simple_model_comparison_test.py
Labels: feature

#905 Save mnist model for tests
  deepchecks/vision/datasets/classification/mnist.py
  tests/vision/checks/performance/robustness_report_test.py
  tests/vision/models/mnist.pth
  tests/vision/vision_conftest.py
Labels: bugfix

#904 Set seed in vision context and fix YOLO tests
  deepchecks/vision/base.py
  deepchecks/vision/checks/distribution/image_dataset_drift.py
  deepchecks/vision/checks/performance/robustness_report.py
  deepchecks/vision/datasets/detection/coco.py
  deepchecks/vision/metrics_utils/metrics.py
  deepchecks/vision/utils/validation.py
  tests/vision/checks/distribution/image_dataset_drift_test.py
  tests/vision/checks/distribution/train_test_label_drift_test.py
  tests/vision/checks/performance/class_performance_test.py
  tests/vision/checks/performance/mean_average_precision_report_test.py
  tests/vision/checks/performance/mean_average_recall_report_test.py
  tests/vision/checks/performance/robustness_report_test.py
  tests/vision/utils_tests/metrics_test.py
Labels: bugfix

#882 [Issue 834] label formatters
  deepchecks/vision/dataset.py
  deepchecks/vision/utils/detection_formatters.py
  docs/source/user-guide/vision/formatter_objects.rst
  tests/vision/utils_tests/formatters_test.py
Labels: feature

#907 Changing alternative_metrics to Dict
  deepchecks/vision/checks/performance/class_performance.py
  deepchecks/vision/checks/performance/robustness_report.py
  deepchecks/vision/checks/performance/simple_model_comparison.py
  deepchecks/vision/metrics_utils/metrics.py
  tests/vision/utils_tests/metrics_test.py
Labels: bugfix

#909 set default prediction formatters
  deepchecks/vision/base.py
  tests/vision/base/test_context.py
  tests/vision/checks/performance/mean_average_precision_report_test.py
  tests/vision/checks/performance/mean_average_recall_report_test.py
Labels: refactoring

#900 The notebook is back
  deepchecks/core/check_utils/whole_dataset_drift_utils.py
  deepchecks/tabular/checks/distribution/whole_dataset_drift.py
  deepchecks/vision/checks/distribution/image_dataset_drift.py
  docs/source/examples/vision/checks/distribution/image_dataset_drift.ipynb
Labels: bugfix

#924 Robustness + VisionData: copy generator when copying dataset
  deepchecks/vision/dataset.py
  tests/vision/checks/performance/robustness_report_test.py
Labels: bugfix

#926 Remove state copying and setting seed in robustness_report
  deepchecks/vision/checks/performance/robustness_report.py
  deepchecks/vision/dataset.py
  tests/vision/checks/performance/robustness_report_test.py
Labels: bugfix

#901 Heatmap comp
  deepchecks/vision/checks/distribution/__init__.py
  deepchecks/vision/checks/distribution/heatmap_comparison.py
  deepchecks/vision/checks/performance/robustness_report.py
  deepchecks/vision/dataset.py
  deepchecks/vision/utils/image_functions.py
  deepchecks/vision/utils/validation.py
  docs/source/examples/vision/checks/distribution/heatmap_comparison.ipynb
  tests/vision/base/test_vision_data.py
  tests/vision/checks/distribution/heatmap_comparison_test.py
Labels: feature

#828 add confusion matrix
  deepchecks/vision/checks/__init__.py
  deepchecks/vision/checks/performance/__init__.py
  deepchecks/vision/checks/performance/confusion_matrix.py
  deepchecks/vision/metrics_utils/detection_precision_recall.py
  deepchecks/vision/metrics_utils/iou_utils.py
  docs/source/examples/vision/checks/performance/confusion_martix.ipynb
  tests/vision/checks/performance/confusion_matrix_test.py
Labels: feature

#927 version bump
  VERSION
Labels: ci

#906 Wandb integration
  .github/workflows/build.yml
  deepchecks/core/check.py
  deepchecks/core/condition.py
  deepchecks/core/display_pandas.py
  deepchecks/core/suite.py
  deepchecks/utils/strings.py
  deepchecks/utils/wandb_utils.py
  docs/source/examples/general/export_outputs_to_wandb.ipynb
  docs/source/examples/tabular/guides/add_a_custom_check.ipynb
  makefile
  requirements/dev-requirements.txt
  tests/base/check_test.py
  tests/base/to_wandb_test.py
  tests/conftest.py
Labels: feature
