Repository deepchecks/deepchecks, pull requests merged in 2022-12, with the labels that each got.

#2180 Fix debugpy license check
  .github/workflows/build.yml
Labels: ci

#2178 fixing test-windows
  .github/workflows/build.yml
  makefile
  tests/vision/docs/test_plots.py
  tests/vision/utils_tests/formatters_test.py
Labels: ci

#2163 Fix cat segmentation
  deepchecks/tabular/dataset.py
  deepchecks/utils/dataframes.py
  deepchecks/utils/performance/weak_segment_abstract.py
  spelling-allowlist.txt
  tests/common.py
  tests/tabular/checks/model_evaluation/weak_segments_performance_test.py
Labels: bug

#2183 Update all contributors badge
  .all-contributorsrc
Labels: ci

#2159 Created junit serialization capability
  deepchecks/core/check_result.py
  deepchecks/core/serialization/abc.py
  deepchecks/core/serialization/check_failure/junit.py
  deepchecks/core/serialization/check_result/junit.py
  deepchecks/core/serialization/suite_result/junit.py
  deepchecks/tabular/suite.py
  docs/source/user-guide/integrations/junit.rst
  tests/serialization/test_check_failure_serialization.py
  tests/serialization/test_check_result_serialization.py
  tests/serialization/test_suite_result_serialization.py
Labels: feature

#2191 Minor import and typo fixes
  .github/workflows/build.yml
  deepchecks/vision/checks/train_test_validation/new_labels.py
  docs/source/checks/vision/train_test_validation/plot_new_labels.py
Labels: bug

#2186 feature_aggregation_method_argument is shared, so it shouldn't say drift
  deepchecks/core/check_utils/multivariate_drift_utils.py
  deepchecks/tabular/_shared_docs.py
Labels: documentation, bug

#2146 Added model_classes
  deepchecks/nlp/base_checks.py
  deepchecks/nlp/checks/model_evaluation/single_dataset_performance.py
  deepchecks/nlp/checks/train_test_validation/keyword_frequency_drift.py
  deepchecks/nlp/context.py
  deepchecks/nlp/metric_utils/scorers.py
  deepchecks/nlp/metric_utils/token_classification.py
  deepchecks/nlp/text_data.py
  deepchecks/nlp/utils/data_inference.py
  deepchecks/tabular/metric_utils/scorers.py
  deepchecks/tabular/utils/validation.py
  deepchecks/utils/docref.py
  docs/source/user-guide/nlp/supported_tasks.rst
  requirements/dev-requirements.txt
  spelling-allowlist.txt
  tests/nlp/checks/model_evaluation/single_dataset_performance_nlp_test.py
  tests/nlp/test_suites.py
  tests/tabular/test_dummy_model.py
Labels: feature, nlp

#2215 Fixing errors from new numpy version
  deepchecks/tabular/checks/model_evaluation/segment_performance.py
  deepchecks/utils/performance/weak_segment_abstract.py
  deepchecks/vision/checks/data_integrity/abstract_property_outliers.py
  requirements/requirements.txt
  tests/conftest.py
Labels: bug

#2205 Changed token classification format to IOB
  deepchecks/nlp/checks/model_evaluation/single_dataset_performance.py
  deepchecks/nlp/context.py
  deepchecks/nlp/metric_utils/scorers.py
  deepchecks/nlp/metric_utils/token_classification.py
  deepchecks/nlp/text_data.py
  deepchecks/nlp/utils/data_inference.py
  requirements/dev-requirements.txt
  tests/nlp/checks/model_evaluation/single_dataset_performance_nlp_test.py
  tests/nlp/nlp_conftest.py
  tests/nlp/test_context.py
  tests/nlp/test_text_data.py
Labels: refactoring

#2204 Using also y_pred to infer task type
  deepchecks/tabular/context.py
  deepchecks/tabular/utils/task_inference.py
  tests/tabular/suites/test_suites.py
  tests/tabular/test_dummy_model.py
  tests/tabular/test_tabular_context.py
Labels: bug

#2220 Download yolo pretrained from figshare
  deepchecks/vision/datasets/detection/coco.py
Labels: refactoring

#2207 Fix various warnings
  deepchecks/tabular/datasets/classification/iris.py
  deepchecks/utils/plot.py
  deepchecks/vision/checks/data_integrity/abstract_property_outliers.py
  deepchecks/vision/metrics_utils/confusion_matrix_counts_metrics.py
  docs/source/checks/tabular/train_test_validation/plot_new_label_train_test.py
  requirements/requirements.txt
  tests/base/dataset_test.py
  tests/base/to_wandb_test.py
  tests/tabular/checks/integrity/class_imbalance_test.py
  tests/tabular/checks/train_test_validation/new_label_test.py
  tests/tabular/test_dummy_model.py
  tests/vision/base/test_vision_data.py
  tests/vision/checks/model_evaluation/class_performance_test.py
  tests/vision/checks/model_evaluation/single_dataset_performance_test.py
Labels: bug

#2222 Small fixes to nlp
  deepchecks/nlp/checks/train_test_validation/keyword_frequency_drift.py
  deepchecks/nlp/context.py
  deepchecks/nlp/text_data.py
  tests/nlp/checks/train_test_validation/keyword_frequency_drift_test.py
Labels: bug

#2223 fix problems with missing classes
  deepchecks/tabular/checks/model_evaluation/single_dataset_performance.py
  deepchecks/tabular/metric_utils/additional_classification_metrics.py
  deepchecks/tabular/metric_utils/scorers.py
  deepchecks/vision/datasets/detection/coco.py
  tests/conftest.py
  tests/tabular/checks/model_evaluation/single_dataset_performance_test.py
  tests/tabular/suites/test_suites.py
Labels: bug

#2224 torch hub coco - skip github validation
  deepchecks/vision/datasets/detection/coco.py
Labels: bug

#2230 Add explicit error message for binary scorers
  deepchecks/tabular/metric_utils/scorers.py
Labels: bug

#2236 simple model scorers to accept averaged scorers
  deepchecks/tabular/checks/model_evaluation/simple_model_comparison.py
  tests/tabular/checks/model_evaluation/simple_model_comparison_test.py
Labels: bug
