Repository deepchecks/deepchecks, pull requests merged in 2022-03, with the labels that each got.

#939 Adding gpu tests
  .github/workflows/build.yml
  deepchecks/vision/metrics_utils/detection_precision_recall.py
  deepchecks/vision/utils/transformations.py
  makefile
  tests/vision/base/test_context.py
  tests/vision/checks/distribution/heatmap_comparison_test.py
  tests/vision/checks/distribution/image_dataset_drift_test.py
  tests/vision/checks/distribution/image_properties_drift_test.py
  tests/vision/checks/distribution/train_test_label_drift_test.py
  tests/vision/checks/performance/class_performance_test.py
  tests/vision/checks/performance/confusion_matrix_test.py
  tests/vision/checks/performance/cv_simple_model_comparison_test.py
  tests/vision/checks/performance/mean_average_precision_report_test.py
  tests/vision/checks/performance/mean_average_recall_report_test.py
  tests/vision/checks/performance/robustness_report_test.py
  tests/vision/utils_tests/metrics_test.py
  tests/vision/vision_conftest.py
Labels: ci

#936 Adding explanations to label drift notebook.
  docs/source/examples/vision/checks/distribution/train_test_label_drift.ipynb
Labels: documentation, feature

#959 Added ask classes
  deepchecks/vision/classification_task.py
  deepchecks/vision/dataset.py
  deepchecks/vision/detection_task.py
  deepchecks/vision/vision_task.py
  tests/vision/base/test_vision_data.py
Labels: feature

#956 Add latest version check to package init
  deepchecks/__init__.py
Labels: feature

#960 Context refactor
  deepchecks/vision/base.py
  deepchecks/vision/classification_data.py
  deepchecks/vision/utils/image_formatters.py
  deepchecks/vision/vision_data.py
Labels: feature

#961 removed_base_formatter
  deepchecks/vision/base.py
  deepchecks/vision/metrics_utils/metrics.py
  deepchecks/vision/utils/__init__.py
  deepchecks/vision/utils/base_formatters.py
  deepchecks/vision/utils/classification_formatters.py
  deepchecks/vision/utils/detection_formatters.py
  deepchecks/vision/utils/validation.py
Labels: feature

#965 Refactoring
  deepchecks/vision/__init__.py
  deepchecks/vision/base.py
  deepchecks/vision/checks/distribution/image_dataset_drift.py
  deepchecks/vision/checks/distribution/image_property_drift.py
  deepchecks/vision/checks/distribution/train_test_label_drift.py
  deepchecks/vision/checks/performance/class_performance.py
  deepchecks/vision/checks/performance/confusion_matrix.py
  deepchecks/vision/checks/performance/image_segment_performance.py
  deepchecks/vision/checks/performance/mean_average_precision_report.py
  deepchecks/vision/checks/performance/mean_average_recall_report.py
  deepchecks/vision/checks/performance/robustness_report.py
  deepchecks/vision/checks/performance/simple_model_comparison.py
  deepchecks/vision/classification_data.py
  deepchecks/vision/dataset.py
  deepchecks/vision/datasets/classification/mnist.py
  deepchecks/vision/datasets/detection/coco.py
  deepchecks/vision/detection_data.py
  deepchecks/vision/vision_data.py
  tests/vision/base/test_context.py
  tests/vision/checks/performance/class_performance_test.py
  tests/vision/checks/performance/confusion_matrix_test.py
  tests/vision/checks/performance/cv_simple_model_comparison_test.py
  tests/vision/checks/performance/image_segment_performance_test.py
  tests/vision/checks/performance/mean_average_precision_report_test.py
  tests/vision/checks/performance/mean_average_recall_report_test.py
  tests/vision/checks/performance/robustness_report_test.py
  tests/vision/utils_tests/metrics_test.py
  tests/vision/utils_tests/mnist_imgaug.py
Labels: feature

#977 Fix order of results in vision suite
  deepchecks/vision/base.py
  deepchecks/vision/checks/__init__.py
Labels: bugfix

#980 Fix inverted confusion matrix axis
  deepchecks/vision/checks/performance/confusion_matrix.py
  docs/source/examples/vision/checks/performance/confusion_matrix.ipynb
Labels: bugfix

#981 Fixing heatmap_comparison.py
  deepchecks/vision/checks/distribution/heatmap_comparison.py
  deepchecks/vision/vision_data.py
Labels: bugfix

#983 Confusion matrix bug
  deepchecks/vision/checks/performance/confusion_matrix.py
  docs/source/examples/vision/checks/performance/confusion_matrix.ipynb
  tests/vision/checks/performance/confusion_matrix_test.py
Labels: bugfix

#986 Update validate image data error message
  deepchecks/vision/vision_data.py
  tests/vision/utils_tests/formatters_test.py
Labels: bugfix

#984 Add progress bars to vision suite run
  deepchecks/core/display_suite.py
  deepchecks/core/suite.py
  deepchecks/tabular/base.py
  deepchecks/vision/base.py
Labels: feature

#992 Cv2 unit8
  deepchecks/vision/checks/distribution/heatmap_comparison.py
  docs/source/user-guide/vision/classification_tutorial.rst
Labels: bugfix

#978 Dc 941 test load dataset use downloaded dataset
  deepchecks/vision/datasets/detection/coco.py
  tests/vision/datasets/test_coco.py
Labels: bugfix

#989 Simple feature contribution issue 842
  deepchecks/core/check_utils/single_feature_contribution_utils.py
  deepchecks/tabular/checks/methodology/single_feature_contribution_train_test.py
  deepchecks/vision/checks/__init__.py
  deepchecks/vision/checks/distribution/image_dataset_drift.py
  deepchecks/vision/checks/distribution/image_property_drift.py
  deepchecks/vision/checks/methodology/__init__.py
  deepchecks/vision/checks/methodology/simple_feature_contribution.py
  deepchecks/vision/checks/performance/image_segment_performance.py
  deepchecks/vision/suites/default_suites.py
  deepchecks/vision/utils/image_formatters.py
  deepchecks/vision/utils/image_functions.py
  docs/source/examples/vision/checks/methodology/simple_feature_contribution.ipynb
  tests/vision/checks/distribution/image_dataset_drift_test.py
  tests/vision/checks/distribution/image_properties_drift_test.py
  tests/vision/checks/distribution/simple_feature_contribution_test.py
  tests/vision/utils_tests/formatters_test.py
Labels: feature

#1001 0.6.0.dev0
  DESCRIPTION.rst
  MANIFEST.in
  VERSION
Labels: ci

#1003 fix errors in classification tutorial
  docs/source/user-guide/vision/classification_tutorial.rst
Labels: bugfix

#1007 Some condition changes
  deepchecks/core/check_result.py
  deepchecks/vision/checks/performance/mean_average_precision_report.py
  deepchecks/vision/suites/default_suites.py
  tests/vision/checks/performance/mean_average_precision_report_test.py
Labels: feature

#999 label and predictions should be tensors
  deepchecks/vision/classification_data.py
  deepchecks/vision/detection_data.py
  tests/vision/base/test_vision_data.py
Labels: bugfix

#991 Add sample option to vision
  deepchecks/core/errors.py
  deepchecks/vision/checks/distribution/train_test_label_drift.py
  deepchecks/vision/context.py
  deepchecks/vision/vision_data.py
  tests/vision/base/test_context.py
  tests/vision/base/test_vision_data.py
  tests/vision/checks/distribution/heatmap_comparison_test.py
  tests/vision/checks/distribution/image_dataset_drift_test.py
  tests/vision/checks/distribution/simple_feature_contribution_test.py
  tests/vision/checks/performance/robustness_report_test.py
  tests/vision/core/vision_data_test.py
Labels: feature

#1008 Fixing RTD badge
  README.rst
Labels: documentation

#1013 Refactor image & label & prediction properties
  deepchecks/core/check_utils/whole_dataset_drift_utils.py
  deepchecks/utils/performance/error_model.py
  deepchecks/vision/checks/distribution/image_dataset_drift.py
  deepchecks/vision/checks/distribution/image_property_drift.py
  deepchecks/vision/checks/distribution/train_test_label_drift.py
  deepchecks/vision/checks/distribution/train_test_prediction_drift.py
  deepchecks/vision/checks/methodology/simple_feature_contribution.py
  deepchecks/vision/checks/performance/image_segment_performance.py
  deepchecks/vision/checks/performance/model_error_analysis.py
  deepchecks/vision/utils/image_formatters.py
  deepchecks/vision/utils/image_properties.py
  deepchecks/vision/utils/label_prediction_properties.py
  deepchecks/vision/utils/measurements.py
  docs/source/examples/vision/checks/performance/image_segment_performance.ipynb
  tests/vision/checks/distribution/image_dataset_drift_test.py
  tests/vision/checks/distribution/image_properties_drift_test.py
  tests/vision/checks/distribution/simple_feature_contribution_test.py
  tests/vision/checks/distribution/train_test_label_drift_test.py
  tests/vision/checks/distribution/train_test_prediction_drift_test.py
  tests/vision/checks/performance/image_segment_performance_test.py
  tests/vision/checks/performance/vision_model_error_analysis_test.py
  tests/vision/utils_tests/formatters_test.py
Labels: refactoring

#1027 refactor _evaluate_image to improve performance
  deepchecks/vision/metrics_utils/detection_precision_recall.py
Labels: bugfix

#1029 [Issue 985] Confusion matrix report - unseen classes bug fix
  deepchecks/vision/checks/performance/confusion_matrix.py
  docs/source/examples/vision/checks/performance/confusion_matrix.ipynb
  spelling-allowlist.txt
  tests/vision/checks/performance/confusion_matrix_test.py
Labels: bugfix

#1035 deepchecks label to wandb runs
  deepchecks/utils/wandb_utils.py
Labels: feature

#1037 Add "other" task type
  deepchecks/vision/vision_data.py
  tests/vision/base/test_vision_data.py
Labels: refactoring

#1044 Update Readme.rst
  README.rst
Labels: documentation

#1036 Class performance alt metrics fix
  deepchecks/vision/checks/performance/class_performance.py
  deepchecks/vision/checks/performance/mean_average_precision_report.py
  deepchecks/vision/checks/performance/robustness_report.py
  deepchecks/vision/metrics_utils/detection_precision_recall.py
  deepchecks/vision/metrics_utils/metrics.py
  docs/source/examples/vision/checks/performance/class_performance.ipynb
  tests/vision/checks/performance/class_performance_test.py
  tests/vision/checks/performance/robustness_report_test.py
  tests/vision/utils_tests/metrics_test.py
Labels: bugfix

#1026 Add properties user guide
  deepchecks/vision/checks/distribution/image_property_drift.py
  deepchecks/vision/utils/image_properties.py
  deepchecks/vision/vision_data.py
  docs/source/user-guide/vision/index.rst
  docs/source/user-guide/vision/vision_properties.rst
Labels: documentation

#1050 Raise an error if model is in training mode when passed to check
  deepchecks/vision/context.py
  tests/vision/base/test_context.py
Labels: bugfix

#1038 Visiondata docs
  deepchecks/vision/vision_data.py
  docs/source/_static/tomatoes.png
  docs/source/index.rst
  docs/source/tutorials/vision/classification_tutorial.rst
  docs/source/tutorials/vision/detection_tutorial.rst
  docs/source/tutorials/vision/index.rst
  docs/source/user-guide/index.rst
  docs/source/user-guide/vision/data-classes/ClassificationData.rst
  docs/source/user-guide/vision/data-classes/DetectionData.rst
  docs/source/user-guide/vision/data-classes/VisionData.rst
  docs/source/user-guide/vision/data-classes/index.rst
  docs/source/user-guide/vision/formatter_objects.rst
  docs/source/user-guide/vision/index.rst
  tests/vision/base/test_vision_data.py
Labels: documentation

#1063 Revert "Visiondata docs"
  deepchecks/vision/vision_data.py
  docs/source/_static/tomatoes.png
  docs/source/index.rst
  docs/source/tutorials/vision/classification_tutorial.rst
  docs/source/tutorials/vision/detection_tutorial.rst
  docs/source/tutorials/vision/index.rst
  docs/source/user-guide/index.rst
  docs/source/user-guide/vision/data-classes/ClassificationData.rst
  docs/source/user-guide/vision/data-classes/DetectionData.rst
  docs/source/user-guide/vision/data-classes/VisionData.rst
  docs/source/user-guide/vision/data-classes/index.rst
  docs/source/user-guide/vision/formatter_objects.rst
  docs/source/user-guide/vision/index.rst
  tests/vision/base/test_vision_data.py
Labels: bug, bugfix

#1047 Custom vision check
  deepchecks/vision/context.py
  deepchecks/vision/metrics_utils/detection_precision_recall.py
  docs/source/tutorials/vision/custom_checks.py
Labels: documentation

#1060 Automatic deployment of docs to github pages
  .github/scripts/push_docs.sh
  .github/workflows/docs.yaml
Labels: documentation

#1045 [issue-1005] SimpleClasifficationDataset
  deepchecks/vision/datasets/classification/__init__.py
  deepchecks/vision/datasets/classification/simple.py
  tests/vision/datasets/test_simple.py
Labels: feature

#1065 Visiondata docs
  deepchecks/vision/vision_data.py
  docs/source/_static/tomatoes.png
  docs/source/index.rst
  docs/source/tutorials/vision/classification_tutorial.rst
  docs/source/tutorials/vision/detection_tutorial.rst
  docs/source/tutorials/vision/index.rst
  docs/source/user-guide/index.rst
  docs/source/user-guide/vision/data-classes/ClassificationData.rst
  docs/source/user-guide/vision/data-classes/DetectionData.rst
  docs/source/user-guide/vision/data-classes/VisionData.rst
  docs/source/user-guide/vision/data-classes/index.rst
  docs/source/user-guide/vision/formatter_objects.rst
  docs/source/user-guide/vision/index.rst
Labels: documentation

#1068 Fixing deprecation warning while importing deepchecks
  deepchecks/core/check_utils/whole_dataset_drift_utils.py
  deepchecks/tabular/dataset.py
  deepchecks/vision/checks/distribution/train_test_label_drift.py
  tests/base/display_test.py
Labels: bugfix

#1070 add classes_to_display to property drift
  deepchecks/vision/checks/distribution/image_property_drift.py
  tests/vision/checks/distribution/image_properties_drift_test.py
Labels: feature

#1049 add test to vision base
  tests/vision/base/test_base_checks.py
  tests/vision/base/test_context.py
  tests/vision/base/test_suite.py
  tests/vision/base/test_vision_data.py
Labels: tests

#1059 some_visual_improvments
  deepchecks/vision/checks/distribution/heatmap_comparison.py
  deepchecks/vision/checks/performance/class_performance.py
  deepchecks/vision/checks/performance/mean_average_precision_report.py
  deepchecks/vision/checks/performance/simple_model_comparison.py
  deepchecks/vision/metrics_utils/metrics.py
Labels: feature

#1034 Check display validation
  deepchecks/core/display_suite.py
  deepchecks/utils/ipython.py
  deepchecks/utils/strings.py
  deepchecks/vision/utils/validation.py
  tests/vision/utils_tests/validation_test.py
Labels: feature

#1073 change x axis name to column name instead of value in drift graphs
  deepchecks/core/check_utils/whole_dataset_drift_utils.py
  deepchecks/tabular/checks/distribution/train_test_feature_drift.py
  deepchecks/tabular/checks/distribution/train_test_label_drift.py
  deepchecks/tabular/checks/distribution/trust_score_comparison.py
  deepchecks/utils/distribution/drift.py
  deepchecks/utils/distribution/plot.py
  deepchecks/vision/checks/distribution/image_property_drift.py
  deepchecks/vision/checks/distribution/train_test_label_drift.py
  deepchecks/vision/checks/distribution/train_test_prediction_drift.py
Labels: documentation

#1072 Simple feature per class 1004
  deepchecks/core/check_utils/single_feature_contribution_utils.py
  deepchecks/vision/checks/methodology/simple_feature_contribution.py
  tests/vision/checks/distribution/simple_feature_contribution_test.py
Labels: feature

#1075 docs version selector fix
  .github/workflows/docs.yaml
  docs/source/_static/switcher.json
  docs/source/conf.py
Labels: documentation

#1078 Suggestion: Add assert in vision objects to Batch
  deepchecks/vision/checks/distribution/image_property_drift.py
  deepchecks/vision/context.py
  deepchecks/vision/detection_data.py
  deepchecks/vision/utils/validation.py
  deepchecks/vision/vision_data.py
  tests/vision/base/test_custom_task.py
  tests/vision/base/test_vision_data.py
Labels: refactoring

#1079 Updating docs main page for vision
  docs/source/index.rst
Labels: documentation

#1082 [Issue-667] added **kwargs to all checks __init__
  deepchecks/core/checks.py
  deepchecks/tabular/base_checks.py
  deepchecks/tabular/checks/distribution/train_test_feature_drift.py
  deepchecks/tabular/checks/distribution/train_test_label_drift.py
  deepchecks/tabular/checks/distribution/trust_score_comparison.py
  deepchecks/tabular/checks/distribution/whole_dataset_drift.py
  deepchecks/tabular/checks/integrity/data_duplicates.py
  deepchecks/tabular/checks/integrity/dominant_frequency_change.py
  deepchecks/tabular/checks/integrity/is_single_value.py
  deepchecks/tabular/checks/integrity/label_ambiguity.py
  deepchecks/tabular/checks/integrity/mixed_data_types.py
  deepchecks/tabular/checks/integrity/mixed_nulls.py
  deepchecks/tabular/checks/integrity/new_category.py
  deepchecks/tabular/checks/integrity/special_chars.py
  deepchecks/tabular/checks/integrity/string_length_out_of_bounds.py
  deepchecks/tabular/checks/integrity/string_mismatch.py
  deepchecks/tabular/checks/integrity/string_mismatch_comparison.py
  deepchecks/tabular/checks/methodology/boosting_overfit.py
  deepchecks/tabular/checks/methodology/date_train_test_leakage_duplicates.py
  deepchecks/tabular/checks/methodology/identifier_leakage.py
  deepchecks/tabular/checks/methodology/index_leakage.py
  deepchecks/tabular/checks/methodology/model_inference_time.py
  deepchecks/tabular/checks/methodology/single_feature_contribution.py
  deepchecks/tabular/checks/methodology/single_feature_contribution_train_test.py
  deepchecks/tabular/checks/methodology/unused_features.py
  deepchecks/tabular/checks/overview/columns_info.py
  deepchecks/tabular/checks/performance/model_error_analysis.py
  deepchecks/tabular/checks/performance/performance_report.py
  deepchecks/tabular/checks/performance/regression_error_distribution.py
  deepchecks/tabular/checks/performance/roc_report.py
  deepchecks/tabular/checks/performance/segment_performance.py
  deepchecks/tabular/checks/performance/simple_model_comparison.py
  deepchecks/vision/checks/distribution/image_dataset_drift.py
  deepchecks/vision/checks/distribution/image_property_drift.py
  deepchecks/vision/checks/distribution/train_test_label_drift.py
  deepchecks/vision/checks/distribution/train_test_prediction_drift.py
  deepchecks/vision/checks/methodology/simple_feature_contribution.py
  deepchecks/vision/checks/performance/class_performance.py
  deepchecks/vision/checks/performance/confusion_matrix.py
  deepchecks/vision/checks/performance/image_segment_performance.py
  deepchecks/vision/checks/performance/mean_average_precision_report.py
  deepchecks/vision/checks/performance/mean_average_recall_report.py
  deepchecks/vision/checks/performance/model_error_analysis.py
  deepchecks/vision/checks/performance/robustness_report.py
  deepchecks/vision/checks/performance/simple_model_comparison.py
Labels: feature

#1092 fix display bug
  deepchecks/core/display_suite.py
  deepchecks/core/suite.py
  requirements/requirements.txt
Labels: bugfix

#1091 Refactor for labels & image outlier
  deepchecks/core/errors.py
  deepchecks/utils/strings.py
  deepchecks/vision/__init__.py
  deepchecks/vision/base_checks.py
  deepchecks/vision/batch_wrapper.py
  deepchecks/vision/checks/distribution/train_test_label_drift.py
  deepchecks/vision/checks/distribution/train_test_prediction_drift.py
  deepchecks/vision/context.py
  deepchecks/vision/suite.py
  deepchecks/vision/utils/label_prediction_properties.py
  deepchecks/vision/utils/validation.py
  deepchecks/vision/vision_data.py
  docs/source/tutorials/vision/plot_custom_checks.py
  docs/source/user-guide/vision/vision_properties.rst
  tests/vision/base/test_base_checks.py
  tests/vision/base/test_vision_data.py
  tests/vision/checks/distribution/image_property_drift_test.py
  tests/vision/vision_conftest.py
Labels: refactoring

#1090 Update main docs page
  docs/source/index.rst
Labels: documentation

#1094 adding code owners
  .github/CODEOWNERS
  .licenserc_fix.yaml
Labels: ci

#1087 add test to conditions in class performance check
  deepchecks/vision/checks/performance/class_performance.py
  tests/vision/checks/performance/class_performance_test.py
Labels: feature

#1098 add example of limiting classes to display
  docs/source/examples/vision/checks/distribution/source/plot_image_property_check.py
Labels: documentation

#1099 Rst to gallery
  .github/workflows/build.yml
  .gitignore
  deepchecks/vision/datasets/detection/coco.py
  docs/source/examples/index.rst
  docs/source/examples/tabular/checks/distribution/source/plot_trust_score_comparison.py
  docs/source/examples/tabular/checks/distribution/source/plot_whole_dataset_drift.py
  docs/source/examples/tabular/checks/index.rst
  docs/source/examples/vision/checks/distribution/source/plot_heatmap_comparison.py
  docs/source/examples/vision/checks/index.rst
  docs/source/tutorials/index.rst
  docs/source/tutorials/tabular/plot_add_a_custom_check.py
  docs/source/tutorials/tabular/plot_quickstart_in_5_minutes.py
  docs/source/tutorials/vision/README.rst
  docs/source/tutorials/vision/classification_tutorial.rst
  docs/source/tutorials/vision/detection_tutorial.rst
  docs/source/tutorials/vision/index.rst
  docs/source/tutorials/vision/plot_classification_tutorial.py
  docs/source/tutorials/vision/plot_detetection_tutorial.py
Labels: documentation

#1100 Json cond fix + condition refactor
  deepchecks/core/check_result.py
  deepchecks/core/checks.py
  deepchecks/core/condition.py
  deepchecks/core/display_pandas.py
  deepchecks/tabular/checks/distribution/train_test_feature_drift.py
  deepchecks/tabular/checks/distribution/train_test_label_drift.py
  deepchecks/tabular/checks/distribution/trust_score_comparison.py
  deepchecks/tabular/checks/distribution/whole_dataset_drift.py
  deepchecks/tabular/checks/integrity/data_duplicates.py
  deepchecks/tabular/checks/integrity/dominant_frequency_change.py
  deepchecks/tabular/checks/integrity/is_single_value.py
  deepchecks/tabular/checks/integrity/label_ambiguity.py
  deepchecks/tabular/checks/integrity/mixed_data_types.py
  deepchecks/tabular/checks/integrity/mixed_nulls.py
  deepchecks/tabular/checks/integrity/new_category.py
  deepchecks/tabular/checks/integrity/new_label.py
  deepchecks/tabular/checks/integrity/special_chars.py
  deepchecks/tabular/checks/integrity/string_length_out_of_bounds.py
  deepchecks/tabular/checks/integrity/string_mismatch.py
  deepchecks/tabular/checks/integrity/string_mismatch_comparison.py
  deepchecks/tabular/checks/methodology/boosting_overfit.py
  deepchecks/tabular/checks/methodology/datasets_size_comparison.py
  deepchecks/tabular/checks/methodology/date_train_test_leakage_duplicates.py
  deepchecks/tabular/checks/methodology/date_train_test_leakage_overlap.py
  deepchecks/tabular/checks/methodology/identifier_leakage.py
  deepchecks/tabular/checks/methodology/index_leakage.py
  deepchecks/tabular/checks/methodology/model_inference_time.py
  deepchecks/tabular/checks/methodology/single_feature_contribution.py
  deepchecks/tabular/checks/methodology/single_feature_contribution_train_test.py
  deepchecks/tabular/checks/methodology/train_test_samples_mix.py
  deepchecks/tabular/checks/methodology/unused_features.py
  deepchecks/tabular/checks/performance/model_error_analysis.py
  deepchecks/tabular/checks/performance/performance_report.py
  deepchecks/tabular/checks/performance/regression_error_distribution.py
  deepchecks/tabular/checks/performance/regression_systematic_error.py
  deepchecks/tabular/checks/performance/roc_report.py
  deepchecks/tabular/checks/performance/simple_model_comparison.py
  deepchecks/vision/checks/distribution/image_property_drift.py
  deepchecks/vision/checks/distribution/train_test_label_drift.py
  deepchecks/vision/checks/distribution/train_test_prediction_drift.py
  deepchecks/vision/checks/methodology/simple_feature_contribution.py
  deepchecks/vision/checks/performance/class_performance.py
  deepchecks/vision/checks/performance/image_segment_performance.py
  deepchecks/vision/checks/performance/mean_average_precision_report.py
  deepchecks/vision/checks/performance/mean_average_recall_report.py
  deepchecks/vision/checks/performance/robustness_report.py
  docs/source/tutorials/vision/plot_custom_checks.py
  docs/source/user-guide/general/customizations/plot_configure_check_conditions.py
  spelling-allowlist.txt
  tests/base/check_test.py
  tests/base/to_json_test.py
  tests/checks/distribution/train_test_label_drift_test.py
  tests/checks/methodology/datasets_size_comparison_test.py
  tests/checks/methodology/model_inference_time_test.py
  tests/checks/performance/model_error_analysis_test.py
  tests/checks/utils.py
Labels: bugfix

#1101 removed model randomness from the quick start guide
  .gitignore
  docs/source/tutorials/tabular/plot_quickstart_in_5_minutes.py
Labels: bugfix

#1089 Adding condition to CV simple model comparison
  .github/workflows/build.yml
  deepchecks/vision/checks/performance/simple_model_comparison.py
  tests/vision/checks/performance/cv_simple_model_comparison_test.py
Labels: feature

#1106 condition order fix
  .github/workflows/build.yml
  deepchecks/core/display_pandas.py
  deepchecks/utils/typing.py
Labels: bugfix

#1085 Model error visualization fix
  deepchecks/core/check_result.py
  deepchecks/tabular/checks/performance/model_error_analysis.py
  deepchecks/utils/performance/error_model.py
  deepchecks/utils/single_sample_metrics.py
  deepchecks/vision/checks/performance/model_error_analysis.py
  docs/source/examples/tabular/use-cases/source/plot_phishing_urls.py
  docs/source/user-guide/general/exporting_results/plot_export_outputs_to_json.py
  docs/source/user-guide/general/exporting_results/plot_exports_output_to_wandb.py
  spelling-allowlist.txt
  tests/checks/performance/model_error_analysis_test.py
  tests/vision/checks/performance/vision_model_error_analysis_test.py
Labels: bugfix

#1111 remove accidental code
  deepchecks/core/check_result.py
Labels: bugfix

#1093 fix docstring
  deepchecks/tabular/checks/integrity/new_category.py
  deepchecks/tabular/datasets/classification/breast_cancer.py
  deepchecks/tabular/datasets/classification/iris.py
  deepchecks/vision/datasets/classification/simple.py
  deepchecks/vision/datasets/detection/coco.py
Labels: documentation

#1110 fixed TOC, thumbnails, plots and search
  docs/source/_static/css/custom.css
  docs/source/_templates/layout.html
  docs/source/_templates/search-field.html
  docs/source/conf.py
  docs/source/examples/general/index.rst
  docs/source/examples/general/source/README.rst
  docs/source/examples/tabular/guides/index.rst
  docs/source/examples/tabular/guides/source/README.rst
  docs/source/examples/tabular/guides/source/plot_add_a_custom_check.py
  docs/source/examples/tabular/guides/source/plot_quickstart_in_5_minutes.py
  docs/source/examples/tabular/use-cases/index.rst
  docs/source/examples/tabular/use-cases/source/README.rst
  docs/source/getting-started/index.rst
  docs/source/getting-started/when_should_you_use.rst
  docs/source/tutorials/index.rst
  docs/source/tutorials/tabular/README.rst
  docs/source/tutorials/tabular/plot_phishing_urls.py
  docs/source/tutorials/tabular/use-cases/README.rst
  docs/source/tutorials/tabular/use-cases/plot_phishing_urls.py
  docs/source/tutorials/vision/plot_classification_tutorial.py
  docs/source/tutorials/vision/plot_custom_checks.py
  docs/source/tutorials/vision/plot_custom_task_tutorial.py
  docs/source/tutorials/vision/plot_detetection_tutorial.py
  docs/source/user-guide/general/customizations/README.rst
  docs/source/user-guide/general/customizations/index.rst
  docs/source/user-guide/general/exporting_results/README.rst
  docs/source/user-guide/general/exporting_results/index.rst
  docs/source/user-guide/general/index.rst
  docs/source/user-guide/index.rst
  docs/source/user-guide/vision/index.rst
Labels: documentation

#1117 improve colors
  deepchecks/utils/plot.py
  deepchecks/vision/checks/performance/class_performance.py
  deepchecks/vision/checks/performance/image_segment_performance.py
  deepchecks/vision/checks/performance/robustness_report.py
  deepchecks/vision/checks/performance/simple_model_comparison.py
Labels: documentation

#1112 Adding the adult dataset to deepchecks.datasets
  deepchecks/tabular/datasets/classification/__init__.py
  deepchecks/tabular/datasets/classification/adult.py
  docs/source/examples/tabular/checks/distribution/source/plot_whole_dataset_drift.py
  docs/source/examples/tabular/checks/methodology/source/plot_boosting_overfit.py
  docs/source/examples/tabular/checks/methodology/source/plot_unused_features.py
  docs/source/examples/tabular/checks/performance/source/plot_calibration_score.py
  docs/source/examples/tabular/checks/performance/source/plot_model_error_analysis.py
  docs/source/examples/tabular/checks/performance/source/plot_segement_performance.py
Labels: feature

#1076 [issue-1056] updated setup.py
  setup.py
Labels: refactoring

#1103 fix read more url
  deepchecks/utils/strings.py
  tests/utils/test_string_utils.py
Labels: bugfix

#1121 Adding citation file
  .github/CODEOWNERS
  .licenserc_fix.yaml
  CITATION.cff
Labels: documentation

#1113 version selector is now working
  docs/source/_templates/layout.html
  docs/source/conf.py
  docs/source/user-guide/vision/data-classes/DetectionData.rst
Labels: bugfix

#1119 Add a tutorial of simple classification data
  deepchecks/vision/__init__.py
  deepchecks/vision/datasets/classification/__init__.py
  deepchecks/vision/simple_classification_data.py
  docs/source/tutorials/vision/plot_detection_tutorial.py
  docs/source/tutorials/vision/plot_simple_classification_tutorial.py
  tests/vision/datasets/test_simple.py
Labels: documentation

#1102 Image property outlier
  deepchecks/core/errors.py
  deepchecks/utils/distribution/drift.py
  deepchecks/utils/outliers.py
  deepchecks/vision/batch_wrapper.py
  deepchecks/vision/checks/__init__.py
  deepchecks/vision/checks/distribution/__init__.py
  deepchecks/vision/checks/distribution/image_property_drift.py
  deepchecks/vision/checks/distribution/image_property_outliers.py
  deepchecks/vision/vision_data.py
  docs/source/examples/vision/checks/distribution/source/plot_image_property_outliers.py
  docs/source/user-guide/vision/vision_properties.rst
  tests/utils/test_outliers.py
  tests/vision/base/test_vision_data.py
  tests/vision/checks/distribution/image_property_drift_test.py
  tests/vision/checks/distribution/image_property_outliers_test.py
  tests/vision/vision_conftest.py
Labels: feature, bugfix

#1114 make numerical type explicit + other edge case fixes
  deepchecks/tabular/checks/distribution/train_test_feature_drift.py
  deepchecks/tabular/checks/distribution/whole_dataset_drift.py
  deepchecks/tabular/checks/methodology/unused_features.py
  deepchecks/tabular/checks/performance/confusion_matrix_report.py
  deepchecks/tabular/checks/performance/model_error_analysis.py
  deepchecks/tabular/checks/performance/performance_report.py
  deepchecks/tabular/checks/performance/segment_performance.py
  deepchecks/tabular/checks/performance/simple_model_comparison.py
  deepchecks/tabular/dataset.py
  deepchecks/utils/features.py
  deepchecks/utils/performance/error_model.py
  deepchecks/utils/performance/partition.py
  docs/source/examples/tabular/checks/performance/source/plot_model_error_analysis.py
  spelling-allowlist.txt
  tests/checks/overview/columns_info_test.py
  tests/conftest.py
  tests/suites/test_suites.py
Labels: bugfix

#1105 add prediction drift to tabular
  deepchecks/checks.py
  deepchecks/tabular/checks/__init__.py
  deepchecks/tabular/checks/distribution/__init__.py
  deepchecks/tabular/checks/distribution/train_test_prediction_drift.py
  docs/source/examples/tabular/checks/distribution/source/plot_train_test_feature_drift.py
  docs/source/examples/tabular/checks/distribution/source/plot_train_test_prediction_drift.py
  docs/source/examples/vision/checks/distribution/source/plot_train_test_prediction_drift.py
  docs/source/examples/vision/checks/performance/source/plot_simple_model_comparison.py
  tests/checks/distribution/train_test_prediction_drift_test.py
  tests/checks/methodology/single_feature_contribution_test.py
  tests/vision/checks/distribution/simple_feature_contribution_test.py
  tests/vision/checks/performance/class_performance_test.py
Labels: feature

#1125 fixed broken links
  docs/source/examples/tabular/checks/distribution/source/plot_train_test_feature_drift.py
  docs/source/examples/tabular/checks/distribution/source/plot_trust_score_comparison.py
  docs/source/examples/tabular/checks/distribution/source/plot_whole_dataset_drift.py
  docs/source/examples/vision/checks/distribution/source/plot_heatmap_comparison.py
  docs/source/examples/vision/checks/distribution/source/plot_image_dataset_drift.py
  docs/source/examples/vision/checks/distribution/source/plot_train_test_prediction_drift.py
  docs/source/examples/vision/checks/methodology/source/plot_simple_feature_contribution.py
  docs/source/examples/vision/checks/performance/source/plot_confusion_matrix.py
  docs/source/examples/vision/checks/performance/source/plot_robustness_report.py
  docs/source/examples/vision/checks/performance/source/plot_simple_model_comparison.py
  docs/source/index.rst
  docs/source/tutorials/tabular/plot_quickstart_in_5_minutes.py
  docs/source/tutorials/vision/plot_classification_tutorial.py
  docs/source/tutorials/vision/plot_custom_checks.py
  docs/source/tutorials/vision/plot_custom_task_tutorial.py
  docs/source/tutorials/vision/plot_detection_tutorial.py
  docs/source/tutorials/vision/plot_simple_classification_tutorial.py
  docs/source/user-guide/general/customizations/plot_configure_check_conditions.py
  docs/source/user-guide/general/customizations/plot_create_a_custom_suite.py
  docs/source/user-guide/general/deepchecks_hierarchy.rst
  docs/source/user-guide/general/index.rst
  docs/source/user-guide/tabular/index.rst
  docs/source/user-guide/vision/data-classes/ClassificationData.rst
  docs/source/user-guide/vision/data-classes/DetectionData.rst
  docs/source/user-guide/vision/data-classes/index.rst
  docs/source/user-guide/vision/index.rst
Labels: documentation

#1104 [Issue-721][tabular] IdentifierLeakage fix
  deepchecks/tabular/checks/methodology/identifier_leakage.py
  deepchecks/tabular/dataset.py
  tests/checks/methodology/identifier_leakage_test.py
Labels: bugfix

#1126 fixing search
  docs/source/_static/switcher.json
  docs/source/_templates/layout.html
  docs/source/tutorials/vision/plot_detection_tutorial.py
Labels: documentation

#1128 Fix bad model metrics/bbox properties
  deepchecks/vision/checks/distribution/heatmap_comparison.py
  deepchecks/vision/checks/distribution/image_dataset_drift.py
  deepchecks/vision/checks/methodology/simple_feature_contribution.py
  deepchecks/vision/checks/performance/confusion_matrix.py
  deepchecks/vision/checks/performance/image_segment_performance.py
  tests/vision/checks/distribution/simple_feature_contribution_test.py
Labels: bugfix

#1131 tabular unitests for more model types
  deepchecks/tabular/checks/overview/model_info.py
  deepchecks/tabular/checks/performance/confusion_matrix_report.py
  requirements/dev-requirements.txt
  tests/checks/methodology/boosting_overfit_test.py
  tests/conftest.py
  tests/suites/test_suites.py
Labels: feature

#1136 Fix outliers when properties have None values
  deepchecks/vision/checks/distribution/abstract_property_outliers.py
  tests/vision/checks/distribution/image_property_outliers_test.py
Labels: bugfix

#1146 remove trust score
  deepchecks/checks.py
  deepchecks/tabular/checks/__init__.py
  deepchecks/tabular/checks/distribution/__init__.py
  deepchecks/tabular/checks/distribution/trust_score_comparison.py
  deepchecks/tabular/suites/default_suites.py
  docs/source/examples/tabular/checks/distribution/source/plot_trust_score_comparison.py
  docs/source/tutorials/tabular/plot_phishing_urls.py
  tests/checks/distribution/trust_score_comparison_test.py
Labels: bugfix

#1134 Heatmap Comparison fix to work on custom task
  deepchecks/vision/checks/__init__.py
  deepchecks/vision/checks/distribution/heatmap_comparison.py
  tests/vision/checks/distribution/heatmap_comparison_test.py
  tests/vision/vision_conftest.py
Labels: bugfix

#1137 Sending version
  VERSION
  deepchecks/__init__.py
  docs/requirements.txt
  docs/source/conf.py
  setup.py
Labels: feature

#1149 fix typo in context
  deepchecks/vision/context.py
Labels: bugfix

#1150 Remove the word alternative from properties params
  deepchecks/vision/checks/distribution/abstract_property_outliers.py
  deepchecks/vision/checks/distribution/image_dataset_drift.py
  deepchecks/vision/checks/distribution/image_property_drift.py
  deepchecks/vision/checks/distribution/image_property_outliers.py
  deepchecks/vision/checks/distribution/label_property_outliers.py
  deepchecks/vision/checks/distribution/train_test_label_drift.py
  deepchecks/vision/checks/distribution/train_test_prediction_drift.py
  deepchecks/vision/checks/methodology/simple_feature_contribution.py
  deepchecks/vision/checks/performance/image_segment_performance.py
  deepchecks/vision/checks/performance/model_error_analysis.py
  deepchecks/vision/utils/validation.py
  docs/source/examples/vision/checks/distribution/source/plot_image_property_check.py
  docs/source/tutorials/vision/plot_custom_task_tutorial.py
  docs/source/user-guide/vision/vision_properties.rst
  tests/vision/checks/distribution/image_property_drift_test.py
  tests/vision/checks/distribution/image_property_outliers_test.py
  tests/vision/checks/distribution/label_property_outliers_test.py
  tests/vision/checks/distribution/train_test_label_drift_test.py
  tests/vision/checks/distribution/train_test_prediction_drift_test.py
Labels: refactoring

#1152 Fix problems in old torch version
  deepchecks/vision/vision_data.py
Labels: bugfix

#1153 Add device to validate formatters
  deepchecks/vision/utils/validation.py
  deepchecks/vision/vision_data.py
  tests/vision/utils_tests/validation_test.py
Labels: feature

#1155 Add new integrity suite and kwargs to vision suites
  deepchecks/vision/checks/distribution/heatmap_comparison.py
  deepchecks/vision/suites/default_suites.py
Labels: feature

#1158 Add README for Swindler Detection
  deepchecks/swindler-detection/README.rst
  deepchecks/swindler_detection/README.rst
  docs/images/april-fools-swindler-detection.png
Labels: feature

#1157 Fix incorrect exceptions
  deepchecks/vision/checks/distribution/train_test_label_drift.py
  deepchecks/vision/checks/distribution/train_test_prediction_drift.py
Labels: bugfix
