Repository deepchecks/deepchecks, pull requests merged in 2022-01, with the labels that each got.

#343 small changes to comments
  deepchecks/checks/distribution/train_test_feature_drift.py
  deepchecks/checks/integrity/data_duplicates.py
  deepchecks/utils/features.py
Labels: kind/fix

#381 moving to coveralls
  .github/workflows/build.yml
  makefile
Labels: chore/ci

#333 Adding new drift nb
  conda-recipe/meta.yaml
  examples/checks/distribution/train_test_feature_drift.ipynb
Labels: chore/documentation

#383 Adding files to package
  .licenserc_fix.yaml
  MANIFEST.in
  VERSION
  setup.py
Labels: kind/fix

#379 Mlc 456 unused feature bug
  deepchecks/checks/methodology/unused_features.py
  deepchecks/utils/model.py
  deepchecks/utils/validation.py
Labels: kind/fix

#380 Label + prediction distribution
  deepchecks/checks/__init__.py
  deepchecks/checks/distribution/__init__.py
  deepchecks/checks/distribution/train_test_label_drift.py
  examples/checks/distribution/train_test_label_drift.ipynb
  tests/checks/distribution/train_test_label_drift_test.py
  tests/conftest.py
Labels: kind/feature, feature

#388 Mlc 185 drift for label and pred
  docs/source/examples/checks/distribution/train_test_label_drift.nblink
Labels: kind/fix

#391 Make trust score plot cut off upper and lower 5% of data for display
  deepchecks/checks/distribution/plot.py
  deepchecks/checks/distribution/trust_score_comparison.py
  examples/checks/distribution/trust_score_comparison.ipynb
Labels: kind/fix

#389 Fixing conda packaging
  conda-recipe/build.sh
  conda-recipe/meta.yaml
Labels: chore/ci

#395 Simple model classes fix
  deepchecks/checks/performance/simple_model_comparison.py
Labels: kind/fix

#398 Fix confusion matrix heatmap
  deepchecks/checks/performance/confusion_matrix_report.py
  requirements.txt
Labels: kind/fix

#387 Add explanatation about scorers
  deepchecks/checks/performance/simple_model_comparison.py
Labels: kind/feature

#397 assume task type from model or label
  deepchecks/checks/integrity/label_ambiguity.py
  deepchecks/checks/integrity/new_label.py
  deepchecks/suites/default_suites.py
  examples/checks/integrity/new_label.ipynb
  tests/checks/integrity/new_label_test.py
Labels: kind/fix

#399 Temporary fix for groupby on category
  deepchecks/checks/integrity/data_duplicates.py
  deepchecks/checks/integrity/label_ambiguity.py
  tests/checks/integrity/data_duplicate_test.py
  tests/checks/integrity/label_ambiguity_test.py
  whitelist.txt
Labels: kind/fix

#364 Merge performance report, Class Performance Imbalance and Train test Overfit into one check
  deepchecks/base/dataset.py
  deepchecks/checks/__init__.py
  deepchecks/checks/methodology/__init__.py
  deepchecks/checks/methodology/performance_overfit.py
  deepchecks/checks/performance/__init__.py
  deepchecks/checks/performance/calibration_score.py
  deepchecks/checks/performance/class_performance.py
  deepchecks/checks/performance/performance_report.py
  deepchecks/suites/default_suites.py
  docs/source/examples/checks/methodology/performance_overfit.nblink
  docs/source/examples/checks/performance/class_performance.nblink
  examples/checks/methodology/performance_overfit.ipynb
  examples/checks/performance/class_performance.ipynb
  examples/checks/performance/multi_model_performance_report.ipynb
  examples/checks/performance/performance_report.ipynb
  examples/howto-guides/create_a_custom_suite.ipynb
  tests/base/check_suite_test.py
  tests/checks/methodology/performance_overfit_test.py
  tests/checks/performance/class_performance_test.py
  tests/checks/performance/performance_report_test.py
Labels: kind/feature

#402 drop nan before gausian_kde
  deepchecks/checks/distribution/plot.py
  deepchecks/checks/distribution/train_test_feature_drift.py
  deepchecks/checks/distribution/train_test_label_drift.py
  deepchecks/checks/distribution/whole_dataset_drift.py
Labels: kind/fix

#406 only one performance report
  deepchecks/suites/default_suites.py
Labels: kind/fix

#405 Fix model info to work with pipeline
  deepchecks/checks/overview/model_info.py
  tests/checks/overview/model_info_test.py
Labels: kind/fix

#410 classes names
  deepchecks/checks/performance/roc_report.py
Labels: kind/feature

#412 remove default class imbalance condition
  VERSION
  deepchecks/suites/default_suites.py
Labels: kind/fix

#413 Fix x axis to show categorical correct
  deepchecks/checks/distribution/plot.py
  deepchecks/checks/performance/performance_report.py
Labels: kind/fix

#414 WholeDatasetDrift: Fix legend position
  deepchecks/checks/distribution/whole_dataset_drift.py
Labels: kind/fix

#426 Fix code example of scorer note docstring
  deepchecks/checks/performance/model_error_analysis.py
  deepchecks/checks/performance/performance_report.py
  deepchecks/checks/performance/simple_model_comparison.py
Labels: kind/fix

#442 Update README.md
  README.md
Labels: kind/fix

#415 Roc plotly
  deepchecks/checks/performance/roc_report.py
Labels: kind/feature

#450 Changing tag in GA
  docs/source/_templates/layout.html
Labels: chore/ci

#440 Fix trying to calculate features importance on none model
  deepchecks/utils/features.py
  requirements.txt
  tests/base/feature_importance_utils_test.py
Labels: kind/fix

#436 Add to suite output the checks that haven't run because of missing parameters
  deepchecks/base/check.py
  deepchecks/base/suite.py
  tests/suites/test_suites.py
Labels: kind/fix

#448 Issue template
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/config.yml
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/ISSUE_TEMPLATE/question.yml
  .licenserc_fix.yaml
Labels: chore/ci

#445 test
  deepchecks/checks/distribution/dist_utils.py
  deepchecks/checks/distribution/plot.py
  deepchecks/checks/distribution/preprocessing.py
  deepchecks/checks/distribution/train_test_feature_drift.py
  deepchecks/checks/distribution/train_test_label_drift.py
  docs/source/api/checks/distribution.rst
Labels: kind/feature

#455 move IdentifierLeakage test to plotly
  deepchecks/checks/methodology/identifier_leakage.py
  examples/checks/methodology/identifier_leakage.ipynb
Labels: kind/feature

#454 Bugfix/fix 453
  README.md
  deepchecks/checks/performance/performance_report.py
  deepchecks/utils/metrics.py
  tests/checks/performance/performance_report_test.py
Labels: kind/fix

#459 Changing README files from markdown to RST
  CONTRIBUTING.md
  CONTRIBUTING.rst
  FAQ.md
  FAQ.rst
  README.md
  README.rst
  VERSION
  deepchecks/suites/README.md
  deepchecks/suites/README.rst
  setup.py
Labels: kind/feature

#462 Fix overlap of titles in drift plots
  deepchecks/base/check.py
  deepchecks/checks/distribution/dist_utils.py
  deepchecks/checks/distribution/plot.py
  examples/checks/distribution/train_test_feature_drift.ipynb
  examples/checks/distribution/train_test_label_drift.ipynb
  examples/checks/distribution/whole_dataset_drift.ipynb
Labels: kind/fix

#463 Updating long description
  setup.py
Labels: kind/feature

#461 [issue-439] added 'Number of samples' column to the result dataframe;
  deepchecks/checks/performance/performance_report.py
  examples/checks/performance/multi_model_performance_report.ipynb
  examples/checks/performance/performance_report.ipynb
Labels: kind/feature

#465 Create pull_request_template.md
  .github/pull_request_template.md
  .licenserc_fix.yaml
Labels: chore/ci

#471 Updating long description
  VERSION
  setup.py
Labels: kind/feature

#470 Change binary scorers to also return per class
  deepchecks/checks/performance/performance_report.py
  deepchecks/checks/performance/simple_model_comparison.py
  deepchecks/utils/metrics.py
  tests/checks/performance/performance_report_test.py
Labels: kind/feature

#476 remove_zero_warn
  deepchecks/utils/metrics.py
Labels: kind/fix

#478 remove links from google collab
  deepchecks/base/display_suite.py
Labels: kind/fix

#473 [Issue-439, addition] SimpleModelComparison: added 'Number of samples' column to the result df
  deepchecks/checks/performance/simple_model_comparison.py
  examples/checks/performance/simple_model_comparison.ipynb
Labels: kind/feature

#468 pipeline model can also no be of type BaseEstimator
  deepchecks/utils/model.py
  deepchecks/utils/validation.py
Labels: kind/fix

#481 [issue-437] added favicons to the docs
  docs/source/_static/favicons/apple-touch-icon.png
  docs/source/_static/favicons/favicon.ico
  docs/source/_static/favicons/favicon.png
  docs/source/_templates/layout.html
Labels: kind/fix

#464 [issue-409] added datetime formating function to utils
  deepchecks/checks/methodology/date_train_test_leakage_duplicates.py
  deepchecks/checks/methodology/date_train_test_leakage_overlap.py
  deepchecks/utils/strings.py
  examples/checks/methodology/date_train_validation_leakage_duplicates.ipynb
  tests/utils/test_string_utils.py
Labels: kind/fix

#480 nothing to show on when pps is 0 on all fields
  deepchecks/checks/distribution/plot.py
  deepchecks/checks/methodology/identifier_leakage.py
  deepchecks/checks/methodology/single_feature_contribution.py
  deepchecks/checks/methodology/single_feature_contribution_train_test.py
Labels: kind/fix

#497 Docs and readme fixes
  README.rst
  docs/source/api/checks/integrity.rst
  docs/source/api/checks/methodology.rst
  docs/source/api/checks/performance.rst
  docs/source/conf.py
  docs/source/examples/checks/integrity/special_chars.ipynb
  docs/source/examples/checks/methodology/date_train_test_leakage_duplicates.ipynb
  docs/source/examples/checks/methodology/date_train_test_leakage_overlap.ipynb
  docs/source/examples/index.rst
  docs/source/getting-started/index.rst
  docs/source/user-guide/key_concepts.rst
Labels: kind/fix

#499 [issue-431] modified suite output text
  deepchecks/base/display_suite.py
Labels: kind/fix

#498 use_undeprecated_tqdm
  deepchecks/base/display_suite.py
Labels: kind/fix

#501 fix errors related to string labels
  deepchecks/checks/performance/calibration_score.py
  deepchecks/checks/performance/model_error_analysis.py
  tests/checks/performance/calibration_score_test.py
  tests/checks/performance/model_error_analysis_test.py
  tests/conftest.py
Labels: kind/fix

#507 Remove default from metrics
  deepchecks/utils/metrics.py
  tests/checks/performance/model_error_analysis_test.py
  tests/checks/performance/performance_report_test.py
  tests/checks/performance/simple_model_comparison_test.py
Labels: kind/feature

#504 Fix string labels in performance report / simple model comparison
  deepchecks/checks/performance/performance_report.py
  deepchecks/checks/performance/simple_model_comparison.py
  docs/source/examples/checks/performance/multi_model_performance_report.ipynb
  docs/source/examples/checks/performance/performance_report.ipynb
Labels: kind/fix

#509 dataset mutable properties fix
  deepchecks/base/dataset.py
  tests/base/dataset_test.py
Labels: kind/fix

#514 Add examples folder and routing from readme
  CONTRIBUTING.rst
  FAQ.rst
  deepchecks/suites/README.rst
  docs/images/notebook-example-launch-badges.png
  examples/README.rst
Labels: documentation

#515 changing gh labels
  .github/workflows/pr.yaml
Labels: ci

#516 Update examples/README.rst
  examples/README.rst
Labels: documentation

#519 Update performance.rst
  docs/source/api/checks/performance.rst
Labels: documentation

#518 Update display_suite.py
  deepchecks/base/display_suite.py
Labels: feature

#522 docs fixes
  docs/source/examples/index.rst
  docs/source/index.rst
Labels: documentation

#526 Fix PerfectModel when data have nulls in label
  deepchecks/checks/performance/simple_model_comparison.py
  deepchecks/utils/metrics.py
  deepchecks/utils/models.py
Labels: bugfix

#531 Adding failed suffixes
  deepchecks/base/check.py
  deepchecks/base/display_suite.py
  deepchecks/base/suite.py
Labels: bugfix

#500 Update the Dataset Object Documentation
  README.rst
  docs/source/index.rst
  docs/source/user-guide/dataset_object.rst
Labels: feature

#537 modifying automatic PR label
  .github/workflows/nb-generation.yml
Labels: ci

#524 Update README.rst
  README.rst
Labels: bugfix

#536 Fixing the license attribute in the setup.py file
  setup.py
Labels: bugfix

#538 refactor_check_py
  .github/workflows/pr.yaml
  deepchecks/base/__init__.py
  deepchecks/base/check.py
  deepchecks/base/condition.py
  deepchecks/base/suite.py
Labels: refactoring

#540 Merging hotfixes from 0.2.x 🎉 🔁
  deepchecks/checks/performance/simple_model_comparison.py
  deepchecks/datasets/classification/iris.py
  deepchecks/utils/metrics.py
  deepchecks/utils/models.py
  docs/source/api/datasets/classification.rst
Labels: feature

#545 Added colon to bug template
  .github/ISSUE_TEMPLATE/bug_report.md
Labels: feature

#550 Fixed future warnings in Calibration Score check 🔮
  deepchecks/checks/performance/calibration_score.py
  docs/source/examples/checks/performance/calibration_score.ipynb
  tests/checks/performance/calibration_score_test.py
Labels: bugfix

#542 Add youden's index marker point to roc report
  deepchecks/checks/performance/roc_report.py
  docs/source/examples/checks/performance/roc_report.ipynb
  tests/checks/performance/roc_report_test.py
Labels: feature

#551 Filter null labels before sampling for more accurate metrics
  deepchecks/base/dataset.py
  deepchecks/checks/performance/model_error_analysis.py
  tests/base/dataset_test.py
Labels: bugfix

#541 Added value for drift value in whole dataset drift
  deepchecks/checks/distribution/whole_dataset_drift.py
  tests/checks/distribution/whole_dataset_drift_test.py
Labels: bugfix

#552 Rename whitelist.txt to spelling-allowlist.txt
  makefile
  spelling-allowlist.txt
Labels: bugfix

#575 [issue-527] `RegressionSystematicError` check plot fix - made hoverboxes content smaller
  deepchecks/checks/performance/regression_systematic_error.py
Labels: bugfix

#577 downgrade requirements so that it doesn't trigger colab conflict error
  requirements.txt
Labels: bugfix

#574 Fix permutation importance to filter nan labels
  deepchecks/utils/features.py
  tests/base/feature_importance_utils_test.py
Labels: bugfix

#583 Moved distribution utils classes from checks package to utils package
  deepchecks/base/__init__.py
  deepchecks/checks/distribution/train_test_feature_drift.py
  deepchecks/checks/distribution/train_test_label_drift.py
  deepchecks/checks/distribution/trust_score_comparison.py
  deepchecks/checks/distribution/whole_dataset_drift.py
  deepchecks/checks/performance/simple_model_comparison.py
  deepchecks/utils/distribution/__init__.py
  deepchecks/utils/distribution/drift.py
  deepchecks/utils/distribution/plot.py
  deepchecks/utils/distribution/preprocessing.py
  deepchecks/utils/distribution/rare_category_encoder.py
  deepchecks/utils/distribution/trust_score.py
Labels: feature

#584 Fixing binder and colab links
  docs/source/index.rst
Labels: documentation

#578 StringLengthOutOfBounds: Add examples of outliers to result
  deepchecks/checks/integrity/string_length_out_of_bounds.py
  docs/source/examples/checks/integrity/string_length_out_of_bounds.ipynb
Labels: feature

#556 replace _NUMBER_OF_FEATURES_LIMIT by _PERMUTATION_IMPORTANCE_TIMEOUT
  deepchecks/utils/features.py
Labels: refactoring

#595 Update structure of feature drift nb
  deepchecks/base/check.py
  docs/source/examples/checks/distribution/train_test_feature_drift.ipynb
Labels: refactoring

#600 Fix pandas style.apply doesn't work on df with non-unique indices
  deepchecks/base/display_pandas.py
Labels: bugfix

#579 [issue-342] added docs link check CI/CD workflow
  .github/workflows/documentation.yaml
  docs/.lycheeignore
Labels: feature

#598 chose scorer based on score and fit on model in permutational feature importance
  deepchecks/utils/features.py
Labels: bugfix

#611 new phishing data and model
  deepchecks/datasets/classification/phishing.py
Labels: bugfix

#612 cast to float before plotting
  deepchecks/checks/distribution/train_test_feature_drift.py
  deepchecks/checks/distribution/whole_dataset_drift.py
  deepchecks/utils/distribution/drift.py
Labels: bugfix

#610 Improve display
  deepchecks/base/check.py
  deepchecks/base/display_pandas.py
  deepchecks/base/display_suite.py
  deepchecks/utils/strings.py
  tests/utils/test_string_utils.py
Labels: feature

#641 fix text not in new line
  deepchecks/base/check.py
Labels: bugfix

#645 fix typo
  deepchecks/checks/integrity/label_ambiguity.py
  docs/source/examples/checks/integrity/label_ambiguity.ipynb
Labels: bugfix

#662 Fix "train test feature drift" notebook headers
  docs/source/examples/checks/distribution/train_test_feature_drift.ipynb
Labels: bugfix

#644 Improve trust score docs
  deepchecks/checks/distribution/trust_score_comparison.py
  deepchecks/datasets/classification/breast_cancer.py
  deepchecks/datasets/classification/iris.py
  deepchecks/ppscore.py
  docs/source/examples/checks/distribution/trust_score_comparison.ipynb
Labels: documentation

#638 Added option to save suite output as html
  .licenserc_fix.yaml
  deepchecks/base/display_suite.py
  deepchecks/base/resources/suite_output.html
  deepchecks/base/suite.py
  docs/source/examples/guides/save_suite_result_as_html.ipynb
  docs/source/examples/index.rst
  docs/source/index.rst
Labels: feature

#664 Fix distribution plots outliers
  deepchecks/checks/distribution/trust_score_comparison.py
  deepchecks/utils/distribution/plot.py
Labels: refactoring

#670 update save as html example
  docs/source/examples/guides/save_suite_result_as_html.ipynb
Labels: bugfix

#642 [DOCS] Update "Single Feature Contribution Train Test" notebook
  deepchecks/base/display_suite.py
  deepchecks/checks/methodology/single_feature_contribution.py
  deepchecks/checks/methodology/single_feature_contribution_train_test.py
  docs/source/examples/checks/methodology/single_feature_contribution_train_test.ipynb
  tests/checks/methodology/single_feature_contribution_test.py
Labels: refactoring

#626 [DOCS] Improve data duplicates example
  deepchecks/checks/integrity/data_duplicates.py
  deepchecks/utils/strings.py
  docs/source/examples/checks/integrity/data_duplicates.ipynb
  tests/checks/distribution/trust_score_comparison_test.py
  tests/checks/integrity/data_duplicate_test.py
  tests/checks/integrity/dominant_frequency_change_test.py
  tests/checks/integrity/label_ambiguity_test.py
  tests/checks/integrity/mixed_data_types_test.py
  tests/checks/integrity/new_category_test.py
  tests/checks/integrity/new_label_test.py
  tests/checks/integrity/special_chars_test.py
  tests/checks/integrity/string_length_out_of_bounds_test.py
  tests/checks/integrity/string_mismatch_comparison_test.py
  tests/checks/integrity/string_mismatch_test.py
  tests/checks/methodology/boosting_overfit_test.py
  tests/checks/methodology/date_leakage_test.py
  tests/checks/methodology/index_train_val_leakage_test.py
  tests/checks/methodology/train_test_samples_mix_test.py
  tests/checks/performance/model_error_analysis_test.py
  tests/checks/performance/simple_model_comparison_test.py
Labels: refactoring

#689 fix typo in save html code
  deepchecks/base/display_suite.py
  docs/source/examples/guides/save_suite_result_as_html.ipynb
Labels: bugfix

#680 [DOCS] Updated Guide - Create a Custom Suite
  docs/source/examples/guides/create_a_custom_suite.ipynb
Labels: documentation

#613 Update "Simple Model Comparison" notebook
  deepchecks/utils/validation.py
  docs/source/examples/checks/performance/simple_model_comparison.ipynb
Labels: refactoring

#690 Fix drift score bar are zoomable
  deepchecks/checks/distribution/whole_dataset_drift.py
  deepchecks/utils/distribution/drift.py
  deepchecks/utils/distribution/plot.py
Labels: bugfix

#693 [DOCS] Small updates to export to html guide
  docs/source/examples/guides/save_suite_result_as_html.ipynb
Labels: documentation

#643 Add supported models to user guide documentation
  docs/source/index.rst
  docs/source/user-guide/index.rst
  docs/source/user-guide/supported_models.rst
Labels: documentation

#688 [issue-571] sphinx errors fixes
  docs/.lycheeignore
  docs/source/conf.py
  docs/source/examples/checks/index.rst
  docs/source/examples/guides/create_a_custom_suite.ipynb
  docs/source/user-guide/dataset_object.rst
  docs/source/user-guide/key_concepts.rst
Labels: documentation, bugfix

#692 fix doc links
  docs/source/user-guide/dataset_object.rst
  docs/source/user-guide/key_concepts.rst
Labels: documentation

#695 Fix Train Test Samples Mix
  deepchecks/checks/methodology/train_test_samples_mix.py
  spelling-allowlist.txt
  tests/checks/methodology/train_test_samples_mix_test.py
Labels: refactoring, bugfix

#665 added option to save checks as json
  deepchecks/base/check.py
  deepchecks/base/display_pandas.py
  deepchecks/base/display_suite.py
  deepchecks/base/suite.py
  docs/source/examples/guides/export_outputs_to_json.ipynb
  docs/source/examples/index.rst
  requirements.txt
  tests/base/to_json_test.py
Labels: feature

#696 🚀 🚀 version bump 0.3.0
  VERSION
Labels: ci

#699 Update index.rst
  docs/source/examples/index.rst
Labels: documentation

#703 Build model if loading causes errors
  deepchecks/datasets/classification/breast_cancer.py
  deepchecks/datasets/classification/iris.py
  deepchecks/datasets/classification/phishing.py
  deepchecks/datasets/regression/avocado.py
Labels: refactoring

#707 Kaggle patch for plotly widgets
  deepchecks/base/display_suite.py
Labels: bugfix

#708 add kaggle to allowed words + version bump
  VERSION
  spelling-allowlist.txt
Labels: bugfix

#706 update suite exceptions and links
  deepchecks/base/display_suite.py
  deepchecks/base/suite.py
  deepchecks/checks/methodology/single_feature_contribution.py
  deepchecks/checks/methodology/single_feature_contribution_train_test.py
  deepchecks/utils/validation.py
  tests/checks/methodology/single_feature_contribution_test.py
  tests/checks/overview/model_info_test.py
  tests/checks/performance/performance_report_test.py
Labels: refactoring

#717 Colab prettier suite view
  deepchecks/base/display_suite.py
  deepchecks/base/suite.py
  spelling-allowlist.txt
Labels: feature

#715 Check display read more
  deepchecks/__init__.py
  deepchecks/utils/strings.py
  tests/utils/test_string_utils.py
Labels: feature

#726 make conda build trigger
  .github/workflows/conda_publish.yml
  .github/workflows/release.yml
Labels: bugfix

#720 update readme plot
  docs/images/train-test-drift-output.png
Labels: feature

#738 Added validations to numpydoc docstrings ✅
  deepchecks/checks/distribution/train_test_feature_drift.py
  deepchecks/checks/distribution/whole_dataset_drift.py
  deepchecks/checks/integrity/dominant_frequency_change.py
  deepchecks/checks/integrity/new_label.py
  deepchecks/checks/methodology/date_train_test_leakage_duplicates.py
  deepchecks/checks/methodology/date_train_test_leakage_overlap.py
  deepchecks/checks/methodology/identifier_leakage.py
  deepchecks/checks/methodology/index_leakage.py
  deepchecks/checks/methodology/model_inference_time.py
  deepchecks/checks/methodology/unused_features.py
  deepchecks/checks/performance/regression_error_distribution.py
  deepchecks/checks/performance/simple_model_comparison.py
  docs/source/conf.py
Labels: documentation

#718 Update docstrings in default_suites.py
  deepchecks/base/suite.py
  deepchecks/suites/default_suites.py
Labels: documentation

#739 explicitly set default timeout for fi calculation
  deepchecks/base/check_context.py
  deepchecks/checks/distribution/whole_dataset_drift.py
  deepchecks/utils/features.py
Labels: bugfix

#734 Rename scorers related parameters
  deepchecks/base/check_context.py
  deepchecks/base/suite.py
  deepchecks/checks/performance/performance_report.py
  deepchecks/checks/performance/simple_model_comparison.py
  deepchecks/utils/metrics.py
  tests/checks/performance/simple_model_comparison_test.py
Labels: refactoring

#741 Removed generated html files generated from notebook
  docs/source/examples/guides/my_suite.html
  docs/source/examples/guides/output.html
  docs/source/examples/guides/save_suite_result_as_html.ipynb
Labels: bugfix

#745 Warn user when trying to show result in a non-interactive shell
  deepchecks/base/check.py
  deepchecks/base/suite.py
  deepchecks/utils/ipython.py
Labels: feature

#735 add check display tests
  deepchecks/base/check.py
  deepchecks/base/display_suite.py
  requirements.txt
  tests/base/display_test.py
Labels: tests

#749 Add more warning for the user when calculating FI
  deepchecks/utils/features.py
  tests/base/feature_importance_utils_test.py
Labels: refactoring

#740 Add FI permutation options to UnusedFeatures
  deepchecks/checks/methodology/unused_features.py
Labels: feature

#760 label amibuity notebook improvemnts
  deepchecks/base/dataset.py
  deepchecks/checks/integrity/label_ambiguity.py
  docs/source/examples/checks/integrity/label_ambiguity.ipynb
Labels: documentation

#764 add conda recipe for ipython
  conda-recipe/meta.yaml
Labels: ci

#767 Move responsibilities from context to dataset
  deepchecks/base/check_context.py
  deepchecks/base/dataset.py
  deepchecks/checks/distribution/train_test_feature_drift.py
  deepchecks/checks/distribution/train_test_label_drift.py
  deepchecks/checks/distribution/trust_score_comparison.py
  deepchecks/checks/distribution/whole_dataset_drift.py
  deepchecks/checks/integrity/dominant_frequency_change.py
  deepchecks/checks/integrity/label_ambiguity.py
  deepchecks/checks/integrity/new_category.py
  deepchecks/checks/integrity/new_label.py
  deepchecks/checks/methodology/date_train_test_leakage_duplicates.py
  deepchecks/checks/methodology/date_train_test_leakage_overlap.py
  deepchecks/checks/methodology/identifier_leakage.py
  deepchecks/checks/methodology/index_leakage.py
  deepchecks/checks/methodology/model_inference_time.py
  deepchecks/checks/methodology/single_feature_contribution.py
  deepchecks/checks/methodology/single_feature_contribution_train_test.py
  deepchecks/checks/methodology/train_test_samples_mix.py
  deepchecks/checks/methodology/unused_features.py
  deepchecks/checks/performance/calibration_score.py
  deepchecks/checks/performance/confusion_matrix_report.py
  deepchecks/checks/performance/model_error_analysis.py
  deepchecks/checks/performance/performance_report.py
  deepchecks/checks/performance/regression_error_distribution.py
  deepchecks/checks/performance/regression_systematic_error.py
  deepchecks/checks/performance/roc_report.py
  deepchecks/checks/performance/segment_performance.py
  deepchecks/checks/performance/simple_model_comparison.py
  deepchecks/utils/metrics.py
  deepchecks/utils/validation.py
  tests/base/to_json_test.py
  tests/checks/methodology/date_leakage_test.py
  tests/checks/methodology/identifier_leakage_test.py
  tests/checks/methodology/index_train_val_leakage_test.py
  tests/checks/methodology/single_feature_contribution_test.py
  tests/checks/performance/calibration_score_test.py
  tests/checks/performance/confusion_matrix_report_test.py
  tests/checks/performance/model_error_analysis_test.py
  tests/checks/performance/performance_report_test.py
  tests/checks/performance/regression_error_distribution_test.py
  tests/checks/performance/regression_systematic_error_test.py
  tests/checks/performance/roc_report_test.py
  tests/checks/performance/segment_performance_test.py
  tests/conftest.py
Labels: refactoring

#770 functionality-split additional fix
  deepchecks/base/check_context.py
Labels: bugfix

#778 reduce on _evals rather than bb_info
  deepchecks/vision/utils/detection_precision_recall.py
  deepchecks/vision/utils/iou_utils.py
Labels: feature

#771 added tests for single feature data + improved tests
  deepchecks/tabular/checks/methodology/unused_features.py
  deepchecks/utils/features.py
  deepchecks/utils/metrics.py
  tests/conftest.py
  tests/suites/test_suites.py
Labels: tests, refactoring

#780 updated makefile
  .github/workflows/build.yml
  MANIFEST.in
  docs/.lycheeignore
  makefile
  requirements/dev-requirements.txt
  requirements/vision-requirements.txt
  setup.py
  tox.ini
Labels: refactoring

#773 Adding base vision package
  deepchecks/checks.py
  deepchecks/suites.py
  deepchecks/tabular/checks/__init__.py
  deepchecks/vision/__init__.py
  deepchecks/vision/base.py
  deepchecks/vision/checks/__init__.py
  deepchecks/vision/checks/distribution/__init__.py
  deepchecks/vision/checks/distribution/train_test_label_drift.py
  deepchecks/vision/checks/performance/__init__.py
  deepchecks/vision/checks/performance/performance_report.py
  deepchecks/vision/dataset.py
  deepchecks/vision/datasets/__init__.py
  deepchecks/vision/datasets/classification/__init__.py
  deepchecks/vision/datasets/classification/mnist.py
  deepchecks/vision/datasets/detection/__init__.py
  deepchecks/vision/datasets/detection/coco.py
  deepchecks/vision/datasets/detection/yolo_to_coco.py
  deepchecks/vision/metrics_utils/__init__.py
  deepchecks/vision/metrics_utils/detection_precision_recall.py
  deepchecks/vision/metrics_utils/iou_utils.py
  deepchecks/vision/metrics_utils/metrics.py
  deepchecks/vision/utils/__init__.py
  deepchecks/vision/utils/validation.py
  docs/source/api/index.rst
  docs/source/api/tabular.rst
  docs/source/api/vision.rst
  docs/source/examples/checks/vision/checks/distribution/train_test_label_drift.ipynb
  docs/source/examples/checks/vision/checks/performance/performance_report.ipynb
  makefile
  requirements/dev-requirements.txt
  spelling-allowlist.txt
  tests/conftest.py
  tests/vision/utils/__init__.py
  tests/vision/utils/metrics_test.py
  tests/vision/vision_conftest.py
  tox.ini
Labels: feature

#783 Add links to suite
  docs/source/user-guide/when_should_you_use.rst
Labels: documentation

#785 Making the notebooks gen multi-procces
  makefile
Labels: ci

#788 Vision docs placeholder
  deepchecks/vision/base.py
  docs/source/conf.py
  docs/source/examples/checks/tabular.rst
  docs/source/examples/checks/tabular/index.rst
  docs/source/examples/checks/vision/distribution/index.rst
  docs/source/examples/checks/vision/distribution/train_test_label_drift.ipynb
  docs/source/examples/checks/vision/index.rst
  docs/source/examples/checks/vision/performance/index.rst
  docs/source/examples/checks/vision/performance/performance_report.ipynb
  docs/source/examples/index.rst
Labels: documentation

#790 Fixing rtd build
  .readthedocs.yaml
  requirements/rtd-requirements.txt
Labels: documentation

#786 Add sample data loader & sample predictions and label caching
  deepchecks/vision/base.py
  deepchecks/vision/checks/distribution/train_test_label_drift.py
  deepchecks/vision/checks/performance/performance_report.py
  deepchecks/vision/dataset.py
  deepchecks/vision/metrics_utils/__init__.py
  deepchecks/vision/metrics_utils/metrics.py
  tests/vision/utils/metrics_test.py
Labels: feature

#792 Fix pandas warning
  deepchecks/core/display_pandas.py
  deepchecks/tabular/checks/integrity/label_ambiguity.py
  deepchecks/tabular/checks/overview/model_info.py
  deepchecks/utils/features.py
  docs/source/examples/checks/tabular/integrity/label_ambiguity.ipynb
  tests/base/feature_importance_utils_test.py
Labels: bugfix

#789 [issue-781] moved checks base classes to core
  deepchecks/__init__.py
  deepchecks/core/__init__.py
  deepchecks/core/check.py
  deepchecks/tabular/__init__.py
  deepchecks/tabular/base.py
  deepchecks/tabular/checks/distribution/train_test_feature_drift.py
  deepchecks/tabular/checks/distribution/train_test_label_drift.py
  deepchecks/tabular/checks/distribution/trust_score_comparison.py
  deepchecks/tabular/checks/distribution/whole_dataset_drift.py
  deepchecks/tabular/checks/integrity/data_duplicates.py
  deepchecks/tabular/checks/integrity/dominant_frequency_change.py
  deepchecks/tabular/checks/integrity/is_single_value.py
  deepchecks/tabular/checks/integrity/label_ambiguity.py
  deepchecks/tabular/checks/integrity/mixed_data_types.py
  deepchecks/tabular/checks/integrity/mixed_nulls.py
  deepchecks/tabular/checks/integrity/new_category.py
  deepchecks/tabular/checks/integrity/new_label.py
  deepchecks/tabular/checks/integrity/special_chars.py
  deepchecks/tabular/checks/integrity/string_length_out_of_bounds.py
  deepchecks/tabular/checks/integrity/string_mismatch.py
  deepchecks/tabular/checks/integrity/string_mismatch_comparison.py
  deepchecks/tabular/checks/methodology/boosting_overfit.py
  deepchecks/tabular/checks/methodology/datasets_size_comparison.py
  deepchecks/tabular/checks/methodology/date_train_test_leakage_duplicates.py
  deepchecks/tabular/checks/methodology/date_train_test_leakage_overlap.py
  deepchecks/tabular/checks/methodology/identifier_leakage.py
  deepchecks/tabular/checks/methodology/index_leakage.py
  deepchecks/tabular/checks/methodology/model_inference_time.py
  deepchecks/tabular/checks/methodology/single_feature_contribution.py
  deepchecks/tabular/checks/methodology/single_feature_contribution_train_test.py
  deepchecks/tabular/checks/methodology/train_test_samples_mix.py
  deepchecks/tabular/checks/methodology/unused_features.py
  deepchecks/tabular/checks/overview/columns_info.py
  deepchecks/tabular/checks/overview/model_info.py
  deepchecks/tabular/checks/performance/calibration_score.py
  deepchecks/tabular/checks/performance/confusion_matrix_report.py
  deepchecks/tabular/checks/performance/model_error_analysis.py
  deepchecks/tabular/checks/performance/performance_report.py
  deepchecks/tabular/checks/performance/regression_error_distribution.py
  deepchecks/tabular/checks/performance/regression_systematic_error.py
  deepchecks/tabular/checks/performance/roc_report.py
  deepchecks/tabular/checks/performance/segment_performance.py
  deepchecks/tabular/checks/performance/simple_model_comparison.py
  deepchecks/vision/__init__.py
  deepchecks/vision/base.py
  deepchecks/vision/checks/distribution/train_test_label_drift.py
  deepchecks/vision/checks/performance/performance_report.py
  docs/source/examples/guides/add_a_custom_check.ipynb
  makefile
  tests/base/check_suite_test.py
  tests/base/check_test.py
  tests/suites/test_suites.py
Labels: refactoring
