Repository deepchecks/deepchecks, pull requests merged in 2023-07, with the labels that each got.

#2620 Update scipy version and broken pillow dependencies in requirements
  deepchecks/vision/utils/image_functions.py
  requirements/dev-requirements.txt
  requirements/requirements.txt
Labels: bug

#2617 Improved heatmap display for confusion matrix report
  deepchecks/utils/abstracts/confusion_matrix_abstract.py
  deepchecks/vision/checks/model_evaluation/confusion_matrix.py
  tests/nlp/checks/model_evaluation/confusion_matrix_test.py
  tests/tabular/checks/model_evaluation/confusion_matrix_report_test.py
  tests/vision/checks/model_evaluation/confusion_matrix_test.py
Labels: feature

#2621 Calculation of NLP properties with batches
  deepchecks/nlp/utils/text_properties.py
  tests/nlp/utils/test_properties.py
Labels: feature

#2628 bug fix properties calc on single sample batch
  deepchecks/nlp/utils/text_properties.py
  tests/nlp/utils/test_properties.py
Labels: bug

#2632 fix nlp device kwargs
  deepchecks/nlp/utils/text_properties.py
  requirements/nlp-prop-requirements.txt
Labels: bug

#2634 Add examples to new and existing properties
  docs/source/nlp/usage_guides/nlp_properties_extended.rst
Labels: documentation

#2636 Amend docs - use spearman rather than Pearson
  docs/source/checks/tabular/data_integrity/plot_feature_feature_correlation.py
Labels: documentation

#2635 Differentiate special chars from punctuations
  deepchecks/nlp/utils/text_properties.py
  docs/source/nlp/usage_guides/nlp_properties.rst
  tests/nlp/checks/data_integrity/under_annotated_segments_test.py
  tests/nlp/checks/train_test_validation/property_drift_test.py
  tests/nlp/test_text_data.py
  tests/nlp/utils/test_properties.py
Labels: feature

#2639 Rename Readability Score to Reading Ease
  deepchecks/nlp/utils/text_properties.py
  docs/source/nlp/usage_guides/nlp_properties.rst
  docs/source/nlp/usage_guides/nlp_properties_extended.rst
  tests/nlp/test_text_data.py
  tests/nlp/utils/test_properties.py
Labels: documentation

#2641 Add ability to cache text prop models
  .github/workflows/build.yml
  deepchecks/nlp/utils/text_properties.py
  deepchecks/nlp/utils/text_properties_models.py
  tests/nlp/utils/test_properties.py
Labels: feature

#2647 Fix the Simple Model Comp condition
  deepchecks/tabular/checks/model_evaluation/simple_model_comparison.py
  tests/tabular/checks/model_evaluation/simple_model_comparison_test.py
Labels: bug

#2645 Weak segment - return single segment per feature argument
  deepchecks/nlp/checks/data_integrity/under_annotated_segments.py
  deepchecks/nlp/checks/model_evaluation/weak_segments_performance.py
  deepchecks/tabular/checks/model_evaluation/weak_segments_performance.py
  deepchecks/utils/abstracts/weak_segment_abstract.py
  deepchecks/vision/checks/model_evaluation/weak_segments_performance.py
  docs/source/checks/nlp/data_integrity/plot_under_annotated_metadata_segments.py
  docs/source/checks/nlp/data_integrity/plot_under_annotated_property_segments.py
  docs/source/checks/nlp/model_evaluation/plot_metadata_segments_performance.py
  docs/source/checks/nlp/model_evaluation/plot_property_segments_performance.py
  docs/source/checks/tabular/model_evaluation/plot_weak_segments_performance.py
  docs/source/nlp/tutorials/quickstarts/plot_multi_label_classification.py
  docs/source/nlp/tutorials/quickstarts/plot_text_classification.py
  docs/source/nlp/tutorials/quickstarts/plot_token_classification.py
  tests/nlp/checks/data_integrity/under_annotated_segments_test.py
  tests/nlp/checks/model_evaluation/weak_segment_performance_test.py
  tests/tabular/checks/model_evaluation/weak_segments_performance_test.py
Labels: feature

#2648 rename is english to english text
  deepchecks/nlp/utils/text_properties.py
  tests/nlp/utils/test_properties.py
Labels: feature

#2649 Return nan embeddings for empty samples
  deepchecks/nlp/checks/data_integrity/conflicting_labels.py
  deepchecks/nlp/checks/data_integrity/special_characters.py
  deepchecks/nlp/checks/data_integrity/text_property_outliers.py
  deepchecks/nlp/utils/text_embeddings.py
  tests/nlp/checks/data_integrity/special_characters_test.py
  tests/nlp/checks/data_integrity/text_property_outliers_test.py
Labels: bug
