Repository deepchecks/deepchecks, pull requests merged in 2023-04, with the labels that each got.

#2433 Fix bugs in Text Outliers display
  deepchecks/nlp/utils/nlp_plot.py
Labels: bug, nlp

#2434 updated dataset - airbnb
  deepchecks/tabular/datasets/regression/airbnb.py
  tests/tabular/test_datasets.py
Labels: feature

#2432 refactor text data
  deepchecks/nlp/checks/data_integrity/property_label_correlation.py
  deepchecks/nlp/checks/data_integrity/text_property_outliers.py
  deepchecks/nlp/checks/model_evaluation/weak_segments_performance.py
  deepchecks/nlp/context.py
  deepchecks/nlp/datasets/classification/tweet_emotion.py
  deepchecks/nlp/input_validations.py
  deepchecks/nlp/task_type.py
  deepchecks/nlp/text_data.py
  deepchecks/nlp/utils/text_properties.py
  deepchecks/utils/validation.py
  docs/source/user-guide/nlp/quickstarts/plot_text_classification.py
  tests/nlp/checks/data_integrity/property_label_correlation_test.py
  tests/nlp/checks/model_evaluation/confusion_matrix_test.py
  tests/nlp/checks/model_evaluation/prediction_drift_test.py
  tests/nlp/checks/model_evaluation/single_dataset_performance_test.py
  tests/nlp/conftest.py
  tests/nlp/test_text_data.py
Labels: feature

#2440 Improve column type inference
  .github/workflows/build.yml
  deepchecks/tabular/dataset.py
  deepchecks/utils/type_inference.py
Labels: bug

#2442 fix sklearn warning
  deepchecks/tabular/metric_utils/scorers.py
Labels: bug

#2437 Update MANIFEST.in to include nlp-prop-requirements.txt
  MANIFEST.in
Labels: ci

#2438 [DEE-443;DEE-460] text properties refactoring; removal of 'TextData.properties_types' and 'TextData.metadata_types'
  deepchecks/core/check_result.py
  deepchecks/nlp/checks/data_integrity/text_property_outliers.py
  deepchecks/nlp/checks/model_evaluation/weak_segments_performance.py
  deepchecks/nlp/input_validations.py
  deepchecks/nlp/text_data.py
  deepchecks/nlp/utils/__init__.py
  deepchecks/nlp/utils/text_properties.py
  requirements/nlp-prop-requirements.txt
  requirements/nlp-requirements.txt
  spelling-allowlist.txt
  tests/base/feature_importance_utils_test.py
  tests/base/test_tabular_deprecation_warnings.py
  tests/base/test_vision_deprecation_warnings.py
  tests/nlp/checks/data_integrity/text_property_outliers_test.py
  tests/nlp/checks/model_evaluation/confusion_matrix_test.py
  tests/nlp/checks/model_evaluation/prediction_drift_test.py
  tests/nlp/checks/model_evaluation/single_dataset_performance_test.py
  tests/nlp/conftest.py
  tests/nlp/test_context.py
  tests/nlp/test_datasets.py
  tests/nlp/test_text_data.py
  tests/nlp/utils/test_properties.py
  tests/tabular/checks/integrity/string_mismatch_test.py
  tests/tabular/checks/model_evaluation/performance_bias_test.py
  tests/tabular/checks/model_evaluation/prediction_drift_test.py
  tests/tabular/checks/model_evaluation/simple_model_comparison_test.py
  tests/tabular/checks/model_evaluation/single_dataset_performance_test.py
  tests/tabular/checks/train_test_validation/feature_drift_test.py
  tests/tabular/checks/train_test_validation/label_drift_test.py
  tests/tabular/suites/test_suites.py
  tests/tabular/test_datasets.py
  tests/tabular/test_dummy_model.py
  tests/tabular/test_tabular_context.py
  tests/utils/metrics_test.py
  tests/vision/base/test_suite.py
  tests/vision/base/test_vision_data.py
  tests/vision/checks/data_integrity/image_property_outliers_test.py
  tests/vision/checks/model_evaluation/prediction_drift_test.py
  tests/vision/checks/train_test_validation/image_property_drift_test.py
  tests/vision/checks/train_test_validation/label_drift_test.py
  tests/vision/datasets/test_mnist_tf.py
  tests/vision/gpu_tests/full_suite_test.py
  tests/vision/utils_tests/metrics_test.py
Labels: refactoring

#2449 nlp doc structure + metrics_guide.rst
  docs/source/checks/nlp/README.txt
  docs/source/checks/nlp/custom/README.txt
  docs/source/checks/nlp/data_integrity/README.txt
  docs/source/checks/nlp/model_evaluation/README.txt
  docs/source/checks/nlp/train_test_validation/README.txt
  docs/source/checks_gallery/nlp.rst
  docs/source/user-guide/general/metrics_guide.rst
Labels: documentation

#2444 don't fail on langdetect
  deepchecks/nlp/utils/text_properties.py
Labels: bug

#2445 [DEE-440] added error msg to checks that do not support token/multi-label classification
  deepchecks/core/errors.py
  deepchecks/nlp/checks/data_integrity/property_label_correlation.py
  deepchecks/nlp/checks/data_integrity/text_property_outliers.py
  deepchecks/nlp/checks/model_evaluation/confusion_matrix_report.py
  deepchecks/nlp/checks/model_evaluation/prediction_drift.py
  deepchecks/nlp/checks/model_evaluation/single_dataset_performance.py
  deepchecks/nlp/checks/model_evaluation/weak_segments_performance.py
  deepchecks/nlp/checks/train_test_validation/label_drift.py
  deepchecks/nlp/context.py
  deepchecks/nlp/metric_utils/token_classification.py
  deepchecks/nlp/utils/data_inference.py
  deepchecks/utils/validation.py
  spelling-allowlist.txt
  tests/nlp/checks/model_evaluation/single_dataset_performance_test.py
Labels: refactoring, dev

#2466 update_version_to_comply_with_new_pep
  VERSION
Labels: bug

#2465 fix hide index
  deepchecks/core/serialization/common.py
  deepchecks/core/serialization/suite_result/html.py
  deepchecks/core/serialization/suite_result/widget.py
  deepchecks/tabular/checks/model_evaluation/model_info.py
Labels: bug

#2467 Nb/feat/multi label
  deepchecks/nlp/checks/model_evaluation/prediction_drift.py
  deepchecks/nlp/checks/train_test_validation/label_drift.py
  deepchecks/tabular/checks/model_evaluation/prediction_drift.py
  deepchecks/tabular/checks/train_test_validation/label_drift.py
  deepchecks/utils/abstracts/label_drift.py
  deepchecks/utils/abstracts/prediction_drift.py
  tests/conftest.py
  tests/nlp/checks/model_evaluation/prediction_drift_test.py
  tests/nlp/checks/train_test_validation/label_drift_test.py
  tests/nlp/checks/train_test_validation/property_drift_test.py
  tests/nlp/conftest.py
  tests/tabular/checks/model_evaluation/prediction_drift_test.py
  tests/tabular/checks/train_test_validation/label_drift_test.py
Labels: feature, nlp

#2458 [DEE-486] nlp 'token_*_per_class' scorers fix
  deepchecks/nlp/metric_utils/token_classification.py
  deepchecks/nlp/utils/data_inference.py
  docs/source/user-guide/general/metrics_guide.rst
  tests/nlp/checks/model_evaluation/single_dataset_performance_test.py
  tests/nlp/checks/model_evaluation/train_test_performance_test.py
Labels: bug

#2469 Adding redirects for top 30 pages
  docs/source/conf.py
Labels: documentation

#2472 Nir/dee 482 create plot files for nlp drift
  deepchecks/nlp/checks/data_integrity/text_property_outliers.py
  deepchecks/vision/suites/default_suites.py
  docs/source/checks/nlp/data_integrity/plot_property_label_correlation.py
  docs/source/checks/nlp/data_integrity/plot_text_property_outliers.py
  docs/source/checks/nlp/model_evaluation/plot_prediction_drift.py
  docs/source/checks/nlp/train_test_validation/plot_label_drift.py
  docs/source/checks/vision/data_integrity/plot_property_label_correlation.py
  docs/source/checks/vision/train_test_validation/plot_image_property_drift.py
  docs/source/checks/vision/train_test_validation/plot_property_label_correlation_change.py
  tests/nlp/checks/data_integrity/text_property_outliers_test.py
Labels: documentation, nlp

#2468 Added properties and metadata guides
  deepchecks/nlp/checks/data_integrity/text_property_outliers.py
  deepchecks/nlp/text_data.py
  deepchecks/vision/suites/default_suites.py
  docs/source/checks/nlp/data_integrity/plot_property_label_correlation.py
  docs/source/checks/nlp/data_integrity/plot_text_property_outliers.py
  docs/source/checks/nlp/model_evaluation/plot_prediction_drift.py
  docs/source/checks/nlp/train_test_validation/plot_label_drift.py
  docs/source/nlp/tutorials/other/nlp_metadata.rst
  docs/source/nlp/tutorials/other/nlp_properties.rst
  docs/source/vision/usage_guides/vision_properties.rst
  tests/nlp/checks/data_integrity/text_property_outliers_test.py
  tests/nlp/test_text_data.py
Labels: documentation, nlp

#2473 Remove failing check
  tests/vision/base/test_suite.py
Labels: bug

#2470 Noam/dee 511 write check docs traintestperformance
  docs/source/checks/nlp/model_evaluation/plot_single_dataset_performance.py
  docs/source/checks/nlp/model_evaluation/plot_train_test_performance.py
  docs/source/checks/nlp/train_test_validation/plot_property_drift.py
  docs/source/checks/tabular/model_evaluation/plot_single_dataset_performance.py
  docs/source/checks/tabular/model_evaluation/plot_train_test_performance.py
Labels: documentation
