Repository deepchecks/deepchecks, pull requests merged in 2023-12, with the labels that each got.

#2703 Vulnerability issues fix by Synk
  .github/workflows/build.yml
  docs/requirements.txt
  requirements/dev-requirements.txt
  requirements/nlp-requirements.txt
  tests/nlp/test_text_data.py
  tests/vision/base/test_suite.py
Labels: ci

#2699 docs: fix typos in README.md [skip ci]
  README.md
Labels: documentation

#2698 :zap: code optimization for cleaning special chars from string
  deepchecks/nlp/utils/text_embeddings.py
Labels: feature

#2709 change_weak_segments_na_logic
  deepchecks/utils/abstracts/weak_segment_abstract.py
  deepchecks/utils/dataframes.py
  tests/nlp/checks/model_evaluation/weak_segment_performance_test.py
Labels: bug

#2705 weak segment should have maximum of 1 category
  deepchecks/nlp/checks/data_integrity/under_annotated_segments.py
  deepchecks/nlp/checks/model_evaluation/weak_segments_performance.py
  deepchecks/tabular/checks/model_evaluation/weak_segments_performance.py
  deepchecks/utils/abstracts/weak_segment_abstract.py
  deepchecks/vision/checks/model_evaluation/weak_segments_performance.py
  tests/nlp/checks/model_evaluation/weak_segment_performance_test.py
Labels: feature

#2716 remove ipython req
  requirements/requirements.txt
Labels: ci

#2717 improved documentation
  deepchecks/core/suite.py
Labels: documentation
