Repository deepchecks/deepchecks, pull requests merged in 2023-01, with the labels that each got.

#2239 fix typo
  docs/source/getting-started/installation.rst
Labels: documentation

#2226 Implement PerformanceDisparityReport (#2225)
  deepchecks/tabular/checks/model_evaluation/__init__.py
  deepchecks/tabular/checks/model_evaluation/performance_bias.py
  docs/source/checks/tabular/model_evaluation/plot_performance_bias.py
  tests/tabular/checks/model_evaluation/performance_bias_test.py
Labels: feature

#2245 Does not copy dataset if n_samples is none
  deepchecks/tabular/checks/data_integrity/outlier_sample_detection.py
  deepchecks/tabular/checks/model_evaluation/unused_features.py
  deepchecks/tabular/checks/model_evaluation/weak_segments_performance.py
  deepchecks/tabular/checks/train_test_validation/multivariate_drift.py
  deepchecks/tabular/checks/train_test_validation/whole_dataset_drift.py
  deepchecks/tabular/dataset.py
  deepchecks/tabular/suite.py
  deepchecks/tabular/utils/feature_importance.py
  tests/base/dataset_test.py
  tests/conftest.py
  tests/tabular/suites/test_suites.py
Labels: refactoring

#2244 common calculation for default properties
  deepchecks/swindler_detection/README.rst
  deepchecks/vision/_shared_docs.py
  deepchecks/vision/checks/data_integrity/abstract_property_outliers.py
  deepchecks/vision/checks/data_integrity/image_property_outliers.py
  deepchecks/vision/checks/data_integrity/label_property_outliers.py
  deepchecks/vision/checks/data_integrity/property_label_correlation.py
  deepchecks/vision/checks/model_evaluation/class_performance.py
  deepchecks/vision/checks/model_evaluation/confusion_matrix.py
  deepchecks/vision/checks/model_evaluation/mean_average_precision_report.py
  deepchecks/vision/checks/model_evaluation/mean_average_recall_report.py
  deepchecks/vision/checks/model_evaluation/simple_model_comparison.py
  deepchecks/vision/checks/model_evaluation/single_dataset_performance.py
  deepchecks/vision/checks/model_evaluation/train_test_prediction_drift.py
  deepchecks/vision/checks/model_evaluation/weak_segments_performance.py
  deepchecks/vision/checks/train_test_validation/heatmap_comparison.py
  deepchecks/vision/checks/train_test_validation/image_dataset_drift.py
  deepchecks/vision/checks/train_test_validation/image_property_drift.py
  deepchecks/vision/checks/train_test_validation/new_labels.py
  deepchecks/vision/checks/train_test_validation/property_label_correlation_change.py
  deepchecks/vision/checks/train_test_validation/train_test_label_drift.py
  deepchecks/vision/datasets/detection/coco_tensorflow.py
  deepchecks/vision/datasets/detection/mask.py
  deepchecks/vision/suite.py
  deepchecks/vision/suites/default_suites.py
  deepchecks/vision/utils/image_properties.py
  deepchecks/vision/vision_data/batch_wrapper.py
  tests/vision/base/test_suite.py
  tests/vision/checks/data_integrity/image_property_outliers_test.py
  tests/vision/checks/data_integrity/property_label_correlation_test.py
  tests/vision/checks/train_test_validation/heatmap_comparison_test.py
  tests/vision/checks/train_test_validation/image_dataset_drift_test.py
  tests/vision/checks/train_test_validation/property_label_correlation_change_test.py
  tests/vision/utils_tests/properties_utils_tests.py
Labels: feature, vision

#2249 fix some type hints
  deepchecks/utils/distribution/drift.py
  deepchecks/utils/distribution/plot.py
Labels: refactoring

#2250 Fix PerformanceBias's documentation example: fix indent and fix ZeroDivision warning
  docs/source/checks/tabular/model_evaluation/plot_performance_bias.py
Labels: documentation, bug

#2252 ignore na default in label drift
  deepchecks/tabular/checks/train_test_validation/train_test_label_drift.py
Labels: feature, tabular

#2255 Rename category mismatch to new category and update display
  .github/workflows/build.yml
  deepchecks/checks.py
  deepchecks/tabular/checks/__init__.py
  deepchecks/tabular/checks/train_test_validation/__init__.py
  deepchecks/tabular/checks/train_test_validation/category_mismatch_train_test.py
  deepchecks/tabular/checks/train_test_validation/new_category_train_test.py
  deepchecks/tabular/suites/default_suites.py
  deepchecks/tabular/utils/messages.py
  docs/source/checks/tabular/train_test_validation/plot_new_category_train_test.py
  tests/base/test_tabular_deprecation_warnings.py
  tests/examples_validation.py
  tests/tabular/checks/train_test_validation/new_category_test.py
  tests/tabular/suites/test_suites.py
Labels: refactoring

#2278 New Issues will be labels with "linear" to get synced
  .github/workflows/label-new-issue.yml
Labels: ci

#2247 percent_of_nulls fig fix
  deepchecks/tabular/checks/data_integrity/percent_of_nulls.py
Labels: bug

#2281 Improve context performance
  deepchecks/tabular/context.py
  deepchecks/tabular/feature_importance.py
  deepchecks/tabular/utils/task_inference.py
  deepchecks/utils/array_math.py
  tests/base/feature_importance_utils_test.py
  tests/tabular/test_dummy_model.py
  tests/utils/metrics_test.py
  tests/utils/test_task_inference.py
Labels: refactoring

#2283 Refactor check plots
  benchmarks/vision_bench.py
  deepchecks/vision/datasets/classification/mnist_tensorflow.py
  deepchecks/vision/datasets/classification/mnist_torch.py
  deepchecks/vision/datasets/detection/coco_tensorflow.py
  deepchecks/vision/metrics_utils/custom_scorer.py
  deepchecks/vision/utils/test_utils.py
  docs/source/checks/vision/data_integrity/plot_image_property_outliers.py
  docs/source/checks/vision/data_integrity/plot_label_property_outliers.py
  docs/source/checks/vision/data_integrity/plot_property_label_correlation.py
  docs/source/checks/vision/model_evaluation/plot_class_performance.py
  docs/source/checks/vision/model_evaluation/plot_model_error_analysis.py
  docs/source/checks/vision/model_evaluation/plot_robustness_report.py
  docs/source/checks/vision/model_evaluation/plot_simple_model_comparison.py
  docs/source/checks/vision/model_evaluation/plot_single_dataset_performance.py
  docs/source/checks/vision/model_evaluation/plot_train_test_prediction_drift.py
  docs/source/checks/vision/train_test_validation/plot_heatmap_comparison.py
  docs/source/checks/vision/train_test_validation/plot_property_label_correlation_change.py
  docs/source/checks/vision/train_test_validation/plot_train_test_label_drift.py
  examples/examples_metrics_guide.py
  examples/vision/precomputed_predictions_examples.py
  spelling-allowlist.txt
  tests/vision/base/test_suite.py
  tests/vision/base/test_vision_data.py
  tests/vision/checks/train_test_validation/new_labels_test.py
  tests/vision/checks/train_test_validation/property_label_correlation_change_test.py
  tests/vision/datasets/test_mnist_tf.py
  tests/vision/datasets/test_mnist_torch.py
  tests/vision/gpu_tests/full_suite_test.py
  tests/vision/vision_conftest.py
Labels: feature

#2288 Fix all train_test_validation checks
  docs/source/checks/vision/model_evaluation/plot_image_segment_performance.py
  docs/source/checks/vision/model_evaluation/plot_model_error_analysis.py
  docs/source/checks/vision/model_evaluation/plot_robustness_report.py
  docs/source/checks/vision/train_test_validation/plot_heatmap_comparison.py
  docs/source/checks/vision/train_test_validation/plot_image_dataset_drift.py
  docs/source/checks/vision/train_test_validation/plot_image_property_drift.py
  docs/source/checks/vision/train_test_validation/plot_new_labels.py
  docs/source/checks/vision/train_test_validation/plot_property_label_correlation_change.py
  docs/source/checks/vision/train_test_validation/plot_similar_image_leakage.py
  docs/source/checks/vision/train_test_validation/plot_train_test_label_drift.py
Labels: feature, vision

#2280 [issue-2253][Vision Renewed] vision conftest fix
  tests/base/check_test.py
  tests/base/feature_importance_utils_test.py
  tests/base/test_tabular_deprecation_warnings.py
  tests/common.py
  tests/conftest.py
  tests/tabular/checks/integrity/class_imbalance_test.py
  tests/tabular/checks/model_evaluation/single_dataset_performance_test.py
  tests/tabular/checks/model_evaluation/weak_segments_performance_test.py
  tests/tabular/checks/train_test_validation/multivariate_drift_test.py
  tests/tabular/conftest.py
  tests/tabular/suites/test_suites.py
  tests/tabular/test_datasets.py
  tests/tabular/test_dummy_model.py
  tests/utils/metrics_test.py
  tests/utils/preprocessing_test.py
  tests/vision/__init__.py
  tests/vision/base/test_context.py
  tests/vision/base/test_suite.py
  tests/vision/base/test_vision_data.py
  tests/vision/checks/data_integrity/label_property_outliers_test.py
  tests/vision/checks/model_evaluation/class_performance_test.py
  tests/vision/checks/model_evaluation/confusion_matrix_test.py
  tests/vision/checks/model_evaluation/mean_average_precision_report_test.py
  tests/vision/checks/model_evaluation/single_dataset_performance_test.py
  tests/vision/conftest.py
  tests/vision/datasets/test_coco_tensorflow.py
  tests/vision/datasets/test_coco_torch.py
  tests/vision/datasets/test_mask.py
  tests/vision/datasets/test_mnist_torch.py
  tests/vision/gpu_tests/full_suite_test.py
  tests/vision/utils_tests/label_prediction_properties_test.py
  tests/vision/utils_tests/properties_utils_tests.py
Labels: refactoring, bug

#2289 Add head() to VisionData
  deepchecks/vision/base_checks.py
  deepchecks/vision/checks/data_integrity/abstract_property_outliers.py
  deepchecks/vision/checks/data_integrity/property_label_correlation.py
  deepchecks/vision/checks/model_evaluation/confusion_matrix.py
  deepchecks/vision/checks/model_evaluation/train_test_prediction_drift.py
  deepchecks/vision/checks/train_test_validation/heatmap_comparison.py
  deepchecks/vision/checks/train_test_validation/image_property_drift.py
  deepchecks/vision/checks/train_test_validation/new_labels.py
  deepchecks/vision/checks/train_test_validation/property_label_correlation_change.py
  deepchecks/vision/checks/train_test_validation/train_test_label_drift.py
  deepchecks/vision/datasets/detection/coco_torch.py
  deepchecks/vision/fonts/quicksand/Quicksand-Bold.otf
  deepchecks/vision/fonts/quicksand/Quicksand-Regular.otf
  deepchecks/vision/fonts/quicksand/SIL Open Font License.txt
  deepchecks/vision/metrics_utils/scorers.py
  deepchecks/vision/suite.py
  deepchecks/vision/utils/image_functions.py
  deepchecks/vision/utils/test_utils.py
  deepchecks/vision/vision_data/__init__.py
  deepchecks/vision/vision_data/batch_wrapper.py
  deepchecks/vision/vision_data/utils.py
  deepchecks/vision/vision_data/vision_data.py
  tests/vision/base/test_vision_data.py
  tests/vision/checks/train_test_validation/new_labels_test.py
  tests/vision/checks/train_test_validation/property_label_correlation_change_test.py
  tests/vision/conftest.py
  tests/vision/datasets/test_coco_tensorflow.py
Labels: feature

#2282 vision docs
  docs/source/user-guide/vision/quickstarts/plot_classification_tutorial.py
  docs/source/user-guide/vision/quickstarts/plot_detection_tutorial.py
  docs/source/user-guide/vision/quickstarts/plot_simple_classification_tutorial.py
Labels: documentation

#2291 vision data and supported tasks and formats
  deepchecks/vision/__init__.py
  deepchecks/vision/datasets/classification/mnist_tensorflow.py
  deepchecks/vision/datasets/classification/mnist_torch.py
  deepchecks/vision/datasets/detection/coco_tensorflow.py
  deepchecks/vision/datasets/detection/coco_torch.py
  deepchecks/vision/datasets/detection/mask.py
  deepchecks/vision/datasets/segmentation/segmentation_coco.py
  deepchecks/vision/utils/test_utils.py
  deepchecks/vision/vision_data/vision_data.py
  docs/source/user-guide/index.rst
  docs/source/user-guide/vision/VisionData.rst
  docs/source/user-guide/vision/data-classes/ClassificationData.rst
  docs/source/user-guide/vision/data-classes/DetectionData.rst
  docs/source/user-guide/vision/data-classes/SegmentationData.rst
  docs/source/user-guide/vision/data-classes/VisionData.rst
  docs/source/user-guide/vision/data-classes/index.rst
  docs/source/user-guide/vision/supported_tasks_and_formats.rst
  tests/vision/base/test_vision_data.py
  tests/vision/conftest.py
Labels: documentation, vision

#2292 Metric guide & model_eval checks refactor
  deepchecks/vision/datasets/classification/mnist_torch.py
  deepchecks/vision/metrics_utils/__init__.py
  deepchecks/vision/metrics_utils/custom_metric.py
  deepchecks/vision/metrics_utils/scorers.py
  deepchecks/vision/suites/README.rst
  docs/source/checks/vision/data_integrity/plot_property_label_correlation.py
  docs/source/checks/vision/model_evaluation/plot_class_performance.py
  docs/source/checks/vision/model_evaluation/plot_confusion_matrix.py
  docs/source/checks/vision/model_evaluation/plot_mean_average_precision_report.py
  docs/source/checks/vision/model_evaluation/plot_mean_average_recall_report.py
  docs/source/checks/vision/model_evaluation/plot_simple_model_comparison.py
  docs/source/checks/vision/model_evaluation/plot_single_dataset_performance.py
  docs/source/checks/vision/model_evaluation/plot_train_test_prediction_drift.py
  docs/source/checks/vision/model_evaluation/plot_weak_segments_performance.py
  docs/source/user-guide/general/metrics_guide.rst
  examples/examples_metrics_guide.py
  tests/vision/checks/model_evaluation/single_dataset_performance_test.py
  tests/vision/utils_tests/metrics_test.py
Labels: feature, vision

#2295 segmentation tutorial
  deepchecks/vision/datasets/segmentation/segmentation_coco.py
  docs/source/user-guide/vision/quickstarts/plot_classification_tutorial.py
  docs/source/user-guide/vision/quickstarts/plot_detection_tutorial.py
  docs/source/user-guide/vision/quickstarts/plot_segmentation_tutorial.py
Labels: documentation, vision

#2293 Warning Typo Fix
  deepchecks/core/serialization/suite_result/html.py
  deepchecks/tabular/utils/task_inference.py
Labels: bug

#2298 Nb/docs/vision docs arrange
  deepchecks/utils/ipython.py
  deepchecks/vision/utils/image_properties.py
  deepchecks/vision/vision_data/format_validators.py
  deepchecks/vision/vision_data/utils.py
  deepchecks/vision/vision_data/vision_data.py
  docs/source/user-guide/general/metrics_guide.rst
  docs/source/user-guide/index.rst
  docs/source/user-guide/tabular/tutorials/plot_add_a_custom_check.py
  docs/source/user-guide/vision/VisionData.rst
  docs/source/user-guide/vision/custom_check_templates.rst
  docs/source/user-guide/vision/quickstarts/README.txt
  docs/source/user-guide/vision/tutorials/plot_classification_tutorial.py
  docs/source/user-guide/vision/tutorials/plot_custom_checks.py
  docs/source/user-guide/vision/tutorials/plot_custom_task_tutorial.py
  docs/source/user-guide/vision/tutorials/plot_detection_tutorial.py
  docs/source/user-guide/vision/tutorials/plot_extractors_validating.py
  docs/source/user-guide/vision/tutorials/plot_segmentation_tutorial.py
  docs/source/user-guide/vision/tutorials/plot_simple_classification_tutorial.py
  docs/source/user-guide/vision/tutorials/tomato-detection/train.py
  docs/source/user-guide/vision/using_precomputed_predictions_vision.rst
  docs/source/user-guide/vision/vision_properties.rst
  examples/vision/precomputed_predictions_examples.py
  examples/vision/static_properties_example.py
  tests/vision/checks/model_evaluation/class_performance_test.py
  tests/vision/checks/train_test_validation/property_label_correlation_change_test.py
Labels: documentation, vision

#2303 remove top 5 + some name changes
  .github/workflows/build.yml
  deepchecks/core/reduce_classes.py
  deepchecks/tabular/_shared_docs.py
  tests/tabular/checks/integrity/percent_of_nulls_test.py
  tests/tabular/checks/train_test_validation/train_test_feature_drift_test.py
Labels: feature

#2307 Vision docs fixes
  deepchecks/utils/gower_distance.py
  deepchecks/vision/checks/train_test_validation/image_dataset_drift.py
  deepchecks/vision/datasets/classification/__init__.py
  deepchecks/vision/datasets/detection/__init__.py
  deepchecks/vision/datasets/detection/coco_tensorflow.py
  deepchecks/vision/datasets/detection/coco_torch.py
  deepchecks/vision/datasets/detection/mask.py
  deepchecks/vision/metrics_utils/custom_scorer.py
  deepchecks/vision/suites/default_suites.py
  deepchecks/vision/vision_data/simple_classification_data.py
  docs/source/api/deepchecks.tabular.rst
  docs/source/conf.py
  docs/source/getting-started/welcome.rst
  docs/source/user-guide/general/metrics_guide.rst
  docs/source/user-guide/tabular/dataset_object.rst
  docs/source/user-guide/vision/supported_tasks_and_formats.rst
  docs/source/user-guide/vision/tutorials/plot_classification_tutorial.py
  docs/source/user-guide/vision/tutorials/plot_custom_checks.py
  docs/source/user-guide/vision/tutorials/plot_detection_tutorial.py
  docs/source/user-guide/vision/tutorials/plot_segmentation_tutorial.py
  docs/source/user-guide/vision/vision_properties.rst
Labels: documentation

#2310 Production suite
  deepchecks/suites.py
  deepchecks/tabular/suites/README.rst
  deepchecks/tabular/suites/__init__.py
  deepchecks/tabular/suites/default_suites.py
  tests/tabular/suites/test_suites.py
Labels: feature

#2308 Correctly spell supported with two p's
  deepchecks/tabular/checks/model_evaluation/boosting_overfit.py
  docs/source/getting-started/welcome.rst
  tests/utils/test_string_utils.py
Labels: documentation, bug

#2312 0.11.0 bump
  docs/source/_static/switcher.json
Labels: feature

#2313 aggregation method to be able to be set to None (left 'none' in for now for version stuff, will remove later)
  deepchecks/core/reduce_classes.py
  deepchecks/tabular/_shared_docs.py
  deepchecks/tabular/checks/data_integrity/percent_of_nulls.py
  deepchecks/tabular/checks/model_evaluation/train_test_prediction_drift.py
  deepchecks/tabular/checks/train_test_validation/new_category_train_test.py
  deepchecks/tabular/checks/train_test_validation/train_test_feature_drift.py
  deepchecks/vision/checks/model_evaluation/train_test_prediction_drift.py
  deepchecks/vision/checks/train_test_validation/image_property_drift.py
  deepchecks/vision/checks/train_test_validation/train_test_label_drift.py
  tests/tabular/checks/integrity/percent_of_nulls_test.py
  tests/tabular/checks/train_test_validation/train_test_feature_drift_test.py
  tests/vision/checks/train_test_validation/image_property_drift_test.py
Labels: feature
