Repository deepchecks/deepchecks, pull requests merged in 2023-06, with the labels that each got.

#2572 Fix the property drift check name and others various fixes
  .gitignore
  deepchecks/analytics/anonymous_telemetry.py
  deepchecks/nlp/checks/data_integrity/unknown_tokens.py
  deepchecks/nlp/checks/train_test_validation/property_drift.py
  docs/source/nlp/tutorials/quickstarts/plot_multi_label_classification.py
  docs/source/nlp/tutorials/quickstarts/plot_text_classification.py
  spelling-allowlist.txt
Labels: bug

#2575 [MON-2340] moved airbnb files to s3
  deepchecks/tabular/datasets/regression/airbnb.py
Labels: refactoring

#2576 Nb/feat/special chars check
  benchmarks/vision_bench.py
  deepchecks/core/serialization/common.py
  deepchecks/core/serialization/suite_result/html.py
  deepchecks/core/serialization/suite_result/widget.py
  deepchecks/nlp/checks/data_integrity/special_characters.py
  deepchecks/nlp/checks/data_integrity/text_duplicates.py
  deepchecks/nlp/checks/data_integrity/text_property_outliers.py
  deepchecks/nlp/suites/default_suites.py
  deepchecks/nlp/text_data.py
  deepchecks/tabular/checks/model_evaluation/model_info.py
  deepchecks/utils/abstracts/data_duplicates.py
  deepchecks/utils/abstracts/train_test_samples_mix.py
  deepchecks/utils/dataframes.py
  deepchecks/vision/checks/data_integrity/abstract_property_outliers.py
  docs/source/checks/nlp/data_integrity/plot_special_characters.py
  tests/nlp/checks/data_integrity/special_characters_test.py
  tests/nlp/checks/data_integrity/text_duplicates_test.py
  tests/nlp/checks/model_evaluation/weak_segment_performance_test.py
  tests/nlp/utils/test_properties.py
  tests/tabular/checks/integrity/data_duplicate_test.py
  tests/tabular/checks/train_test_validation/train_test_samples_mix_test.py
  tests/utils/test_outliers.py
Labels: feature

#2574 Added description and URL for text properties in plots
  deepchecks/nlp/checks/train_test_validation/property_drift.py
  deepchecks/nlp/utils/nlp_plot.py
  deepchecks/nlp/utils/text_properties.py
  deepchecks/utils/abstracts/feature_drift.py
  docs/source/nlp/usage_guides/nlp_properties.rst
Labels: feature

#2577 [DOCS] Update readme (unify testing, ci, monitoring)
  README.md
  docs/source/_static/images/general/deepchecks-ci-checks.png
  docs/source/_static/images/general/join-our-slack-community.png
  docs/source/_static/images/general/monitoring-app-ui.gif
  docs/source/_static/images/readme/cont_validation_dark.png
  docs/source/_static/images/readme/cont_validation_light.png
Labels: documentation

#2580 [DOCS] Update Readme
  README.md
Labels: documentation

#2573 Embed long documents with openai
  deepchecks/nlp/checks/data_integrity/unknown_tokens.py
  deepchecks/nlp/text_data.py
  deepchecks/nlp/utils/text_embeddings.py
  deepchecks/nlp/utils/text_properties.py
  requirements/nlp-prop-requirements.txt
  requirements/nlp-requirements.txt
  spelling-allowlist.txt
Labels: feature

#2579 take properties type from built in dict and not from user.
  deepchecks/nlp/datasets/classification/just_dance_comment_analysis.py
  deepchecks/nlp/datasets/classification/tweet_emotion.py
  deepchecks/nlp/datasets/token_classification/scierc_ner.py
  deepchecks/nlp/text_data.py
  deepchecks/nlp/utils/text_properties.py
  tests/nlp/test_text_data.py
Labels: feature

#2584 replace airbnb link
  deepchecks/tabular/datasets/regression/airbnb.py
Labels: refactoring

#2583 Nb/bug/small updates multi lang usecase
  deepchecks/nlp/checks/data_integrity/text_property_outliers.py
  deepchecks/nlp/input_validations.py
  deepchecks/nlp/suites/default_suites.py
  docs/source/checks/nlp/data_integrity/plot_text_property_outliers.py
  docs/source/nlp/tutorials/quickstarts/plot_text_classification.py
  tests/nlp/checks/data_integrity/text_property_outliers_test.py
Labels: bug

#2585 Noam/address null properties
  deepchecks/nlp/datasets/classification/just_dance_comment_analysis.py
  deepchecks/nlp/utils/text_properties.py
  docs/source/checks/nlp/data_integrity/plot_text_property_outliers.py
  docs/source/checks/nlp/train_test_validation/plot_property_drift.py
  docs/source/nlp/usage_guides/nlp_properties.rst
  tests/nlp/checks/train_test_validation/property_drift_test.py
Labels: documentation

#2581 Fix bugs in properties
  deepchecks/nlp/utils/text_properties.py
  tests/nlp/utils/test_properties.py
Labels: bug, nlp

#2587 0.17.x update to main
  VERSION
  docs/source/_static/switcher.json
Labels: feature

#2586 [MON-2260] 'un_numpy' func fix
  deepchecks/utils/dataframes.py
  spelling-allowlist.txt
Labels: bug

#2589 Nb/docs/small fixes
  docs/source/general/concepts/when_should_you_use.rst
  docs/source/getting-started/welcome.rst
  docs/source/nlp/index.rst
  docs/source/nlp/tutorials/quickstarts/plot_multi_label_classification.py
  docs/source/nlp/tutorials/quickstarts/plot_text_classification.py
  docs/source/nlp/tutorials/quickstarts/plot_token_classification.py
Labels: documentation

#2592 bump hotfix version
  VERSION
Labels: ci

#2593 [DOCS] Update Readme
  README.md
  docs/source/_static/images/general/model_evaluation_suite.gif
  docs/source/_static/images/readme/cont_validation_dark.png
  docs/source/_static/images/readme/cont_validation_light.png
  docs/source/_static/images/readme/deepchecks_continuous_validation_dark.png
  docs/source/_static/images/readme/deepchecks_continuous_validation_light.png
  docs/source/_static/images/readme/model-evaluation-suite.gif
Labels: documentation

#2594 Fix new albumentations issue
  docs/source/vision/tutorials/other/plot_custom_task_tutorial.py
  requirements/dev-requirements.txt
Labels: bug

#2596 [DOCS] Update Continuous Validation in Welcome
  docs/source/_static/images/general/deepchecks-testing-logo.svg
  docs/source/_static/images/general/model-evaluation-suite.gif
  docs/source/_static/images/general/nlp-checks.gif
  docs/source/_static/images/welcome/ci_cd_title.png
  docs/source/_static/images/welcome/ci_tile.png
  docs/source/_static/images/welcome/deepchecks_continuous_validation_light.png
  docs/source/_static/images/welcome/monitoring_tile.png
  docs/source/_static/images/welcome/monitoring_title.png
  docs/source/_static/images/welcome/research_title.png
  docs/source/_static/images/welcome/testing_phases_in_pipeline.png
  docs/source/_static/images/welcome/testing_phases_in_pipeline_with_tiles.png
  docs/source/_static/images/welcome/testing_tile.png
  docs/source/conf.py
  docs/source/general/concepts/when_should_you_use.rst
  docs/source/general/index.rst
  docs/source/general/usage/ci_cd.rst
  docs/source/general/usage/showing_results.rst
  docs/source/getting-started/installation.rst
  docs/source/getting-started/welcome.rst
  docs/source/nlp/index.rst
  docs/source/tabular/index.rst
  docs/source/vision/index.rst
Labels: documentation

#2597 Setting any non-numeric value to nan and tests
  deepchecks/nlp/checks/data_integrity/text_property_outliers.py
  tests/nlp/checks/data_integrity/text_property_outliers_test.py
Labels: bug

#2600 airbnb fixes and improvements
  deepchecks/tabular/datasets/regression/airbnb.py
  tests/tabular/test_datasets.py
Labels: feature

#2601 Bump hotfix version
  VERSION
Labels: ci

#2602 Update README.md
  README.md
Labels: documentation

#2595 Update drift guide for nlp
  docs/source/general/guides/drift_guide.rst
  docs/source/getting-started/installation.rst
Labels: documentation

#2603 multivariate drift fix
  deepchecks/tabular/checks/train_test_validation/multivariate_drift.py
Labels: bug

#2604 Changed model_classes logger warning and made sure tabular only warns once
  deepchecks/nlp/context.py
  deepchecks/tabular/checks/model_evaluation/boosting_overfit.py
  deepchecks/tabular/context.py
Labels: bug

#2609 fix many warnings when using joblib (weak segments)
  deepchecks/analytics/anonymous_telemetry.py
  spelling-allowlist.txt
Labels: bug

#2611 Not raise DeepchecksProcessError for UnderAnnotated + WeakSegments
  deepchecks/nlp/checks/data_integrity/under_annotated_segments.py
  deepchecks/nlp/checks/model_evaluation/weak_segments_performance.py
  deepchecks/utils/abstracts/weak_segment_abstract.py
  tests/nlp/checks/data_integrity/under_annotated_segments_test.py
  tests/nlp/checks/model_evaluation/weak_segment_performance_test.py
Labels: bug

#2606 Added .describe() function to the TextData class
  deepchecks/nlp/text_data.py
  deepchecks/nlp/utils/text_data_plot.py
  deepchecks/utils/plot.py
  docs/source/nlp/usage_guides/text_data_object.rst
  tests/nlp/test_text_data.py
Labels: feature

#2616 Added is_english property & flag to calculate english-only properties on non-english identified samples
  deepchecks/nlp/text_data.py
  deepchecks/nlp/utils/text_properties.py
  tests/nlp/utils/test_properties.py
Labels: feature, nlp
