Repository deepchecks/deepchecks, pull requests merged in 2023-03, with the labels that each got.

#2361 fix for imbalanced classes drift
  deepchecks/utils/distribution/drift.py
  tests/utils/drift_test.py
Labels: feature

#2362 Add large version of airbnb dataset
  deepchecks/tabular/datasets/regression/airbnb.py
Labels: feature

#2363 Fix new label reduce & add 2 reduce functions
  deepchecks/tabular/checks/data_integrity/mixed_nulls.py
  deepchecks/tabular/checks/data_integrity/string_mismatch.py
  deepchecks/tabular/checks/train_test_validation/new_label_train_test.py
  tests/base/display_test.py
  tests/tabular/checks/integrity/mixed_nulls_test.py
  tests/tabular/checks/integrity/string_mismatch_test.py
  tests/tabular/checks/train_test_validation/new_label_test.py
Labels: feature

#2366 defaults for single_dataset_performance.py
  deepchecks/core/reduce_classes.py
  deepchecks/tabular/checks/model_evaluation/single_dataset_performance.py
  tests/tabular/checks/model_evaluation/single_dataset_performance_test.py
  tests/tabular/test_dummy_model.py
Labels: feature

#2360 changed plotly version to the latest
  docs/source/user-guide/general/showing_results.rst
  requirements/requirements.txt
Labels: bug

#2367 Solve issue with pps inferring label type from dtype
  .github/workflows/build.yml
  deepchecks/tabular/checks/data_integrity/feature_label_correlation.py
  deepchecks/tabular/checks/data_integrity/identifier_label_correlation.py
  deepchecks/tabular/checks/train_test_validation/feature_label_correlation_change.py
  spelling-allowlist.txt
  tests/tabular/checks/train_test_validation/feature_label_correlation_test.py
Labels: bug

#2368 fix issue with reduce for integrity check
  deepchecks/core/reduce_classes.py
  tests/tabular/checks/integrity/mixed_nulls_test.py
Labels: bug

#2365 deepchecks properties + weak segments + label correlation
  deepchecks/core/check_utils/feature_label_correlation_utils.py
  deepchecks/nlp/checks/__init__.py
  deepchecks/nlp/checks/data_integrity/__init__.py
  deepchecks/nlp/checks/data_integrity/property_label_correlation.py
  deepchecks/nlp/checks/model_evaluation/__init__.py
  deepchecks/nlp/checks/model_evaluation/weak_segments_performance.py
  deepchecks/nlp/context.py
  deepchecks/nlp/datasets/classification/tweet_emotion.py
  deepchecks/nlp/text_data.py
  deepchecks/nlp/utils/text_properties.py
  deepchecks/tabular/checks/model_evaluation/boosting_overfit.py
  deepchecks/vision/checks/data_integrity/property_label_correlation.py
  makefile
  tests/nlp/checks/data_integrity/__init__.py
  tests/nlp/checks/data_integrity/property_label_correlation_test.py
  tests/nlp/checks/model_evaluation/weak_segment_performance_test.py
  tests/nlp/checks/train_test_validation/train_test_label_drift_test.py
  tests/nlp/conftest.py
  tests/nlp/test_text_data.py
Labels: feature

#2370 Mixed null reduce now ignores a single null type
  deepchecks/tabular/checks/data_integrity/mixed_nulls.py
  tests/tabular/checks/integrity/mixed_nulls_test.py
Labels: bug

#2371 Removed unused files from nlp-base
  deepchecks/nlp/checks/__init__.py
  deepchecks/nlp/checks/train_test_validation/__init__.py
  deepchecks/nlp/checks/train_test_validation/keyword_frequency_drift.py
  deepchecks/nlp/context.py
  deepchecks/nlp/datasets/classification/tweet_emotion.py
  deepchecks/nlp/suites/__init__.py
  deepchecks/nlp/suites/default_suites.py
  deepchecks/nlp/utils/__init__.py
  deepchecks/nlp/utils/embeddings_display.py
  tests/nlp/checks/model_evaluation/weak_segment_performance_test.py
  tests/nlp/checks/train_test_validation/keyword_frequency_drift_test.py
  tests/nlp/conftest.py
  tests/nlp/test_context.py
  tests/nlp/test_datasets.py
  tests/nlp/test_suites.py
Labels: refactoring

#2373 Nlp base final fixes 2
  deepchecks/nlp/checks/__init__.py
  deepchecks/nlp/checks/model_evaluation/__init__.py
  deepchecks/nlp/checks/model_evaluation/weak_segments_performance.py
  deepchecks/nlp/context.py
  deepchecks/nlp/datasets/classification/tweet_emotion.py
  deepchecks/nlp/suites/default_suites.py
  deepchecks/nlp/text_data.py
  tests/nlp/checks/model_evaluation/weak_segment_performance_test.py
  tests/nlp/test_text_data.py
Labels: refactoring

#2374 Nlp base final fixes 3
  deepchecks/nlp/checks/data_integrity/property_label_correlation.py
  deepchecks/nlp/checks/model_evaluation/train_test_prediction_drift.py
  deepchecks/nlp/checks/model_evaluation/weak_segments_performance.py
  deepchecks/nlp/checks/train_test_validation/train_test_label_drift.py
  deepchecks/nlp/suites/default_suites.py
  deepchecks/tabular/checks/model_evaluation/train_test_prediction_drift.py
  deepchecks/vision/checks/data_integrity/property_label_correlation.py
  deepchecks/vision/checks/model_evaluation/train_test_prediction_drift.py
  requirements/dev-requirements.txt
  tests/nlp/checks/model_evaluation/train_test_prediction_drift_test.py
  tests/nlp/checks/model_evaluation/weak_segment_performance_test.py
  tests/nlp/checks/train_test_validation/train_test_label_drift_test.py
  tests/vision/checks/data_integrity/property_label_correlation_test.py
Labels: refactoring

#2376 Fixed weak segment performance n_top_thingy thing
  deepchecks/nlp/checks/model_evaluation/weak_segments_performance.py
  deepchecks/vision/checks/model_evaluation/weak_segments_performance.py
  tests/nlp/checks/model_evaluation/weak_segment_performance_test.py
Labels: refactoring

#2372 [DOCS] Update Welcome Docs
  .gitignore
  docs/requirements.txt
  docs/source/_static/images/sphinx_thumbnails/tabular_quickstarts/data_distribution.png
  docs/source/_static/images/sphinx_thumbnails/tabular_quickstarts/data_integrity.png
  docs/source/_static/images/sphinx_thumbnails/tabular_quickstarts/full_suite.png
  docs/source/_static/images/sphinx_thumbnails/tabular_quickstarts/model_evaluation.png
  docs/source/_static/images/welcome/ci_cd_title.png
  docs/source/_static/images/welcome/monitoring_title.png
  docs/source/_static/images/welcome/research_title.png
  docs/source/_static/images/welcome/testing_phases_in_pipeline.png
  docs/source/conf.py
  docs/source/getting-started/index.rst
  docs/source/getting-started/welcome.rst
  docs/source/user-guide/general/when_should_you_use.rst
  docs/source/user-guide/index.rst
  docs/source/user-guide/integrations/hugging_face.rst
  docs/source/user-guide/integrations/junit.rst
  docs/source/user-guide/tabular/quickstarts/README.rst
  docs/source/user-guide/tabular/quickstarts/README.txt
  docs/source/user-guide/tabular/quickstarts/plot_quick_data_integrity.py
  docs/source/user-guide/tabular/quickstarts/plot_quick_model_evaluation.py
  docs/source/user-guide/tabular/quickstarts/plot_quick_train_test_validation.py
  docs/source/user-guide/tabular/quickstarts/plot_quickstart_in_5_minutes.py
Labels: documentation

#2384 fix sorting of new category display
  deepchecks/tabular/checks/train_test_validation/new_category_train_test.py
Labels: bug

#2392 Added and corrected redirects
  docs/source/conf.py
Labels: documentation

#2393 Fix link and address LabelDrift
  docs/source/user-guide/nlp/quickstarts/plot_text_classification.py
Labels: documentation

#2394 updated switcher.json
  docs/source/_static/switcher.json
Labels: refactoring

#2395 Fixing docs size
  docs/source/api/index.rst
  docs/source/conf.py
Labels: documentation

#2396 change aggregation methods
  deepchecks/core/reduce_classes.py
  deepchecks/tabular/_shared_docs.py
  deepchecks/tabular/checks/train_test_validation/feature_drift.py
  docs/source/checks/tabular/train_test_validation/plot_feature_drift.py
  tests/tabular/checks/integrity/mixed_nulls_test.py
  tests/tabular/checks/train_test_validation/feature_drift_test.py
Labels: feature

#2398 [FIX] Update array_math.py
  deepchecks/utils/array_math.py
Labels: feature

#2412 fix ipywdigets error
  deepchecks/core/serialization/check_failure/widget.py
  deepchecks/core/serialization/check_result/widget.py
  deepchecks/core/serialization/dataframe/widget.py
  deepchecks/core/serialization/suite_result/widget.py
Labels: bug

#2409 Add huggingFace properties
  deepchecks/nlp/text_data.py
  deepchecks/nlp/utils/text_properties.py
  docs/source/user-guide/nlp/quickstarts/plot_text_classification.py
  requirements/nlp-prop-requirements.txt
  setup.py
  tests/nlp/test_text_data.py
  tests/nlp/utils/test_properties.py
Labels: feature, nlp

#2410 Added TextPropertyOutliers Check
  deepchecks/nlp/checks/__init__.py
  deepchecks/nlp/checks/data_integrity/__init__.py
  deepchecks/nlp/checks/data_integrity/text_property_outliers.py
  deepchecks/nlp/checks/model_evaluation/weak_segments_performance.py
  deepchecks/nlp/suites/default_suites.py
  deepchecks/nlp/text_data.py
  deepchecks/nlp/utils/nlp_plot.py
  deepchecks/nlp/utils/text_properties.py
  deepchecks/nlp/utils/text_utils.py
  deepchecks/tabular/dataset.py
  deepchecks/tabular/utils/task_inference.py
  deepchecks/utils/distribution/plot.py
  deepchecks/utils/outliers.py
  deepchecks/utils/plot.py
  deepchecks/utils/type_inference.py
  deepchecks/vision/checks/data_integrity/abstract_property_outliers.py
  deepchecks/vision/checks/data_integrity/image_property_outliers.py
  deepchecks/vision/checks/data_integrity/label_property_outliers.py
  tests/nlp/checks/data_integrity/text_property_outliers_test.py
  tests/nlp/checks/test_text_utils.py
  tests/nlp/test_text_data.py
  tests/nlp/utils/test_properties.py
  tests/utils/test_outliers.py
  tests/vision/checks/data_integrity/image_property_outliers_test.py
Labels: feature

#2417 Fix nlp properties runtime
  deepchecks/nlp/datasets/classification/tweet_emotion.py
  deepchecks/nlp/text_data.py
  deepchecks/nlp/utils/text_properties.py
  tests/nlp/checks/data_integrity/property_label_correlation_test.py
  tests/nlp/checks/data_integrity/text_property_outliers_test.py
  tests/nlp/checks/model_evaluation/weak_segment_performance_test.py
  tests/nlp/utils/test_properties.py
Labels: bug

#2425 Recsys overl
  .all-contributorsrc
  README.md
  deepchecks/core/serialization/check_failure/widget.py
  deepchecks/core/serialization/check_result/widget.py
  deepchecks/core/serialization/dataframe/widget.py
  deepchecks/core/serialization/suite_result/widget.py
  deepchecks/nlp/checks/__init__.py
  deepchecks/nlp/checks/data_integrity/__init__.py
  deepchecks/nlp/checks/data_integrity/text_property_outliers.py
  deepchecks/nlp/checks/model_evaluation/weak_segments_performance.py
  deepchecks/nlp/datasets/classification/tweet_emotion.py
  deepchecks/nlp/suites/default_suites.py
  deepchecks/nlp/text_data.py
  deepchecks/nlp/utils/nlp_plot.py
  deepchecks/nlp/utils/text_properties.py
  deepchecks/nlp/utils/text_utils.py
  deepchecks/recommender/context.py
  deepchecks/recommender/dataset.py
  deepchecks/recommender/suites.py
  deepchecks/tabular/base_checks.py
  deepchecks/tabular/checks/model_evaluation/single_dataset_performance.py
  deepchecks/tabular/checks/model_evaluation/weak_segments_performance.py
  deepchecks/tabular/context.py
  deepchecks/tabular/dataset.py
  deepchecks/tabular/suite.py
  deepchecks/tabular/utils/task_inference.py
  deepchecks/tabular/utils/task_type.py
  deepchecks/utils/distribution/plot.py
  deepchecks/utils/outliers.py
  deepchecks/utils/plot.py
  deepchecks/utils/single_sample_metrics.py
  deepchecks/utils/type_inference.py
  deepchecks/vision/checks/data_integrity/abstract_property_outliers.py
  deepchecks/vision/checks/data_integrity/image_property_outliers.py
  deepchecks/vision/checks/data_integrity/label_property_outliers.py
  docs/source/user-guide/nlp/quickstarts/plot_text_classification.py
  requirements/nlp-prop-requirements.txt
  setup.py
  tests/nlp/checks/data_integrity/property_label_correlation_test.py
  tests/nlp/checks/data_integrity/text_property_outliers_test.py
  tests/nlp/checks/model_evaluation/weak_segment_performance_test.py
  tests/nlp/checks/test_text_utils.py
  tests/nlp/test_text_data.py
  tests/nlp/utils/test_properties.py
  tests/utils/test_outliers.py
  tests/vision/checks/data_integrity/image_property_outliers_test.py
Labels: feature

#2428 feature drift reduce output method fix
  deepchecks/tabular/checks/train_test_validation/feature_drift.py
Labels: bug, dev, hotfix

#2429 fix feature importance in feature drift reduce
  deepchecks/core/reduce_classes.py
  deepchecks/tabular/checks/train_test_validation/feature_drift.py
Labels: bug

#2430 fix new_category_train_test.py display
  deepchecks/tabular/checks/train_test_validation/new_category_train_test.py
Labels: bug
