Repository deepchecks/deepchecks, pull requests merged in 2023-10, with the labels that each got.

#2682 Nadav/llm 803 integrate the optimized models in testing package
  deepchecks/nlp/utils/text_properties.py
Labels: feature, nlp

#2683 Part of the vulnerability fixes required by Snyk
  .github/workflows/build.yml
  requirements/dev-requirements.txt
  requirements/requirements.txt
Labels: ci

#2685 Fix CI/CD
  deepchecks/vision/metrics_utils/scorers.py
  tests/vision/base/test_suite.py
Labels: bug

#2686 Bump dev version
  VERSION
Labels: ci
