Repository deepchecks/deepchecks, pull requests merged in 2023-05, with the labels that each got.

#2483 Noam/dee 521 unknown token check
  deepchecks/nlp/checks/__init__.py
  deepchecks/nlp/checks/data_integrity/__init__.py
  deepchecks/nlp/checks/data_integrity/special_characters.py
  deepchecks/nlp/checks/data_integrity/unknown_tokens.py
  deepchecks/nlp/suites/default_suites.py
  requirements/dev-requirements.txt
  spelling-allowlist.txt
  tests/nlp/checks/data_integrity/unknown_tokens_test.py
Labels: feature, nlp

#2484 [DOCS] Update Main Page for New Structure
  .gitignore
  docs/source/general/index.rst
  docs/source/getting-started/welcome.rst
  docs/source/tabular/index.rst
Labels: documentation

#2482 Nb/docs/warnings fix
  deepchecks/core/serialization/suite_result/html.py
  deepchecks/nlp/checks/data_integrity/property_label_correlation.py
  deepchecks/nlp/text_data.py
  deepchecks/tabular/checks/data_integrity/feature_label_correlation.py
  deepchecks/tabular/checks/train_test_validation/feature_label_correlation_change.py
  deepchecks/tabular/suites/default_suites.py
  deepchecks/tabular/utils/validation.py
  deepchecks/utils/docref.py
  deepchecks/vision/README.rst
  deepchecks/vision/checks/data_integrity/property_label_correlation.py
  deepchecks/vision/checks/train_test_validation/property_label_correlation_change.py
  deepchecks/vision/suites/default_suites.py
  docs/source/checks/nlp/model_evaluation/plot_prediction_drift.py
  docs/source/general/guides/metrics_guide.rst
  docs/source/general/integrations/hugging_face.rst
  docs/source/general/usage/customizations/plot_create_a_custom_suite.py
  docs/source/getting-started/installation.rst
  docs/source/index.rst
  docs/source/nlp/index.rst
  docs/source/nlp/tutorials/quickstarts/plot_text_classification.py
  docs/source/nlp/usage_guides/nlp_metadata.rst
  docs/source/nlp/usage_guides/nlp_properties.rst
  docs/source/tabular/index.rst
  docs/source/tabular/tutorials/quickstarts/plot_quickstart_in_5_minutes.py
  docs/source/vision/index.rst
  docs/source/vision/usage_guides/supported_tasks_and_formats.rst
  docs/source/vision/usage_guides/visiondata_object.rst
Labels: documentation

#2490 Update welcome and add link to Deepchecks Monitoring
  LICENSE
  docs/source/getting-started/welcome.rst
Labels: documentation

#2488 add test data docs
  docs/source/nlp/index.rst
  docs/source/nlp/usage_guides/text_data_object.rst
Labels: documentation

#2493 Noam/dee 538 better handle download of nltk
  deepchecks/nlp/checks/data_integrity/unknown_tokens.py
  deepchecks/nlp/utils/text.py
  docs/source/nlp/usage_guides/text_data_object.rst
Labels: bug

#2491 Weak segments refactor + bug fix
  deepchecks/nlp/checks/data_integrity/unknown_tokens.py
  deepchecks/nlp/checks/model_evaluation/weak_segments_performance.py
  deepchecks/nlp/input_validations.py
  deepchecks/nlp/utils/weak_segments.py
  deepchecks/tabular/checks/model_evaluation/weak_segments_performance.py
  deepchecks/utils/abstracts/weak_segment_abstract.py
  deepchecks/utils/dataframes.py
  deepchecks/utils/single_sample_metrics.py
  deepchecks/vision/checks/model_evaluation/weak_segments_performance.py
  deepchecks/vision/metrics_utils/iou_utils.py
  spelling-allowlist.txt
  tests/nlp/checks/model_evaluation/weak_segment_performance_test.py
  tests/tabular/checks/model_evaluation/weak_segments_performance_test.py
  tests/tabular/conftest.py
  tests/vision/checks/model_evaluation/weak_segments_performance_test.py
Labels: bug

#2496 [BUG] added forgotten 'raise' keyword
  deepchecks/nlp/checks/data_integrity/unknown_tokens.py
Labels: bug

#2478 Fixes #2452 Added two new text properties
  deepchecks/nlp/utils/text_properties.py
  docs/source/nlp/usage_guides/nlp_properties.rst
  tests/nlp/checks/train_test_validation/property_drift_test.py
  tests/nlp/test_text_data.py
  tests/nlp/utils/test_properties.py
Labels: feature, nlp

#2494 Noam/dee 505 multilabel with many classes usecase
  deepchecks/nlp/base_checks.py
  deepchecks/nlp/checks/data_integrity/conflicting_labels.py
  deepchecks/nlp/checks/data_integrity/unknown_tokens.py
  deepchecks/nlp/checks/model_evaluation/single_dataset_performance.py
  deepchecks/nlp/checks/model_evaluation/train_test_performance.py
  deepchecks/nlp/context.py
  deepchecks/nlp/suite.py
  tests/nlp/checks/model_evaluation/train_test_performance_test.py
  tests/nlp/test_context.py
  tests/nlp/test_suites.py
Labels: bug

#2504 tabular _DummyModel - allow multi-labels
  deepchecks/tabular/context.py
  tests/nlp/checks/data_integrity/text_property_outliers_test.py
  tests/nlp/checks/data_integrity/unknown_tokens_test.py
  tests/tabular/checks/model_evaluation/weak_segments_performance_test.py
Labels: bug, feature

#2500 Feat/Add Misclassified samples lower than condition to Confusion Matrix Report
  deepchecks/nlp/checks/model_evaluation/confusion_matrix_report.py
  deepchecks/tabular/checks/model_evaluation/confusion_matrix_report.py
  deepchecks/utils/abstracts/confusion_matrix_abstract.py
  docs/source/checks/nlp/model_evaluation/plot_confusion_matrix_report.py
  docs/source/checks/tabular/model_evaluation/plot_confusion_matrix_report.py
  spelling-allowlist.txt
  tests/nlp/checks/model_evaluation/confusion_matrix_test.py
  tests/tabular/checks/model_evaluation/confusion_matrix_report_test.py
Labels: feature

#2506 Improve lang detection
  .gitignore
  deepchecks/nlp/utils/text_properties.py
  requirements/nlp-prop-requirements.txt
  requirements/requirements.txt
  requirements/vision-requirements.txt
  spelling-allowlist.txt
Labels: feature

#2508 Fix api docs
  README.md
  deepchecks/nlp/metric_utils/token_classification.py
  deepchecks/tabular/suites/default_suites.py
  deepchecks/vision/checks/data_integrity/abstract_property_outliers.py
  deepchecks/vision/checks/data_integrity/image_property_outliers.py
  deepchecks/vision/checks/data_integrity/label_property_outliers.py
  deepchecks/vision/checks/data_integrity/property_label_correlation.py
  deepchecks/vision/checks/model_evaluation/prediction_drift.py
  deepchecks/vision/checks/train_test_validation/image_dataset_drift.py
  deepchecks/vision/checks/train_test_validation/image_property_drift.py
  deepchecks/vision/checks/train_test_validation/label_drift.py
  deepchecks/vision/checks/train_test_validation/property_label_correlation_change.py
  deepchecks/vision/suites/default_suites.py
  docs/source/_templates/autosummary/check.rst
  docs/source/checks/nlp/model_evaluation/plot_prediction_drift.py
  docs/source/checks/vision/train_test_validation/plot_new_labels.py
  docs/source/conf.py
  docs/source/general/concepts/when_should_you_use.rst
  docs/source/general/usage/showing_results.rst
  docs/source/getting-started/welcome.rst
  docs/source/nlp/index.rst
  docs/source/nlp/tutorials/quickstarts/README.txt
  docs/source/nlp/tutorials/quickstarts/plot_text_classification.py
  docs/source/tabular/index.rst
  docs/source/tabular/tutorials/quickstarts/README.txt
  docs/source/tabular/usage_guides/dataset_object.rst
  docs/source/vision/index.rst
  docs/source/vision/tutorials/other/README.txt
  docs/source/vision/tutorials/quickstarts/README.txt
  docs/source/vision/usage_guides/supported_tasks_and_formats.rst
  docs/source/vision/usage_guides/visiondata_object.rst
Labels: documentation

#2510 Noam/feature/update default suites
  deepchecks/nlp/checks/model_evaluation/weak_segments_performance.py
  deepchecks/nlp/suites/default_suites.py
  deepchecks/utils/dataframes.py
Labels: feature

#2505 Nb/feat/under annotated checks
  deepchecks/nlp/checks/__init__.py
  deepchecks/nlp/checks/data_integrity/__init__.py
  deepchecks/nlp/checks/data_integrity/under_annotated_segments.py
  deepchecks/nlp/checks/model_evaluation/weak_segments_performance.py
  deepchecks/nlp/suites/default_suites.py
  deepchecks/nlp/text_data.py
  deepchecks/utils/abstracts/weak_segment_abstract.py
  deepchecks/utils/metrics.py
  deepchecks/utils/single_sample_metrics.py
  tests/nlp/checks/data_integrity/under_annotated_segments_test.py
  tests/utils/metrics_test.py
Labels: feature

#2513 under annotated check - support multi label and token classification
  deepchecks/nlp/checks/data_integrity/under_annotated_segments.py
  deepchecks/nlp/datasets/classification/tweet_emotion.py
  deepchecks/nlp/input_validations.py
  deepchecks/nlp/metric_utils/scorers.py
  deepchecks/nlp/utils/data_inference.py
  deepchecks/tabular/metric_utils/scorers.py
  deepchecks/vision/utils/test_utils.py
  tests/nlp/checks/data_integrity/under_annotated_segments_test.py
  tests/nlp/checks/model_evaluation/single_dataset_performance_test.py
  tests/nlp/checks/model_evaluation/train_test_performance_test.py
  tests/nlp/checks/model_evaluation/weak_segment_performance_test.py
  tests/nlp/checks/train_test_validation/property_drift_test.py
  tests/nlp/checks/train_test_validation/text_embeddings_drift_test.py
  tests/nlp/conftest.py
Labels: feature

#2514 [DOCS] Update ci-cd order and fix typos
  docs/source/general/usage/ci_cd.rst
  docs/source/getting-started/installation.rst
  docs/source/getting-started/welcome.rst
Labels: documentation

#2515 small fixes
  .gitignore
  deepchecks/nlp/checks/data_integrity/under_annotated_segments.py
  deepchecks/nlp/checks/model_evaluation/weak_segments_performance.py
Labels: feature

#2518 fix fasttext file path issue
  deepchecks/nlp/utils/text_properties.py
Labels: bug

#2511 [DEE-456] nlp dummy model refactoring
  deepchecks/nlp/context.py
  deepchecks/nlp/input_validations.py
  deepchecks/utils/typing.py
  tests/nlp/checks/data_integrity/under_annotated_segments_test.py
  tests/nlp/checks/model_evaluation/confusion_matrix_test.py
  tests/nlp/checks/model_evaluation/single_dataset_performance_test.py
  tests/nlp/conftest.py
  tests/nlp/test_context.py
  tests/nlp/utils/test_embeddings.py
  tests/tabular/checks/model_evaluation/confusion_matrix_report_test.py
  tests/utils/metrics_test.py
Labels: refactoring

#2521 update main to 0.14.0
  VERSION
  docs/source/_static/switcher.json
Labels: ci, feature

#2516 Plot files under annotated checks
  deepchecks/nlp/checks/data_integrity/under_annotated_segments.py
  deepchecks/nlp/utils/test_utils.py
  docs/source/checks/nlp/data_integrity/plot_under_annotated_metadata_segments.py
  docs/source/checks/nlp/data_integrity/plot_under_annotated_property_segments.py
  docs/source/checks/nlp/model_evaluation/plot_metadata_segments_performance.py
  docs/source/checks/nlp/model_evaluation/plot_property_segments_performance.py
Labels: documentation

#2512 Fixes #2454 Added Readability score and average sentence length text property
  deepchecks/nlp/utils/text_properties.py
  docs/source/nlp/usage_guides/nlp_properties.rst
  tests/nlp/checks/data_integrity/under_annotated_segments_test.py
  tests/nlp/checks/train_test_validation/property_drift_test.py
  tests/nlp/test_text_data.py
  tests/nlp/utils/test_properties.py
Labels: feature

#2522 fix version in docs
  docs/source/conf.py
Labels: bug

#2527 change nlp to beta
  README.md
Labels: documentation

#2528 Changed embeddings to numpy array
  deepchecks/nlp/datasets/classification/tweet_emotion.py
  deepchecks/nlp/input_validations.py
  deepchecks/nlp/text_data.py
  deepchecks/nlp/utils/multivariate_embeddings_drift_utils.py
  deepchecks/nlp/utils/text_embeddings.py
  docs/source/nlp/usage_guides/nlp_embeddings.rst
  tests/nlp/checks/train_test_validation/text_embeddings_drift_test.py
  tests/nlp/test_datasets.py
Labels: refactoring, nlp

#2531 Nb/feat/support multi label
  deepchecks/nlp/checks/data_integrity/conflicting_labels.py
  deepchecks/nlp/checks/model_evaluation/prediction_drift.py
  deepchecks/nlp/checks/train_test_validation/label_drift.py
  deepchecks/nlp/context.py
  deepchecks/nlp/datasets/classification/__init__.py
  deepchecks/nlp/datasets/classification/just_dance_comment_analysis.py
  deepchecks/nlp/datasets/classification/tweet_emotion.py
  deepchecks/nlp/utils/text_properties.py
  deepchecks/utils/abstracts/prediction_drift.py
  deepchecks/utils/builtin_datasets_utils.py
  deepchecks/utils/distribution/preprocessing.py
  tests/nlp/checks/data_integrity/conflicting_labels_test.py
  tests/nlp/checks/model_evaluation/prediction_drift_test.py
  tests/nlp/checks/train_test_validation/label_drift_test.py
  tests/nlp/conftest.py
  tests/nlp/test_datasets.py
Labels: feature

#2533 Added support of token classification to PredictionDrift & LabelDrift
  deepchecks/nlp/checks/model_evaluation/prediction_drift.py
  deepchecks/nlp/checks/train_test_validation/label_drift.py
  deepchecks/nlp/suites/default_suites.py
  deepchecks/utils/distribution/preprocessing.py
  tests/nlp/checks/model_evaluation/prediction_drift_test.py
  tests/nlp/checks/train_test_validation/label_drift_test.py
Labels: feature, nlp

#2525 [DEE-417] do not calculate english-only text properties for not english samples
  .github/workflows/build.yml
  deepchecks/nlp/checks/train_test_validation/property_drift.py
  deepchecks/nlp/utils/text_properties.py
  makefile
  tests/nlp/checks/data_integrity/under_annotated_segments_test.py
  tests/nlp/checks/train_test_validation/property_drift_test.py
  tests/nlp/conftest.py
  tests/nlp/test_datasets.py
  tests/nlp/test_text_data.py
  tests/nlp/utils/test_properties.py
Labels: refactoring

#2486 Update CITATION.cff with JMLR Paper
  CITATION.cff
Labels: documentation

#2538 Extended just dance dataset + small fixes
  deepchecks/nlp/checks/model_evaluation/weak_segments_performance.py
  deepchecks/nlp/context.py
  deepchecks/nlp/datasets/classification/just_dance_comment_analysis.py
  deepchecks/nlp/utils/text_embeddings.py
  deepchecks/nlp/utils/text_properties.py
  deepchecks/tabular/checks/model_evaluation/weak_segments_performance.py
  tests/nlp/checks/model_evaluation/prediction_drift_test.py
  tests/nlp/checks/model_evaluation/weak_segment_performance_test.py
  tests/nlp/checks/train_test_validation/label_drift_test.py
  tests/nlp/conftest.py
  tests/nlp/test_datasets.py
Labels: feature

#2535 Added fasttext to dev-requirements.txt
  requirements/dev-requirements.txt
Labels: bug

#2540 Noam/dee 530 feat improved quickstart for nlp
  deepchecks/nlp/datasets/classification/tweet_emotion.py
  deepchecks/nlp/utils/nlp_plot.py
  docs/source/checks/vision/model_evaluation/plot_prediction_drift.py
  docs/source/general/usage/customizations/plot_create_a_custom_suite.py
  docs/source/nlp/tutorials/quickstarts/plot_text_classification.py
Labels: documentation

#2543 fix set_precision in pandas deprecated
  deepchecks/core/serialization/dataframe/html.py
Labels: bug

#2541 multi label quick start
  deepchecks/nlp/datasets/classification/just_dance_comment_analysis.py
  deepchecks/nlp/suites/default_suites.py
  docs/source/general/usage/customizations/README.txt
  docs/source/nlp/tutorials/quickstarts/plot_multi_label_classification.py
  docs/source/nlp/tutorials/quickstarts/plot_text_classification.py
  docs/source/nlp/usage_guides/supported_tasks.rst
  tests/nlp/checks/model_evaluation/weak_segment_performance_test.py
  tests/nlp/conftest.py
Labels: documentation, nlp

#2536 Fixes #2524 Refactoring of the calculate_default_properties function and adding new text properties
  .gitignore
  deepchecks/nlp/text_data.py
  deepchecks/nlp/utils/__init__.py
  deepchecks/nlp/utils/text_properties.py
  docs/source/checks/nlp/train_test_validation/plot_property_drift.py
  docs/source/nlp/usage_guides/nlp_properties.rst
  docs/source/nlp/usage_guides/text_data_object.rst
  tests/nlp/checks/data_integrity/under_annotated_segments_test.py
  tests/nlp/checks/model_evaluation/weak_segment_performance_test.py
  tests/nlp/checks/train_test_validation/property_drift_test.py
  tests/nlp/test_text_data.py
  tests/nlp/utils/test_properties.py
Labels: feature

#2545 fix reference to nlp in vision
  docs/source/vision/index.rst
Labels: bug

#2546 update version to 0.14.1.dev1
  VERSION
Labels: ci

#2544 [DEE-550] fix - 'dataset.select' mutates provided columns list
  deepchecks/tabular/dataset.py
  tests/nlp/checks/model_evaluation/weak_segment_performance_test.py
  tests/nlp/checks/train_test_validation/property_drift_test.py
Labels: bug

#2548 updated embeddings calculation functions names
  deepchecks/nlp/text_data.py
  deepchecks/nlp/utils/__init__.py
  deepchecks/nlp/utils/text_embeddings.py
  docs/source/nlp/tutorials/quickstarts/plot_text_classification.py
  docs/source/nlp/usage_guides/nlp_embeddings.rst
  tests/nlp/test_text_data.py
  tests/nlp/utils/test_embeddings.py
Labels: refactoring, nlp

#2550 fix deprecated styler method
  deepchecks/core/serialization/dataframe/html.py
Labels: bug

#2553 Fix prediction/label drift for token classification
  deepchecks/nlp/checks/model_evaluation/prediction_drift.py
  deepchecks/nlp/checks/train_test_validation/label_drift.py
  deepchecks/nlp/utils/nlp_plot.py
  deepchecks/nlp/utils/token_classification_utils.py
  tests/nlp/checks/model_evaluation/prediction_drift_test.py
  tests/nlp/checks/train_test_validation/label_drift_test.py
Labels: bug, nlp

#2534 Fixes #2480 Created separation for make file for Windows and Linux
  CONTRIBUTING.rst
Labels: ci

#2556 Fixed bug in TrainTestClassPerformance checks
  deepchecks/core/check_utils/class_performance_utils.py
Labels: bug

#2557 iqr range modification
  deepchecks/nlp/checks/data_integrity/text_property_outliers.py
  deepchecks/utils/outliers.py
  tests/nlp/checks/data_integrity/text_property_outliers_test.py
  tests/utils/test_outliers.py
  tests/vision/checks/data_integrity/label_property_outliers_test.py
Labels: bug

#2558 Add min_samples and n_top_classes to TrainTestPerformance in NLP
  deepchecks/nlp/checks/model_evaluation/train_test_performance.py
  deepchecks/utils/abstracts/train_test_performace.py
  tests/nlp/checks/model_evaluation/train_test_performance_test.py
Labels: feature, nlp

#2563 Missing package name in NLP quickstart
  docs/source/nlp/tutorials/quickstarts/plot_multi_label_classification.py
  docs/source/nlp/tutorials/quickstarts/plot_text_classification.py
Labels: bug

#2560 Nb/bug/weak segments fill na
  deepchecks/nlp/checks/model_evaluation/weak_segments_performance.py
  deepchecks/nlp/context.py
  deepchecks/nlp/input_validations.py
  deepchecks/nlp/text_data.py
  deepchecks/nlp/utils/weak_segments.py
  deepchecks/tabular/checks/model_evaluation/weak_segments_performance.py
  deepchecks/utils/abstracts/weak_segment_abstract.py
  deepchecks/utils/dataframes.py
  deepchecks/utils/type_inference.py
  tests/nlp/checks/data_integrity/under_annotated_segments_test.py
  tests/nlp/checks/model_evaluation/weak_segment_performance_test.py
  tests/nlp/test_text_data.py
  tests/tabular/checks/integrity/columns_info_test.py
  tests/tabular/test_tabular_context.py
Labels: bug

#2561 data duplicates takes a long time for long docs
  deepchecks/nlp/checks/data_integrity/conflicting_labels.py
  deepchecks/nlp/checks/data_integrity/text_duplicates.py
  deepchecks/nlp/checks/train_test_validation/train_test_sample_mix.py
  deepchecks/nlp/utils/text.py
  tests/nlp/checks/data_integrity/conflicting_labels_test.py
  tests/nlp/checks/data_integrity/text_duplicates_test.py
  tests/nlp/checks/train_test_validation/train_test_samples_mix_test.py
Labels: bug

#2567 fix error in pandas 2
  deepchecks/nlp/input_validations.py
Labels: bug

#2530 Recsys base
  deepchecks/recommender/ranking.py
  requirements/requirements.txt
Labels: feature

#2568 reorder checks in suites NLP
  deepchecks/nlp/suites/default_suites.py
  deepchecks/utils/abstracts/label_drift.py
Labels: feature

#2569 long docs unknown tokens takes a long time
  deepchecks/nlp/checks/data_integrity/unknown_tokens.py
  docs/source/checks/nlp/data_integrity/plot_unknown_tokens.py
  spelling-allowlist.txt
  tests/nlp/checks/data_integrity/unknown_tokens_test.py
Labels: bug

#2566 Imrpoved run times of Average Sentence Length and Readability Score
  deepchecks/core/serialization/common.py
  deepchecks/nlp/checks/data_integrity/conflicting_labels.py
  deepchecks/nlp/checks/data_integrity/special_characters.py
  deepchecks/nlp/checks/data_integrity/text_duplicates.py
  deepchecks/nlp/checks/data_integrity/unknown_tokens.py
  deepchecks/nlp/checks/train_test_validation/train_test_sample_mix.py
  deepchecks/nlp/utils/text_properties.py
  deepchecks/tabular/checks/data_integrity/mixed_data_types.py
  deepchecks/utils/strings.py
  docs/source/nlp/tutorials/quickstarts/plot_multi_label_classification.py
  docs/source/nlp/usage_guides/nlp_properties.rst
  tests/nlp/checks/data_integrity/under_annotated_segments_test.py
  tests/nlp/checks/train_test_validation/property_drift_test.py
  tests/nlp/test_text_data.py
  tests/nlp/utils/test_properties.py
  tests/utils/test_string_utils.py
Labels: feature, nlp
