Repository deepchecks/deepchecks, pull requests merged in 2023-08, with the labels that each got.

#2653 more robust nan handling when creating TextData label
  .github/workflows/build.yml
  deepchecks/nlp/input_validations.py
  deepchecks/nlp/task_type.py
  tests/nlp/test_text_data.py
Labels: bug

#2656 switch to better Toxicty model
  .github/workflows/build.yml
  deepchecks/nlp/utils/text_properties.py
  tests/nlp/utils/test_properties.py
Labels: feature

#2661 Corrected grammar in dataset_object.rst
  docs/source/tabular/usage_guides/dataset_object.rst
Labels: documentation

#2654 Adding a new check - frequent substring
  deepchecks/nlp/checks/data_integrity/frequent_substrings.py
  tests/nlp/checks/data_integrity/frequent_substrings_test.py
Labels: feature

#2663 Adding a doc to the new check - frequent substring
  deepchecks/nlp/checks/__init__.py
  deepchecks/nlp/checks/data_integrity/__init__.py
  deepchecks/nlp/suites/default_suites.py
  docs/source/checks/nlp/data_integrity/plot_frequent_substrings.py
Labels: documentation

#2664 calibrate the toxicity model
  deepchecks/nlp/utils/assets/toxicity_calibrator.pkl
  deepchecks/nlp/utils/text_properties.py
Labels: feature

#2665 Slight adjustment to prefer larger segments
  deepchecks/nlp/utils/text_properties.py
  deepchecks/utils/abstracts/weak_segment_abstract.py
  docs/source/checks/nlp/data_integrity/plot_under_annotated_property_segments.py
  docs/source/checks/tabular/model_evaluation/plot_weak_segments_performance.py
  tests/nlp/checks/data_integrity/under_annotated_segments_test.py
  tests/nlp/checks/model_evaluation/weak_segment_performance_test.py
  tests/tabular/checks/model_evaluation/weak_segments_performance_test.py
  tests/vision/checks/model_evaluation/weak_segments_performance_test.py
Labels: feature

#2666 use device_map=auto when accelerate is installed
  deepchecks/nlp/utils/text_properties_models.py
Labels: bug
