Repository deepchecks/deepchecks, pull requests merged in 2023-02, with the labels that each got.

#2311 coverage fix #2
  deepchecks/vision/datasets/detection/coco_torch.py
  makefile
Labels: bug

#2318 fix aggregation type validation in drift
  deepchecks/tabular/checks/model_evaluation/train_test_prediction_drift.py
Labels: bug

#2319 fix missing assets
  MANIFEST.in
Labels: bug, hotfix

#2287 Add first CICD docs
  docs/source/_static/images/cicd/airflow.png
  docs/source/_static/images/cicd/s3_suites.png
  docs/source/user-guide/general/ci_cd.rst
  docs/source/user-guide/index.rst
  examples/cicd/airflow.py
Labels: documentation

#2321 fix numeric lists in ci/cd docs
  docs/source/user-guide/general/ci_cd.rst
Labels: bug

#2322 Improve vision data head display
  deepchecks/core/serialization/abc.py
  deepchecks/core/serialization/html_display.py
  deepchecks/vision/vision_data/vision_data.py
Labels: refactoring

#2324 Add NewCategory to prod suite
  deepchecks/tabular/datasets/regression/airbnb.py
  deepchecks/tabular/suites/default_suites.py
  tests/tabular/suites/test_suites.py
Labels: bug

#2325 Nb/feat/embedding checks
  deepchecks/nlp/utils/__init__.py
  deepchecks/nlp/utils/embeddings_calculator.py
  deepchecks/nlp/utils/embeddings_display.py
Labels: feature, nlp

#2327 Weak segments + label and prediction drift
  deepchecks/nlp/base_checks.py
  deepchecks/nlp/checks/__init__.py
  deepchecks/nlp/checks/model_evaluation/__init__.py
  deepchecks/nlp/checks/model_evaluation/single_dataset_performance.py
  deepchecks/nlp/checks/model_evaluation/weak_segments_performance.py
  deepchecks/nlp/checks/train_test_validation/__init__.py
  deepchecks/nlp/checks/train_test_validation/train_test_label_drift.py
  deepchecks/nlp/checks/train_test_validation/train_test_prediction_drift.py
  deepchecks/nlp/context.py
  deepchecks/nlp/suite.py
  deepchecks/nlp/text_data.py
  deepchecks/nlp/utils/data_inference.py
  deepchecks/nlp/utils/embeddings_calculator.py
  deepchecks/nlp/utils/embeddings_display.py
  deepchecks/tabular/context.py
  deepchecks/utils/validation.py
  deepchecks/vision/checks/model_evaluation/weak_segments_performance.py
  tests/nlp/checks/model_evaluation/single_dataset_performance_test.py
  tests/nlp/test_context.py
  tests/nlp/test_suites.py
  tests/nlp/test_text_data.py
Labels: feature, nlp

#2326 Noam/mon 1644 enable f1 as a default metric
  deepchecks/tabular/metric_utils/scorers.py
Labels: feature

#2329 Add imbalanced drift method
  deepchecks/tabular/checks/model_evaluation/train_test_prediction_drift.py
  deepchecks/tabular/checks/train_test_validation/train_test_feature_drift.py
  deepchecks/tabular/checks/train_test_validation/train_test_label_drift.py
  deepchecks/utils/distribution/drift.py
  deepchecks/utils/distribution/preprocessing.py
  deepchecks/vision/checks/model_evaluation/train_test_prediction_drift.py
  deepchecks/vision/checks/train_test_validation/image_property_drift.py
  deepchecks/vision/checks/train_test_validation/train_test_label_drift.py
  spelling-allowlist.txt
  tests/tabular/checks/model_evaluation/train_test_prediction_drift_test.py
  tests/tabular/checks/train_test_validation/train_test_feature_drift_test.py
  tests/tabular/checks/train_test_validation/train_test_label_drift_test.py
  tests/vision/checks/model_evaluation/train_test_prediction_drift_test.py
  tests/vision/checks/train_test_validation/image_dataset_drift_test.py
  tests/vision/checks/train_test_validation/image_property_drift_test.py
  tests/vision/checks/train_test_validation/train_test_label_drift_test.py
Labels: feature

#2331 added exception or drift_mode!=prediction and balance_classes=True for prediction drift
  deepchecks/tabular/checks/model_evaluation/train_test_prediction_drift.py
  deepchecks/utils/distribution/drift.py
  tests/tabular/checks/model_evaluation/train_test_prediction_drift_test.py
Labels: bug

#2335 Fixed missed default
  deepchecks/utils/distribution/drift.py
Labels: bug

#2336 ignore min_category_size_ratio for balance_classes=True
  deepchecks/tabular/checks/model_evaluation/train_test_prediction_drift.py
  deepchecks/tabular/checks/train_test_validation/train_test_label_drift.py
  deepchecks/utils/distribution/drift.py
  deepchecks/vision/checks/model_evaluation/train_test_prediction_drift.py
  deepchecks/vision/checks/train_test_validation/train_test_label_drift.py
  tests/utils/drift_test.py
Labels: bug

#2337 Added the n_to_show parameter for the TrainTestSamplesMix test
  deepchecks/tabular/checks/train_test_validation/train_test_samples_mix.py
  tests/tabular/checks/train_test_validation/train_test_samples_mix_test.py
Labels: feature

#2338 Nb/nlp/tweet use case v2
  deepchecks/nlp/utils/embeddings_display.py
  tests/nlp/test_text_data.py
Labels: feature

#2339 added min_samples to all drift checks
  deepchecks/core/reduce_classes.py
  deepchecks/tabular/checks/model_evaluation/train_test_prediction_drift.py
  deepchecks/tabular/checks/train_test_validation/train_test_feature_drift.py
  deepchecks/tabular/checks/train_test_validation/train_test_label_drift.py
  deepchecks/utils/distribution/drift.py
  deepchecks/vision/checks/data_integrity/abstract_property_outliers.py
  deepchecks/vision/checks/data_integrity/image_property_outliers.py
  deepchecks/vision/checks/data_integrity/label_property_outliers.py
  deepchecks/vision/checks/data_integrity/property_label_correlation.py
  deepchecks/vision/checks/model_evaluation/train_test_prediction_drift.py
  deepchecks/vision/checks/model_evaluation/weak_segments_performance.py
  deepchecks/vision/checks/train_test_validation/image_dataset_drift.py
  deepchecks/vision/checks/train_test_validation/image_property_drift.py
  deepchecks/vision/checks/train_test_validation/property_label_correlation_change.py
  deepchecks/vision/checks/train_test_validation/train_test_label_drift.py
  deepchecks/vision/suites/default_suites.py
  tests/tabular/checks/model_evaluation/train_test_prediction_drift_test.py
  tests/tabular/checks/train_test_validation/train_test_feature_drift_test.py
  tests/tabular/checks/train_test_validation/train_test_label_drift_test.py
  tests/vision/checks/model_evaluation/train_test_prediction_drift_test.py
  tests/vision/checks/train_test_validation/image_property_drift_test.py
  tests/vision/checks/train_test_validation/train_test_label_drift_test.py
Labels: feature

#2340 Move the deepchecks metrics (fpr fnr tnr) multiclass versions to multiclass only
  deepchecks/tabular/metric_utils/scorers.py
Labels: bug

#2342 fix if on pandas object
  deepchecks/core/reduce_classes.py
Labels: bug

#2343 Fixing many issues in the docs
  deepchecks/tabular/checks/model_evaluation/regression_error_distribution.py
  deepchecks/tabular/checks/model_evaluation/weak_segments_performance.py
  deepchecks/tabular/suites/default_suites.py
  docs/source/checks/vision/model_evaluation/plot_train_test_prediction_drift.py
  docs/source/checks/vision/model_evaluation/plot_weak_segments_performance.py
  docs/source/nitpick-exceptions
  docs/source/user-guide/general/ci_cd.rst
  docs/source/user-guide/general/drift_guide.rst
  docs/source/user-guide/vision/tutorials/plot_classification_tutorial.py
  docs/source/user-guide/vision/tutorials/plot_custom_task_tutorial.py
  docs/source/user-guide/vision/tutorials/plot_detection_tutorial.py
  docs/source/user-guide/vision/tutorials/plot_segmentation_tutorial.py
Labels: documentation

#2347 small updates to vision data head
  deepchecks/vision/vision_data/vision_data.py
Labels: feature

#2346 fix train_test_prediction_drift reduce fails on value of 0
  deepchecks/tabular/checks/model_evaluation/train_test_prediction_drift.py
Labels: bug

#2348 Added validation and normalization of feature importance
  deepchecks/tabular/context.py
  deepchecks/tabular/utils/feature_importance.py
  docs/source/user-guide/tabular/feature_importance.rst
  tests/base/check_test.py
  tests/base/feature_importance_utils_test.py
Labels: bug

#2350 fixed bug in drift score min samples ordering
  deepchecks/tabular/checks/train_test_validation/train_test_feature_drift.py
Labels: bug

#2352 fix for binary scorer with single class
  deepchecks/tabular/metric_utils/scorers.py
  spelling-allowlist.txt
  tests/tabular/checks/model_evaluation/single_dataset_performance_test.py
Labels: bug

#2354 balance distributions in cramers v
  deepchecks/core/reduce_classes.py
  deepchecks/tabular/_shared_docs.py
  deepchecks/tabular/checks/train_test_validation/train_test_feature_drift.py
  deepchecks/tabular/context.py
  deepchecks/tabular/dataset.py
  deepchecks/tabular/datasets/regression/airbnb.py
  deepchecks/utils/distribution/drift.py
  deepchecks/utils/performance/weak_segment_abstract.py
  tests/tabular/checks/integrity/data_duplicate_test.py
  tests/tabular/checks/model_evaluation/train_test_prediction_drift_test.py
  tests/tabular/checks/train_test_validation/date_leakage_test.py
  tests/tabular/checks/train_test_validation/train_test_feature_drift_test.py
  tests/tabular/checks/train_test_validation/train_test_label_drift_test.py
  tests/utils/drift_test.py
  tests/vision/checks/train_test_validation/train_test_label_drift_test.py
Labels: feature

#2358 Fix calculate feature importance for regression
  deepchecks/tabular/feature_importance.py
  deepchecks/tabular/utils/feature_importance.py
  tests/base/feature_importance_utils_test.py
  tests/utils/metrics_test.py
Labels: bug

#2359 small spelling fix
  docs/source/user-guide/tabular/quickstarts/plot_quick_data_integrity.py
Labels: documentation
